package com.deloitte.nextgen.entities;

import com.deloitte.nextgen.entities.composite.T1004AppIndvId;
import lombok.*;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name ="T1004_APP_INDV")
@Data
@NoArgsConstructor
@IdClass(T1004AppIndvId.class)
public class T1004AppIndv implements Serializable {
    @Id
    @Column(name = "APP_NUM")
    private String appNum;
    @Column(name = "INDV_SEQ_NUM")
    private Long indvSeqNum;
    @Column(name = "ALN_SPONSER_SW")
    private Character alnSponserSw;
    @Column(name = "BC_RQST_SW")
    private Character bcRqstSw;
    @Column(name = "BRTH_DT")
    private java.sql.Timestamp brthDt;
    @Column(name = "FPW_RQST_SW")
    private Character fpwRqstSw;
    @Column(name = "FS_RQST_SW")
    private Character fsRqstSw;
    @Column(name = "FST_NAM")
    private String fstNam;
    @Column(name = "INDV_ESTB_STAT_IND")
    private Character indvEstbStatInd;
    @Column(name = "LAST_NAM")
    private String lastNam;
    @Column(name = "MA_RQST_SW")
    private Character maRqstSw;
    @Column(name = "MID_INIT")
    private String midInit;
    @Column(name = "PIN_NUM")
    private Long pinNum;
    @Column(name = "PRIM_PRSN_SW")
    private Character primPrsnSw;
    @Column(name = "SEX_IND")
    private Character sexInd;
    @Column(name = "SFX_NAM")
    private String sfxNam;
    @Column(name = "SNDX_NUM")
    private Character sndxNum;
    @Column(name = "SSN_NUM")
    private String ssnNum;
    @Column(name = "RLVN_IND")
    private Character rlvnInd;
    @Column(name = "INDV_EXISTS_IN_BRIDGES_SW")
    private Character indvExistsInBridgesSw;
    @Column(name = "BRIDGES_INDV_ID")
    private Long bridgesIndvId;
    @Column(name = "SE_RQST_SW")
    private Character seRqstSw;
    @Column(name = "VETERAN_SW")
    private Character veteranSw;
    @Column(name = "ALIAS_FST_NAM")
    private String aliasFstNam;
    @Column(name = "ALIAS_IND")
    private String aliasInd;
    @Column(name = "ALIAS_LAST_NAM")
    private String aliasLastNam;
    @Column(name = "ALIAS_MID_INIT")
    private String aliasMidInit;
    @Column(name = "ALIAS_SUFFIX_NAME")
    private String aliasSuffixName;
    @Column(name = "COMM_ASST_BAILLE_IND")
    private String commAsstBailleInd;
    @Column(name = "COMM_ASST_EMAIL_IND")
    private String commAsstEmailInd;
    @Column(name = "COMM_ASST_LG_PRINT_IND")
    private String commAsstLgPrintInd;
    @Column(name = "COMM_ASST_NONE_IND")
    private String commAsstNoneInd;
    @Column(name = "COMM_ASST_SL_INTERP_IND")
    private String commAsstSlInterpInd;
    @Column(name = "COMM_ASST_TTY_IND")
    private String commAsstTtyInd;
    @Column(name = "COMM_ASST_VEDREL_IND")
    private String commAsstVedrelInd;
    @Column(name = "BRST_CER_CANCER_DIAG_DT")
    private java.sql.Timestamp brstCerCancerDiagDt;
    @Column(name = "HSPC_DSC_CD")
    private String hspcDscCd;
    @Column(name = "IF_OUT_ARRANGEMENT")
    private String ifOutArrangement;
    @Column(name = "INTER_OTH_DSC")
    private String interOthDsc;
    @Column(name = "BRST_CER_CANCER_DIAG_IND")
    private String brstCerCancerDiagInd;
    @Column(name = "LANG_OTH_DSC")
    private String langOthDsc;
    @Column(name = "LIVE_AT_SAME_ADDR_IND")
    private String liveAtSameAddrInd;
    @Column(name = "RACE_CHINESE_IND")
    private String raceChineseInd;
    @Column(name = "RACE_FILIPINO_IND")
    private String raceFilipinoInd;
    @Column(name = "RACE_GUAM_IND")
    private String raceGuamInd;
    @Column(name = "RACE_JAPANESE_IND")
    private String raceJapaneseInd;
    @Column(name = "RACE_KOREAN_IND")
    private String raceKoreanInd;
    @Column(name = "RACE_MEMB_FED_REC_TRB_IND")
    private String raceMembFedRecTrbInd;
    @Column(name = "RACE_NHPI_IND")
    private String raceNhpiInd;
    @Column(name = "RACE_OTH_ASIAN_IND")
    private String raceOthAsianInd;
    @Column(name = "RACE_OTH_IND")
    private String raceOthInd;
    @Column(name = "RACE_SAMOAN_IND")
    private String raceSamoanInd;
    @Column(name = "RACE_VIE_IND")
    private String raceVieInd;
    @Column(name = "REQ_INTERP_IND")
    private String reqInterpInd;
    @Column(name = "SSN_INFO_ACK_IND")
    private String ssnInfoAckInd;
    @Column(name = "TAX_DP_OUTSIDE_HOME_IND")
    private String taxDpOutsideHomeInd;
    @Column(name = "TAX_JOINT_FILE_IND")
    private String taxJointFileInd;
    @Column(name = "TRIBE_NAME")
    private String tribeName;
    @Column(name = "BLND_DABL_IND")
    private String blndDablInd;
    @Column(name = "IS_MAPPED")
    private String isMapped;
    @Column(name = "IS_CHANGED")
    private String isChanged;
    @Column(name = "COMM_INTERP_RESP")
    private String commInterpResp;
    @Column(name = "COMM_INTERP_CD")
    private String commInterpCd;
    @Column(name = "COMM_ASST_FL_INTERP_IND")
    private String commAsstFlInterpInd;
    @Column(name = "LAW_PRES_FED_HUB_IND")
    private String lawPresFedHubInd;
    @Column(name = "NON_CTZN_FED_HUB_IND")
    private String nonCtznFedHubInd;
    @Column(name = "US_CTZN_FED_HUB_IND")
    private String usCtznFedHubInd;
    @Column(name = "SSN_VRFN_FED_HUB_IND")
    private String ssnVrfnFedHubInd;
    @Column(name = "DOB_FED_HUB_IND")
    private String dobFedHubInd;
    @Column(name = "UNEARNED_INC_DOL_IND")
    private String unearnedIncDolInd;
    @Column(name = "EARNED_INC_DOL_IND")
    private String earnedIncDolInd;
    @Column(name = "TAX_CL_OUTSIDE_HOME_IND")
    private String taxClOutsideHomeInd;
    @Column(name = "TAX_FILING_STATUS")
    private String taxFilingStatus;
    @Column(name = "RACE_EAST_ASIAN")
    private String raceEastAsian;
    @Column(name = "RACE_PERSIAN")
    private String racePersian;
    @Column(name = "RACE_UNKNOWN")
    private String raceUnknown;
    @Column(name = "REFERRAL_ID")
    private String referralId;
    @Column(name = "CHG_DT")
    private java.sql.Timestamp chgDt;
    @Column(name = "COURT_ORDER")
    private Character courtOrder;
    @Column(name = "CHILD_IN_DFCS_CUSTORY")
    private Character childInDfcsCustory;
    @Column(name = "CLIENT_ID")
    private Long clientId;
    @Column(name = "VETERAN_TYPE_SW")
    private Character veteranTypeSw;
    @Column(name = "DL_NUMBER")
    private String dlNumber;
    @Column(name = "DL_STATE_CD")
    private String dlStateCd;
    @Column(name = "DL_EXPIRATION_DT")
    private java.sql.Timestamp dlExpirationDt;
    @Column(name = "DL_VALID_SW")
    private String dlValidSw;
}
