CREATE SEQUENCE IF NOT EXISTS TYPE_ZERO_ENTITY_0SQ START WITH 1
INCREMENT BY 5 MINVALUE 1 MAXVALUE 999;
CREATE SEQUENCE IF NOT EXISTS TYPE_ZERO_ENTITY_1SQ START WITH 1
INCREMENT BY 5 MINVALUE 1 MAXVALUE 999;
CREATE SEQUENCE IF NOT EXISTS TYPE_ZERO_ENTITY_2SQ START WITH 1
INCREMENT BY 5 MINVALUE 1 MAXVALUE 999;
CREATE SEQUENCE IF NOT EXISTS TYPE_ONE_ENTITY_0SQ START WITH 1
INCREMENT BY 5 MINVALUE 1 MAXVALUE 999;
CREATE SEQUENCE IF NOT EXISTS TYPE_ONE_ENTITY_1SQ START WITH 1
INCREMENT BY 5 MINVALUE 1 MAXVALUE 999;
CREATE SEQUENCE IF NOT EXISTS TYPE_ONE_ENTITY_2SQ START WITH 1
INCREMENT BY 5 MINVALUE 1 MAXVALUE 999;
CREATE SEQUENCE IF NOT EXISTS TYPE_TWO_ENTITY_0SQ START WITH 1
INCREMENT BY 5 MINVALUE 1 MAXVALUE 999;
CREATE SEQUENCE IF NOT EXISTS TYPE_TWO_ENTITY_1SQ START WITH 1
INCREMENT BY 5 MINVALUE 1 MAXVALUE 999;
CREATE SEQUENCE IF NOT EXISTS TYPE_TWO_ENTITY_2SQ START WITH 1
INCREMENT BY 5 MINVALUE 1 MAXVALUE 999;