server:
  port: 8082
  compression:
    enabled: true
  servlet:
    contextPath: /ar

logging:
  level:
    root: DEBUG
    org.reflections: ERROR

spring:
  application:
    name: ApplicationRegistration
  jackson:
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@//localhost:1522/ORCL
    username: WP_AR_APP
    password: WP_AR_APP
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      poolName: applicationRegistration
      connectionTimeout: 10000
      maximumPoolSize: 2
      autoCommit: false
      connectionTestQuery: SELECT 1 FROM DUAL
      data-source-properties:
        cachePrepStmts: true
        perpStmtCacheSize: 250
        prepStmtCacheSqlLimits: 2048
        userServerPrepStmts: true

nextgen:
  reference-table:
    preload: false
  cors:
     allowed-origins:
#         - "http://15.207.142.199"
         - "http://localhost:5000"
#  jms:
#    broker-url: tcp://localhost:61616?jms.useAsyncSend=true
#    password: admin
#    user: admin
#    queue:
#      audit:
#        name: audit.log
#      error:
#        name: error.log



security:
  security:
    testing : true
address:
  smartystreet-service:
    auth-id: 263f07f0-e0a9-f580-ac0b-1e7fd9ebb003
    auth-token: t62pcICqWKkWpc3Awi1F
    url: https://us-street.api.smartystreets.com/street-address?

#
ssp:
  fetchSSPAppNumbers-service:
    url: http://localhost:8085/ar-ssp-api/stg-appsearch/v1/applications/appNum
  fetchSSPApplicants-service:
    url: http://localhost:8085/ar-ssp-api/conflictPanel/v1/Applicants/appNum
  fetchSSPContacts-service:
    url: http://localhost:8085/ar-ssp-api/conflictPanel/v1/Contacts/appNum
  fetchSSPAuthRep-service:
    url: http://localhost:8085/ar-ssp-api/conflictPanel/v1/authRep-details/appNum
  fetchSSPContactConflicts-service:
    url: http://localhost:8085/ar-ssp-api/conflictPanel/v1/contact-conflicts/appNum
  fetchSSPAuthRepConflicts-service:
    url: http://localhost:8085/ar-ssp-api/conflictPanel/v1/authRep-conflicts/appNum
  fetchSSPSnapDetails-service:
    url: http://localhost:8085/ar-ssp-api/program/v1/snap-expedited-details/appNum
  fetchSSPProgram-service:
    url: http://localhost:8085/ar-ssp-api/program/v1/app-programs/appNum