package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Am508DetailsA generated by hbm2java
 */
@Entity
@Table(name="AM_508_DETAILS_A"
    ,schema="IE_APP_ONLINE"
)
public class Am508DetailsA  implements java.io.Serializable {


     private Am508DetailsAId id;
     private String hcwrOigNum;
     private String hcwrSchedHearingCd;
     private String delayExplanation;
     private String wicVendorId;
     private LocalDate wicDenailDt;
     private String wicDocketNum;
     private String wicStoreNum;
     private String wicStoreOwner;
     private String depAppealNum;
     private String corpAgentName;
     private LocalDate deptNoticeDt;
     private String typeOfHearingCd;
     private String detailNotes;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String auditUserId;
     private LocalDate auditDt;
     private String miscNotes;

    public Am508DetailsA() {
    }

	
    public Am508DetailsA(Am508DetailsAId id, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
        this.id = id;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
        this.auditUserId = auditUserId;
        this.auditDt = auditDt;
    }
    public Am508DetailsA(Am508DetailsAId id, String hcwrOigNum, String hcwrSchedHearingCd, String delayExplanation, String wicVendorId, LocalDate wicDenailDt, String wicDocketNum, String wicStoreNum, String wicStoreOwner, String depAppealNum, String corpAgentName, LocalDate deptNoticeDt, String typeOfHearingCd, String detailNotes, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt, String miscNotes) {
       this.id = id;
       this.hcwrOigNum = hcwrOigNum;
       this.hcwrSchedHearingCd = hcwrSchedHearingCd;
       this.delayExplanation = delayExplanation;
       this.wicVendorId = wicVendorId;
       this.wicDenailDt = wicDenailDt;
       this.wicDocketNum = wicDocketNum;
       this.wicStoreNum = wicStoreNum;
       this.wicStoreOwner = wicStoreOwner;
       this.depAppealNum = depAppealNum;
       this.corpAgentName = corpAgentName;
       this.deptNoticeDt = deptNoticeDt;
       this.typeOfHearingCd = typeOfHearingCd;
       this.detailNotes = detailNotes;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.auditUserId = auditUserId;
       this.auditDt = auditDt;
       this.miscNotes = miscNotes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="am508Seq", column=@Column(name="AM_508_SEQ", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="aplNum", column=@Column(name="APL_NUM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="historySeq", column=@Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0) ) } )
    public Am508DetailsAId getId() {
        return this.id;
    }
    
    public void setId(Am508DetailsAId id) {
        this.id = id;
    }

    
    @Column(name="HCWR_OIG_NUM", length=25)
    public String getHcwrOigNum() {
        return this.hcwrOigNum;
    }
    
    public void setHcwrOigNum(String hcwrOigNum) {
        this.hcwrOigNum = hcwrOigNum;
    }

    
    @Column(name="HCWR_SCHED_HEARING_CD", length=2)
    public String getHcwrSchedHearingCd() {
        return this.hcwrSchedHearingCd;
    }
    
    public void setHcwrSchedHearingCd(String hcwrSchedHearingCd) {
        this.hcwrSchedHearingCd = hcwrSchedHearingCd;
    }

    
    @Column(name="DELAY_EXPLANATION", length=4000)
    public String getDelayExplanation() {
        return this.delayExplanation;
    }
    
    public void setDelayExplanation(String delayExplanation) {
        this.delayExplanation = delayExplanation;
    }

    
    @Column(name="WIC_VENDOR_ID", length=20)
    public String getWicVendorId() {
        return this.wicVendorId;
    }
    
    public void setWicVendorId(String wicVendorId) {
        this.wicVendorId = wicVendorId;
    }

    
    @Column(name="WIC_DENAIL_DT", length=7)
    public LocalDate getWicDenailDt() {
        return this.wicDenailDt;
    }
    
    public void setWicDenailDt(LocalDate wicDenailDt) {
        this.wicDenailDt = wicDenailDt;
    }

    
    @Column(name="WIC_DOCKET_NUM", length=25)
    public String getWicDocketNum() {
        return this.wicDocketNum;
    }
    
    public void setWicDocketNum(String wicDocketNum) {
        this.wicDocketNum = wicDocketNum;
    }

    
    @Column(name="WIC_STORE_NUM", length=25)
    public String getWicStoreNum() {
        return this.wicStoreNum;
    }
    
    public void setWicStoreNum(String wicStoreNum) {
        this.wicStoreNum = wicStoreNum;
    }

    
    @Column(name="WIC_STORE_OWNER", length=50)
    public String getWicStoreOwner() {
        return this.wicStoreOwner;
    }
    
    public void setWicStoreOwner(String wicStoreOwner) {
        this.wicStoreOwner = wicStoreOwner;
    }

    
    @Column(name="DEP_APPEAL_NUM", length=25)
    public String getDepAppealNum() {
        return this.depAppealNum;
    }
    
    public void setDepAppealNum(String depAppealNum) {
        this.depAppealNum = depAppealNum;
    }

    
    @Column(name="CORP_AGENT_NAME", length=50)
    public String getCorpAgentName() {
        return this.corpAgentName;
    }
    
    public void setCorpAgentName(String corpAgentName) {
        this.corpAgentName = corpAgentName;
    }

    
    @Column(name="DEPT_NOTICE_DT", length=7)
    public LocalDate getDeptNoticeDt() {
        return this.deptNoticeDt;
    }
    
    public void setDeptNoticeDt(LocalDate deptNoticeDt) {
        this.deptNoticeDt = deptNoticeDt;
    }

    
    @Column(name="TYPE_OF_HEARING_CD", length=5)
    public String getTypeOfHearingCd() {
        return this.typeOfHearingCd;
    }
    
    public void setTypeOfHearingCd(String typeOfHearingCd) {
        this.typeOfHearingCd = typeOfHearingCd;
    }

    
    @Column(name="DETAIL_NOTES", length=4000)
    public String getDetailNotes() {
        return this.detailNotes;
    }
    
    public void setDetailNotes(String detailNotes) {
        this.detailNotes = detailNotes;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AUDIT_USER_ID", nullable=false, length=20)
    public String getAuditUserId() {
        return this.auditUserId;
    }
    
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    
    @Column(name="AUDIT_DT", nullable=false, length=7)
    public LocalDate getAuditDt() {
        return this.auditDt;
    }
    
    public void setAuditDt(LocalDate auditDt) {
        this.auditDt = auditDt;
    }

    
    @Column(name="MISC_NOTES", length=4000)
    public String getMiscNotes() {
        return this.miscNotes;
    }
    
    public void setMiscNotes(String miscNotes) {
        this.miscNotes = miscNotes;
    }




}


