package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Am508DetailsAId generated by hbm2java
 */
@Embeddable
public class Am508DetailsAId  implements java.io.Serializable {


     private BigInteger am508Seq;
     private BigInteger aplNum;
     private BigInteger historySeq;

    public Am508DetailsAId() {
    }

    public Am508DetailsAId(BigInteger am508Seq, BigInteger aplNum, BigInteger historySeq) {
       this.am508Seq = am508Seq;
       this.aplNum = aplNum;
       this.historySeq = historySeq;
    }
   


    @Column(name="AM_508_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getAm508Seq() {
        return this.am508Seq;
    }
    
    public void setAm508Seq(BigInteger am508Seq) {
        this.am508Seq = am508Seq;
    }


    @Column(name="APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Am508DetailsAId) ) return false;
		 Am508DetailsAId castOther = ( Am508DetailsAId ) other; 
         
		 return ( (this.getAm508Seq()==castOther.getAm508Seq()) || ( this.getAm508Seq()!=null && castOther.getAm508Seq()!=null && this.getAm508Seq().equals(castOther.getAm508Seq()) ) )
 && ( (this.getAplNum()==castOther.getAplNum()) || ( this.getAplNum()!=null && castOther.getAplNum()!=null && this.getAplNum().equals(castOther.getAplNum()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAm508Seq() == null ? 0 : this.getAm508Seq().hashCode() );
         result = 37 * result + ( getAplNum() == null ? 0 : this.getAplNum().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


