package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmAdminReview generated by hbm2java
 */
@Entity
@Table(name="AM_ADMIN_REVIEW"
    ,schema="IE_APP_ONLINE"
)
public class AmAdminReview  implements java.io.Serializable {


     private String aplNum;
     private BigInteger amAdminReviewSeqNum;
     private String courtCaseNum;
     private Character proSeFilingInd;
     private LocalDate dtComplaintFiled;
     private String judicialCircutCd;
     private String caseStatCd;
     private String ansStatCd;
     private LocalDate dtTranscriptRecvd;
     private LocalDate dtAssigned;
     private LocalDate dtAnsSentToAag;
     private LocalDate dtTranscriptReq;
     private String crossRefAplNum;
     private String unableToBeCompletedNote;
     private LocalDate dhsBriefFiledDt;
     private String aagRepReqCd;
     private String summonsSrvedCd;
     private LocalDate dtAagRepReq;
     private LocalDate dtSummonsSrved;
     private String aagAssigned;
     private String briefingSchOrdCd;
     private LocalDate courtHrngSchDt;
     private LocalDate complnBriefFiledDt;
     private String genCounselNotes;
     private String adRwDispositionCd;
     private String aplCourtRevInd;
     private String ilSupCourtRevInd;
     private String dispositionNotes;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;

    public AmAdminReview() {
    }

	
    public AmAdminReview(String aplNum, BigInteger amAdminReviewSeqNum, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.aplNum = aplNum;
        this.amAdminReviewSeqNum = amAdminReviewSeqNum;
        this.historySeq = historySeq;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmAdminReview(String aplNum, BigInteger amAdminReviewSeqNum, String courtCaseNum, Character proSeFilingInd, LocalDate dtComplaintFiled, String judicialCircutCd, String caseStatCd, String ansStatCd, LocalDate dtTranscriptRecvd, LocalDate dtAssigned, LocalDate dtAnsSentToAag, LocalDate dtTranscriptReq, String crossRefAplNum, String unableToBeCompletedNote, LocalDate dhsBriefFiledDt, String aagRepReqCd, String summonsSrvedCd, LocalDate dtAagRepReq, LocalDate dtSummonsSrved, String aagAssigned, String briefingSchOrdCd, LocalDate courtHrngSchDt, LocalDate complnBriefFiledDt, String genCounselNotes, String adRwDispositionCd, String aplCourtRevInd, String ilSupCourtRevInd, String dispositionNotes, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
       this.aplNum = aplNum;
       this.amAdminReviewSeqNum = amAdminReviewSeqNum;
       this.courtCaseNum = courtCaseNum;
       this.proSeFilingInd = proSeFilingInd;
       this.dtComplaintFiled = dtComplaintFiled;
       this.judicialCircutCd = judicialCircutCd;
       this.caseStatCd = caseStatCd;
       this.ansStatCd = ansStatCd;
       this.dtTranscriptRecvd = dtTranscriptRecvd;
       this.dtAssigned = dtAssigned;
       this.dtAnsSentToAag = dtAnsSentToAag;
       this.dtTranscriptReq = dtTranscriptReq;
       this.crossRefAplNum = crossRefAplNum;
       this.unableToBeCompletedNote = unableToBeCompletedNote;
       this.dhsBriefFiledDt = dhsBriefFiledDt;
       this.aagRepReqCd = aagRepReqCd;
       this.summonsSrvedCd = summonsSrvedCd;
       this.dtAagRepReq = dtAagRepReq;
       this.dtSummonsSrved = dtSummonsSrved;
       this.aagAssigned = aagAssigned;
       this.briefingSchOrdCd = briefingSchOrdCd;
       this.courtHrngSchDt = courtHrngSchDt;
       this.complnBriefFiledDt = complnBriefFiledDt;
       this.genCounselNotes = genCounselNotes;
       this.adRwDispositionCd = adRwDispositionCd;
       this.aplCourtRevInd = aplCourtRevInd;
       this.ilSupCourtRevInd = ilSupCourtRevInd;
       this.dispositionNotes = dispositionNotes;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
    }
   
     @Id 

    
    @Column(name="APL_NUM", unique=true, nullable=false, length=10)
    public String getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(String aplNum) {
        this.aplNum = aplNum;
    }

    
    @Column(name="AM_ADMIN_REVIEW_SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAmAdminReviewSeqNum() {
        return this.amAdminReviewSeqNum;
    }
    
    public void setAmAdminReviewSeqNum(BigInteger amAdminReviewSeqNum) {
        this.amAdminReviewSeqNum = amAdminReviewSeqNum;
    }

    
    @Column(name="COURT_CASE_NUM", length=20)
    public String getCourtCaseNum() {
        return this.courtCaseNum;
    }
    
    public void setCourtCaseNum(String courtCaseNum) {
        this.courtCaseNum = courtCaseNum;
    }

    
    @Column(name="PRO_SE_FILING_IND", length=1)
    public Character getProSeFilingInd() {
        return this.proSeFilingInd;
    }
    
    public void setProSeFilingInd(Character proSeFilingInd) {
        this.proSeFilingInd = proSeFilingInd;
    }

    
    @Column(name="DT_COMPLAINT_FILED", length=7)
    public LocalDate getDtComplaintFiled() {
        return this.dtComplaintFiled;
    }
    
    public void setDtComplaintFiled(LocalDate dtComplaintFiled) {
        this.dtComplaintFiled = dtComplaintFiled;
    }

    
    @Column(name="JUDICIAL_CIRCUT_CD", length=5)
    public String getJudicialCircutCd() {
        return this.judicialCircutCd;
    }
    
    public void setJudicialCircutCd(String judicialCircutCd) {
        this.judicialCircutCd = judicialCircutCd;
    }

    
    @Column(name="CASE_STAT_CD", length=5)
    public String getCaseStatCd() {
        return this.caseStatCd;
    }
    
    public void setCaseStatCd(String caseStatCd) {
        this.caseStatCd = caseStatCd;
    }

    
    @Column(name="ANS_STAT_CD", length=5)
    public String getAnsStatCd() {
        return this.ansStatCd;
    }
    
    public void setAnsStatCd(String ansStatCd) {
        this.ansStatCd = ansStatCd;
    }

    
    @Column(name="DT_TRANSCRIPT_RECVD", length=7)
    public LocalDate getDtTranscriptRecvd() {
        return this.dtTranscriptRecvd;
    }
    
    public void setDtTranscriptRecvd(LocalDate dtTranscriptRecvd) {
        this.dtTranscriptRecvd = dtTranscriptRecvd;
    }

    
    @Column(name="DT_ASSIGNED", length=7)
    public LocalDate getDtAssigned() {
        return this.dtAssigned;
    }
    
    public void setDtAssigned(LocalDate dtAssigned) {
        this.dtAssigned = dtAssigned;
    }

    
    @Column(name="DT_ANS_SENT_TO_AAG", length=7)
    public LocalDate getDtAnsSentToAag() {
        return this.dtAnsSentToAag;
    }
    
    public void setDtAnsSentToAag(LocalDate dtAnsSentToAag) {
        this.dtAnsSentToAag = dtAnsSentToAag;
    }

    
    @Column(name="DT_TRANSCRIPT_REQ", length=7)
    public LocalDate getDtTranscriptReq() {
        return this.dtTranscriptReq;
    }
    
    public void setDtTranscriptReq(LocalDate dtTranscriptReq) {
        this.dtTranscriptReq = dtTranscriptReq;
    }

    
    @Column(name="CROSS_REF_APL_NUM", length=20)
    public String getCrossRefAplNum() {
        return this.crossRefAplNum;
    }
    
    public void setCrossRefAplNum(String crossRefAplNum) {
        this.crossRefAplNum = crossRefAplNum;
    }

    
    @Column(name="UNABLE_TO_BE_COMPLETED_NOTE", length=4000)
    public String getUnableToBeCompletedNote() {
        return this.unableToBeCompletedNote;
    }
    
    public void setUnableToBeCompletedNote(String unableToBeCompletedNote) {
        this.unableToBeCompletedNote = unableToBeCompletedNote;
    }

    
    @Column(name="DHS_BRIEF_FILED_DT", length=7)
    public LocalDate getDhsBriefFiledDt() {
        return this.dhsBriefFiledDt;
    }
    
    public void setDhsBriefFiledDt(LocalDate dhsBriefFiledDt) {
        this.dhsBriefFiledDt = dhsBriefFiledDt;
    }

    
    @Column(name="AAG_REP_REQ_CD", length=5)
    public String getAagRepReqCd() {
        return this.aagRepReqCd;
    }
    
    public void setAagRepReqCd(String aagRepReqCd) {
        this.aagRepReqCd = aagRepReqCd;
    }

    
    @Column(name="SUMMONS_SRVED_CD", length=5)
    public String getSummonsSrvedCd() {
        return this.summonsSrvedCd;
    }
    
    public void setSummonsSrvedCd(String summonsSrvedCd) {
        this.summonsSrvedCd = summonsSrvedCd;
    }

    
    @Column(name="DT_AAG_REP_REQ", length=7)
    public LocalDate getDtAagRepReq() {
        return this.dtAagRepReq;
    }
    
    public void setDtAagRepReq(LocalDate dtAagRepReq) {
        this.dtAagRepReq = dtAagRepReq;
    }

    
    @Column(name="DT_SUMMONS_SRVED", length=7)
    public LocalDate getDtSummonsSrved() {
        return this.dtSummonsSrved;
    }
    
    public void setDtSummonsSrved(LocalDate dtSummonsSrved) {
        this.dtSummonsSrved = dtSummonsSrved;
    }

    
    @Column(name="AAG_ASSIGNED", length=25)
    public String getAagAssigned() {
        return this.aagAssigned;
    }
    
    public void setAagAssigned(String aagAssigned) {
        this.aagAssigned = aagAssigned;
    }

    
    @Column(name="BRIEFING_SCH_ORD_CD", length=5)
    public String getBriefingSchOrdCd() {
        return this.briefingSchOrdCd;
    }
    
    public void setBriefingSchOrdCd(String briefingSchOrdCd) {
        this.briefingSchOrdCd = briefingSchOrdCd;
    }

    
    @Column(name="COURT_HRNG_SCH_DT", length=7)
    public LocalDate getCourtHrngSchDt() {
        return this.courtHrngSchDt;
    }
    
    public void setCourtHrngSchDt(LocalDate courtHrngSchDt) {
        this.courtHrngSchDt = courtHrngSchDt;
    }

    
    @Column(name="COMPLN_BRIEF_FILED_DT", length=7)
    public LocalDate getComplnBriefFiledDt() {
        return this.complnBriefFiledDt;
    }
    
    public void setComplnBriefFiledDt(LocalDate complnBriefFiledDt) {
        this.complnBriefFiledDt = complnBriefFiledDt;
    }

    
    @Column(name="GEN_COUNSEL_NOTES", length=500)
    public String getGenCounselNotes() {
        return this.genCounselNotes;
    }
    
    public void setGenCounselNotes(String genCounselNotes) {
        this.genCounselNotes = genCounselNotes;
    }

    
    @Column(name="AD_RW_DISPOSITION_CD", length=5)
    public String getAdRwDispositionCd() {
        return this.adRwDispositionCd;
    }
    
    public void setAdRwDispositionCd(String adRwDispositionCd) {
        this.adRwDispositionCd = adRwDispositionCd;
    }

    
    @Column(name="APL_COURT_REV_IND", length=3)
    public String getAplCourtRevInd() {
        return this.aplCourtRevInd;
    }
    
    public void setAplCourtRevInd(String aplCourtRevInd) {
        this.aplCourtRevInd = aplCourtRevInd;
    }

    
    @Column(name="IL_SUP_COURT_REV_IND", length=3)
    public String getIlSupCourtRevInd() {
        return this.ilSupCourtRevInd;
    }
    
    public void setIlSupCourtRevInd(String ilSupCourtRevInd) {
        this.ilSupCourtRevInd = ilSupCourtRevInd;
    }

    
    @Column(name="DISPOSITION_NOTES", length=4000)
    public String getDispositionNotes() {
        return this.dispositionNotes;
    }
    
    public void setDispositionNotes(String dispositionNotes) {
        this.dispositionNotes = dispositionNotes;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }




}


