package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmAdditionalDetailsId generated by hbm2java
 */
@Embeddable
public class AmAdditionalDetailsId  implements java.io.Serializable {


     private BigInteger amAddlSeqNum;
     private BigInteger aplNum;

    public AmAdditionalDetailsId() {
    }

    public AmAdditionalDetailsId(BigInteger amAddlSeqNum, BigInteger aplNum) {
       this.amAddlSeqNum = amAddlSeqNum;
       this.aplNum = aplNum;
    }
   


    @Column(name="AM_ADDL_SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAmAddlSeqNum() {
        return this.amAddlSeqNum;
    }
    
    public void setAmAddlSeqNum(BigInteger amAddlSeqNum) {
        this.amAddlSeqNum = amAddlSeqNum;
    }


    @Column(name="APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmAdditionalDetailsId) ) return false;
		 AmAdditionalDetailsId castOther = ( AmAdditionalDetailsId ) other; 
         
		 return ( (this.getAmAddlSeqNum()==castOther.getAmAddlSeqNum()) || ( this.getAmAddlSeqNum()!=null && castOther.getAmAddlSeqNum()!=null && this.getAmAddlSeqNum().equals(castOther.getAmAddlSeqNum()) ) )
 && ( (this.getAplNum()==castOther.getAplNum()) || ( this.getAplNum()!=null && castOther.getAplNum()!=null && this.getAplNum().equals(castOther.getAplNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAmAddlSeqNum() == null ? 0 : this.getAmAddlSeqNum().hashCode() );
         result = 37 * result + ( getAplNum() == null ? 0 : this.getAplNum().hashCode() );
         return result;
   }   


}


