package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmAdditionalDetails generated by hbm2java
 */
@Entity
@Table(name="AM_ADDITIONAL_DETAILS"
    ,schema="IE_APP_ONLINE"
)
public class AmAdditionalDetails  implements java.io.Serializable {


     private AmAdditionalDetailsId id;
     private String incarceratedId;
     private String doNotScheduleId;
     private String adminReviewId;
     private String physicalRecordsId;
     private BigInteger hearingOfficerId;
     private BigInteger hearingSupervisorId;
     private LocalDate applicationDt;
     private LocalDate denialDt;
     private LocalDate miscellaneousDt;
     private LocalDate miscellaneousDenailDt;
     private String misc1Data;
     private String misc2Data;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private BigInteger reviewerCd;
     private Character expeditedSw;
     private Character inPersonSchdlSw;
     private BigInteger attorneyEmpId;
     private BigInteger witnessEmpId;
     private LocalDate updateDt;
     private String updateUserId;
     private String aschdProcessTxt;

    public AmAdditionalDetails() {
    }

	
    public AmAdditionalDetails(AmAdditionalDetailsId id, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.id = id;
        this.historySeq = historySeq;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmAdditionalDetails(AmAdditionalDetailsId id, String incarceratedId, String doNotScheduleId, String adminReviewId, String physicalRecordsId, BigInteger hearingOfficerId, BigInteger hearingSupervisorId, LocalDate applicationDt, LocalDate denialDt, LocalDate miscellaneousDt, LocalDate miscellaneousDenailDt, String misc1Data, String misc2Data, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, BigInteger reviewerCd, Character expeditedSw, Character inPersonSchdlSw, BigInteger attorneyEmpId, BigInteger witnessEmpId, LocalDate updateDt, String updateUserId, String aschdProcessTxt) {
       this.id = id;
       this.incarceratedId = incarceratedId;
       this.doNotScheduleId = doNotScheduleId;
       this.adminReviewId = adminReviewId;
       this.physicalRecordsId = physicalRecordsId;
       this.hearingOfficerId = hearingOfficerId;
       this.hearingSupervisorId = hearingSupervisorId;
       this.applicationDt = applicationDt;
       this.denialDt = denialDt;
       this.miscellaneousDt = miscellaneousDt;
       this.miscellaneousDenailDt = miscellaneousDenailDt;
       this.misc1Data = misc1Data;
       this.misc2Data = misc2Data;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.reviewerCd = reviewerCd;
       this.expeditedSw = expeditedSw;
       this.inPersonSchdlSw = inPersonSchdlSw;
       this.attorneyEmpId = attorneyEmpId;
       this.witnessEmpId = witnessEmpId;
       this.updateDt = updateDt;
       this.updateUserId = updateUserId;
       this.aschdProcessTxt = aschdProcessTxt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="amAddlSeqNum", column=@Column(name="AM_ADDL_SEQ_NUM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="aplNum", column=@Column(name="APL_NUM", nullable=false, precision=22, scale=0) ) } )
    public AmAdditionalDetailsId getId() {
        return this.id;
    }
    
    public void setId(AmAdditionalDetailsId id) {
        this.id = id;
    }

    
    @Column(name="INCARCERATED_ID", length=2)
    public String getIncarceratedId() {
        return this.incarceratedId;
    }
    
    public void setIncarceratedId(String incarceratedId) {
        this.incarceratedId = incarceratedId;
    }

    
    @Column(name="DO_NOT_SCHEDULE_ID", length=2)
    public String getDoNotScheduleId() {
        return this.doNotScheduleId;
    }
    
    public void setDoNotScheduleId(String doNotScheduleId) {
        this.doNotScheduleId = doNotScheduleId;
    }

    
    @Column(name="ADMIN_REVIEW_ID", length=2)
    public String getAdminReviewId() {
        return this.adminReviewId;
    }
    
    public void setAdminReviewId(String adminReviewId) {
        this.adminReviewId = adminReviewId;
    }

    
    @Column(name="PHYSICAL_RECORDS_ID", length=2)
    public String getPhysicalRecordsId() {
        return this.physicalRecordsId;
    }
    
    public void setPhysicalRecordsId(String physicalRecordsId) {
        this.physicalRecordsId = physicalRecordsId;
    }

    
    @Column(name="HEARING_OFFICER_ID", precision=22, scale=0)
    public BigInteger getHearingOfficerId() {
        return this.hearingOfficerId;
    }
    
    public void setHearingOfficerId(BigInteger hearingOfficerId) {
        this.hearingOfficerId = hearingOfficerId;
    }

    
    @Column(name="HEARING_SUPERVISOR_ID", precision=22, scale=0)
    public BigInteger getHearingSupervisorId() {
        return this.hearingSupervisorId;
    }
    
    public void setHearingSupervisorId(BigInteger hearingSupervisorId) {
        this.hearingSupervisorId = hearingSupervisorId;
    }

    
    @Column(name="APPLICATION_DT", length=7)
    public LocalDate getApplicationDt() {
        return this.applicationDt;
    }
    
    public void setApplicationDt(LocalDate applicationDt) {
        this.applicationDt = applicationDt;
    }

    
    @Column(name="DENIAL_DT", length=7)
    public LocalDate getDenialDt() {
        return this.denialDt;
    }
    
    public void setDenialDt(LocalDate denialDt) {
        this.denialDt = denialDt;
    }

    
    @Column(name="MISCELLANEOUS_DT", length=7)
    public LocalDate getMiscellaneousDt() {
        return this.miscellaneousDt;
    }
    
    public void setMiscellaneousDt(LocalDate miscellaneousDt) {
        this.miscellaneousDt = miscellaneousDt;
    }

    
    @Column(name="MISCELLANEOUS_DENAIL_DT", length=7)
    public LocalDate getMiscellaneousDenailDt() {
        return this.miscellaneousDenailDt;
    }
    
    public void setMiscellaneousDenailDt(LocalDate miscellaneousDenailDt) {
        this.miscellaneousDenailDt = miscellaneousDenailDt;
    }

    
    @Column(name="MISC1_DATA", length=200)
    public String getMisc1Data() {
        return this.misc1Data;
    }
    
    public void setMisc1Data(String misc1Data) {
        this.misc1Data = misc1Data;
    }

    
    @Column(name="MISC2_DATA", length=200)
    public String getMisc2Data() {
        return this.misc2Data;
    }
    
    public void setMisc2Data(String misc2Data) {
        this.misc2Data = misc2Data;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="REVIEWER_CD", precision=22, scale=0)
    public BigInteger getReviewerCd() {
        return this.reviewerCd;
    }
    
    public void setReviewerCd(BigInteger reviewerCd) {
        this.reviewerCd = reviewerCd;
    }

    
    @Column(name="EXPEDITED_SW", length=1)
    public Character getExpeditedSw() {
        return this.expeditedSw;
    }
    
    public void setExpeditedSw(Character expeditedSw) {
        this.expeditedSw = expeditedSw;
    }

    
    @Column(name="IN_PERSON_SCHDL_SW", length=1)
    public Character getInPersonSchdlSw() {
        return this.inPersonSchdlSw;
    }
    
    public void setInPersonSchdlSw(Character inPersonSchdlSw) {
        this.inPersonSchdlSw = inPersonSchdlSw;
    }

    
    @Column(name="ATTORNEY_EMP_ID", precision=22, scale=0)
    public BigInteger getAttorneyEmpId() {
        return this.attorneyEmpId;
    }
    
    public void setAttorneyEmpId(BigInteger attorneyEmpId) {
        this.attorneyEmpId = attorneyEmpId;
    }

    
    @Column(name="WITNESS_EMP_ID", precision=22, scale=0)
    public BigInteger getWitnessEmpId() {
        return this.witnessEmpId;
    }
    
    public void setWitnessEmpId(BigInteger witnessEmpId) {
        this.witnessEmpId = witnessEmpId;
    }

    
    @Column(name="UPDATE_DT", length=7)
    public LocalDate getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(LocalDate updateDt) {
        this.updateDt = updateDt;
    }

    
    @Column(name="UPDATE_USER_ID", length=20)
    public String getUpdateUserId() {
        return this.updateUserId;
    }
    
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    
    @Column(name="ASCHD_PROCESS_TXT", length=500)
    public String getAschdProcessTxt() {
        return this.aschdProcessTxt;
    }
    
    public void setAschdProcessTxt(String aschdProcessTxt) {
        this.aschdProcessTxt = aschdProcessTxt;
    }




}


