package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmApprRejDtl generated by hbm2java
 */
@Entity
@Table(name="AM_APPR_REJ_DTL"
    ,schema="IE_APP_ONLINE"
)
public class AmApprRejDtl  implements java.io.Serializable {


     private BigInteger amApprRejDtlSeqNum;
     private BigInteger aplNum;
     private String rqstFrmCd;
     private String rqstTypCd;
     private String rqstRsn;
     private String apprTypCd;
     private String rqstExpln;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private BigInteger docketId;
     private String otherWitnessTxt;
     private Character orderSignedSw;
     private String orderTypCd;
     private LocalDate orderSignedDt;
     private LocalDate contPetitionDt;
     private LocalDate orderSubmitReviewDt;
     private LocalDate orderReturnDt;
     private String contRequestByCd;
     private String continuanceRqstCd;
     private Character sendNohAttachSw;
     private String reasonHldOpnCd;
     private LocalDate infoReceivedDt;
     private LocalDate recordHeldOpenDt;
     private Character petRqstTmlySw;
     private LocalDate petitionDueDt;
     private LocalDate updateDt;
     private String updateUserId;
     private LocalDateTime decisionDt;

    public AmApprRejDtl() {
    }

	
    public AmApprRejDtl(BigInteger amApprRejDtlSeqNum, BigInteger aplNum, String rqstFrmCd, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.amApprRejDtlSeqNum = amApprRejDtlSeqNum;
        this.aplNum = aplNum;
        this.rqstFrmCd = rqstFrmCd;
        this.historySeq = historySeq;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmApprRejDtl(BigInteger amApprRejDtlSeqNum, BigInteger aplNum, String rqstFrmCd, String rqstTypCd, String rqstRsn, String apprTypCd, String rqstExpln, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, BigInteger docketId, String otherWitnessTxt, Character orderSignedSw, String orderTypCd, LocalDate orderSignedDt, LocalDate contPetitionDt, LocalDate orderSubmitReviewDt, LocalDate orderReturnDt, String contRequestByCd, String continuanceRqstCd, Character sendNohAttachSw, String reasonHldOpnCd, LocalDate infoReceivedDt, LocalDate recordHeldOpenDt, Character petRqstTmlySw, LocalDate petitionDueDt, LocalDate updateDt, String updateUserId, LocalDateTime decisionDt) {
       this.amApprRejDtlSeqNum = amApprRejDtlSeqNum;
       this.aplNum = aplNum;
       this.rqstFrmCd = rqstFrmCd;
       this.rqstTypCd = rqstTypCd;
       this.rqstRsn = rqstRsn;
       this.apprTypCd = apprTypCd;
       this.rqstExpln = rqstExpln;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.docketId = docketId;
       this.otherWitnessTxt = otherWitnessTxt;
       this.orderSignedSw = orderSignedSw;
       this.orderTypCd = orderTypCd;
       this.orderSignedDt = orderSignedDt;
       this.contPetitionDt = contPetitionDt;
       this.orderSubmitReviewDt = orderSubmitReviewDt;
       this.orderReturnDt = orderReturnDt;
       this.contRequestByCd = contRequestByCd;
       this.continuanceRqstCd = continuanceRqstCd;
       this.sendNohAttachSw = sendNohAttachSw;
       this.reasonHldOpnCd = reasonHldOpnCd;
       this.infoReceivedDt = infoReceivedDt;
       this.recordHeldOpenDt = recordHeldOpenDt;
       this.petRqstTmlySw = petRqstTmlySw;
       this.petitionDueDt = petitionDueDt;
       this.updateDt = updateDt;
       this.updateUserId = updateUserId;
       this.decisionDt = decisionDt;
    }
   
     @Id 

    
    @Column(name="AM_APPR_REJ_DTL_SEQ_NUM", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getAmApprRejDtlSeqNum() {
        return this.amApprRejDtlSeqNum;
    }
    
    public void setAmApprRejDtlSeqNum(BigInteger amApprRejDtlSeqNum) {
        this.amApprRejDtlSeqNum = amApprRejDtlSeqNum;
    }

    
    @Column(name="APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }

    
    @Column(name="RQST_FRM_CD", nullable=false, length=10)
    public String getRqstFrmCd() {
        return this.rqstFrmCd;
    }
    
    public void setRqstFrmCd(String rqstFrmCd) {
        this.rqstFrmCd = rqstFrmCd;
    }

    
    @Column(name="RQST_TYP_CD", length=5)
    public String getRqstTypCd() {
        return this.rqstTypCd;
    }
    
    public void setRqstTypCd(String rqstTypCd) {
        this.rqstTypCd = rqstTypCd;
    }

    
    @Column(name="RQST_RSN", length=5)
    public String getRqstRsn() {
        return this.rqstRsn;
    }
    
    public void setRqstRsn(String rqstRsn) {
        this.rqstRsn = rqstRsn;
    }

    
    @Column(name="APPR_TYP_CD", length=5)
    public String getApprTypCd() {
        return this.apprTypCd;
    }
    
    public void setApprTypCd(String apprTypCd) {
        this.apprTypCd = apprTypCd;
    }

    
    @Column(name="RQST_EXPLN", length=4000)
    public String getRqstExpln() {
        return this.rqstExpln;
    }
    
    public void setRqstExpln(String rqstExpln) {
        this.rqstExpln = rqstExpln;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="DOCKET_ID", precision=22, scale=0)
    public BigInteger getDocketId() {
        return this.docketId;
    }
    
    public void setDocketId(BigInteger docketId) {
        this.docketId = docketId;
    }

    
    @Column(name="OTHER_WITNESS_TXT", length=500)
    public String getOtherWitnessTxt() {
        return this.otherWitnessTxt;
    }
    
    public void setOtherWitnessTxt(String otherWitnessTxt) {
        this.otherWitnessTxt = otherWitnessTxt;
    }

    
    @Column(name="ORDER_SIGNED_SW", length=1)
    public Character getOrderSignedSw() {
        return this.orderSignedSw;
    }
    
    public void setOrderSignedSw(Character orderSignedSw) {
        this.orderSignedSw = orderSignedSw;
    }

    
    @Column(name="ORDER_TYP_CD", length=3)
    public String getOrderTypCd() {
        return this.orderTypCd;
    }
    
    public void setOrderTypCd(String orderTypCd) {
        this.orderTypCd = orderTypCd;
    }

    
    @Column(name="ORDER_SIGNED_DT", length=7)
    public LocalDate getOrderSignedDt() {
        return this.orderSignedDt;
    }
    
    public void setOrderSignedDt(LocalDate orderSignedDt) {
        this.orderSignedDt = orderSignedDt;
    }

    
    @Column(name="CONT_PETITION_DT", length=7)
    public LocalDate getContPetitionDt() {
        return this.contPetitionDt;
    }
    
    public void setContPetitionDt(LocalDate contPetitionDt) {
        this.contPetitionDt = contPetitionDt;
    }

    
    @Column(name="ORDER_SUBMIT_REVIEW_DT", length=7)
    public LocalDate getOrderSubmitReviewDt() {
        return this.orderSubmitReviewDt;
    }
    
    public void setOrderSubmitReviewDt(LocalDate orderSubmitReviewDt) {
        this.orderSubmitReviewDt = orderSubmitReviewDt;
    }

    
    @Column(name="ORDER_RETURN_DT", length=7)
    public LocalDate getOrderReturnDt() {
        return this.orderReturnDt;
    }
    
    public void setOrderReturnDt(LocalDate orderReturnDt) {
        this.orderReturnDt = orderReturnDt;
    }

    
    @Column(name="CONT_REQUEST_BY_CD", length=3)
    public String getContRequestByCd() {
        return this.contRequestByCd;
    }
    
    public void setContRequestByCd(String contRequestByCd) {
        this.contRequestByCd = contRequestByCd;
    }

    
    @Column(name="CONTINUANCE_RQST_CD", length=3)
    public String getContinuanceRqstCd() {
        return this.continuanceRqstCd;
    }
    
    public void setContinuanceRqstCd(String continuanceRqstCd) {
        this.continuanceRqstCd = continuanceRqstCd;
    }

    
    @Column(name="SEND_NOH_ATTACH_SW", length=1)
    public Character getSendNohAttachSw() {
        return this.sendNohAttachSw;
    }
    
    public void setSendNohAttachSw(Character sendNohAttachSw) {
        this.sendNohAttachSw = sendNohAttachSw;
    }

    
    @Column(name="REASON_HLD_OPN_CD", length=3)
    public String getReasonHldOpnCd() {
        return this.reasonHldOpnCd;
    }
    
    public void setReasonHldOpnCd(String reasonHldOpnCd) {
        this.reasonHldOpnCd = reasonHldOpnCd;
    }

    
    @Column(name="INFO_RECEIVED_DT", length=7)
    public LocalDate getInfoReceivedDt() {
        return this.infoReceivedDt;
    }
    
    public void setInfoReceivedDt(LocalDate infoReceivedDt) {
        this.infoReceivedDt = infoReceivedDt;
    }

    
    @Column(name="RECORD_HELD_OPEN_DT", length=7)
    public LocalDate getRecordHeldOpenDt() {
        return this.recordHeldOpenDt;
    }
    
    public void setRecordHeldOpenDt(LocalDate recordHeldOpenDt) {
        this.recordHeldOpenDt = recordHeldOpenDt;
    }

    
    @Column(name="PET_RQST_TMLY_SW", length=1)
    public Character getPetRqstTmlySw() {
        return this.petRqstTmlySw;
    }
    
    public void setPetRqstTmlySw(Character petRqstTmlySw) {
        this.petRqstTmlySw = petRqstTmlySw;
    }

    
    @Column(name="PETITION_DUE_DT", length=7)
    public LocalDate getPetitionDueDt() {
        return this.petitionDueDt;
    }
    
    public void setPetitionDueDt(LocalDate petitionDueDt) {
        this.petitionDueDt = petitionDueDt;
    }

    
    @Column(name="UPDATE_DT", length=7)
    public LocalDate getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(LocalDate updateDt) {
        this.updateDt = updateDt;
    }

    
    @Column(name="UPDATE_USER_ID", length=20)
    public String getUpdateUserId() {
        return this.updateUserId;
    }
    
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    
    @Column(name="DECISION_DT", length=11)
    public LocalDateTime getDecisionDt() {
        return this.decisionDt;
    }
    
    public void setDecisionDt(LocalDateTime decisionDt) {
        this.decisionDt = decisionDt;
    }




}


