package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final

import lombok.Data;

import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmAplGrpId generated by hbm2java
 */
@Data
public class AmAplGrpId  implements java.io.Serializable {

     private BigInteger aplGroupNum;
     private BigInteger aplNum;

  /*  public AmAplGrpId() {
    }

    public AmAplGrpId(String aplGroupNum, BigInteger aplNum) {
       this.aplGroupNum = aplGroupNum;
       this.aplNum = aplNum;
    }
   


    @Column(name="APL_GROUP_NUM", nullable=false, length=11)
    public String getAplGroupNum() {
        return this.aplGroupNum;
    }
    
    public void setAplGroupNum(String aplGroupNum) {
        this.aplGroupNum = aplGroupNum;
    }


    @Column(name="APL_NUM", nullable=false, precision=38, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmAplGrpId) ) return false;
		 AmAplGrpId castOther = ( AmAplGrpId ) other; 
         
		 return ( (this.getAplGroupNum()==castOther.getAplGroupNum()) || ( this.getAplGroupNum()!=null && castOther.getAplGroupNum()!=null && this.getAplGroupNum().equals(castOther.getAplGroupNum()) ) )
 && ( (this.getAplNum()==castOther.getAplNum()) || ( this.getAplNum()!=null && castOther.getAplNum()!=null && this.getAplNum().equals(castOther.getAplNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAplGroupNum() == null ? 0 : this.getAplGroupNum().hashCode() );
         result = 37 * result + ( getAplNum() == null ? 0 : this.getAplNum().hashCode() );
         return result;
   } */


}


