package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final

import com.deloitte.nextgen.framework.persistence.annotations.EntityType;
import com.deloitte.nextgen.framework.persistence.entity.type.zero.TypeZeroBaseEntity;
import com.deloitte.nextgen.framework.persistence.enums.TypeEnum;
import com.deloitte.nextgen.ha.common.repository.AmAppealInfoRepository;
import lombok.*;


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmAppealInfo generated by hbm2java
 */
@Entity
@Table(name="AM_APPEAL_INFO") //  ,schema="IE_APP_ONLINE"
@EntityType(type= TypeEnum.ZERO, customRepository = AmAppealInfoRepository.class)
@EqualsAndHashCode(callSuper=false)
@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AmAppealInfo extends TypeZeroBaseEntity<BigInteger>  {

     @Id
     @Column(name="APL_NUM")
     private BigInteger aplNum;
     @Column(name="GROSS_DAYS")
     private BigInteger grossDays;
     @Column(name="NET_DAYS")
     private BigInteger netDays;

     @Column(name="DELAY_DAYS")
     private BigInteger delayDays;
     @Column(name="AGENCY_CD")
     private String agencyCd;
     @Column(name="CONTINUANCES")
     private BigInteger continuances;
     @Column(name="DAYS_LEFT_OPEN")
     private BigInteger daysLeftOpen;
     @Column(name="FAD_DUE_DAYS")
     private BigInteger fadDueDays;
     @Column(name="FAD_DUE_DT")
     private LocalDate fadDueDt;
     @Column(name="FAD_ISSUED")
     private LocalDate fadIssued;
     @Column(name="FAD_IMPLEMENTED")
     private LocalDate fadImplemented;
     @Column(name="HO_FAD_DUE_DT")
     private LocalDate hoFadDueDt;
     @Column(name="LAST_HEARD_DT")
     private LocalDate lastHeardDt;
     @Column(name="LAST_CONTINUED_DT")
     private LocalDate lastContinuedDt;
     @Column(name="FIRST_SCHEDULED_DT")
     private LocalDate firstScheduledDt;
     @Column(name="LAST_SCHEDULED_DT")
     private java.sql.Timestamp lastScheduledDt;
     @Column(name="LAST_STATUS")
     private String lastStatus;
     @Column(name="LAST_STATUS_EFF_DT")
     private java.sql.Timestamp lastStatusEffDt;
     @Column(name="FIRST_STATUS_EFF_DT")
     private LocalDate firstStatusEffDt;
     @Column(name="RECORD_DAYS_NUM")
     private Integer recordDaysNum;
     @Column(name="RESOLVED_DT")
     private LocalDate resolvedDt;
     @Column(name="CASE_AUTHREP_INCLUDED")
     private Character caseAuthrepIncluded;


     /*@Column(name="ARCHIVE_DT")
     private java.sql.Timestamp archiveDt;*/
     /*
    @Column(name="CREATE_USER_ID")
     private String createUserId;
    @Column(name="UNIQUE_TRANS_ID")
     private BigInteger uniqueTransId;
  */
    /* @Column(name="CREATE_DT")
     private java.sql.Timestamp createDt;
     @Column(name="UPDATE_DT")
     private LocalDate updateDt;
     @Column(name="UPDATE_USER_ID")
     private String updateUserId;*/



    /*public AmAppealInfo() {
    }


    public AmAppealInfo(BigInteger aplNum, LocalDate createDt) {
        this.aplNum = aplNum;
        this.createDt = createDt;
    }
    public AmAppealInfo(BigInteger aplNum, BigInteger grossDays, BigInteger netDays, BigInteger delayDays, String agencyCd, BigInteger continuances, BigInteger daysLeftOpen, BigInteger fadDueDays, LocalDate fadDueDt, LocalDate fadIssued, LocalDate fadImplemented, LocalDate hoFadDueDt, LocalDate lastHeardDt, LocalDate lastContinuedDt, LocalDate firstScheduledDt, LocalDate lastScheduledDt, String lastStatus, LocalDate lastStatusEffDt, LocalDate createDt, LocalDate firstStatusEffDt, Integer recordDaysNum, LocalDate resolvedDt) {
       this.aplNum = aplNum;
       this.grossDays = grossDays;
       this.netDays = netDays;
       this.delayDays = delayDays;
       this.agencyCd = agencyCd;
       this.continuances = continuances;
       this.daysLeftOpen = daysLeftOpen;
       this.fadDueDays = fadDueDays;
       this.fadDueDt = fadDueDt;
       this.fadIssued = fadIssued;
       this.fadImplemented = fadImplemented;
       this.hoFadDueDt = hoFadDueDt;
       this.lastHeardDt = lastHeardDt;
       this.lastContinuedDt = lastContinuedDt;
       this.firstScheduledDt = firstScheduledDt;
       this.lastScheduledDt = lastScheduledDt;
       this.lastStatus = lastStatus;
       this.lastStatusEffDt = lastStatusEffDt;
       this.createDt = createDt;
       this.firstStatusEffDt = firstStatusEffDt;
       this.recordDaysNum = recordDaysNum;
       this.resolvedDt = resolvedDt;
    }

     @Id


    @Column(name="APL_NUM", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }

    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }


    @Column(name="GROSS_DAYS", precision=22, scale=0)
    public BigInteger getGrossDays() {
        return this.grossDays;
    }

    public void setGrossDays(BigInteger grossDays) {
        this.grossDays = grossDays;
    }


    @Column(name="NET_DAYS", precision=22, scale=0)
    public BigInteger getNetDays() {
        return this.netDays;
    }

    public void setNetDays(BigInteger netDays) {
        this.netDays = netDays;
    }


    @Column(name="DELAY_DAYS", precision=22, scale=0)
    public BigInteger getDelayDays() {
        return this.delayDays;
    }

    public void setDelayDays(BigInteger delayDays) {
        this.delayDays = delayDays;
    }


    @Column(name="AGENCY_CD", length=4)
    public String getAgencyCd() {
        return this.agencyCd;
    }

    public void setAgencyCd(String agencyCd) {
        this.agencyCd = agencyCd;
    }


    @Column(name="CONTINUANCES", precision=22, scale=0)
    public BigInteger getContinuances() {
        return this.continuances;
    }

    public void setContinuances(BigInteger continuances) {
        this.continuances = continuances;
    }


    @Column(name="DAYS_LEFT_OPEN", precision=22, scale=0)
    public BigInteger getDaysLeftOpen() {
        return this.daysLeftOpen;
    }

    public void setDaysLeftOpen(BigInteger daysLeftOpen) {
        this.daysLeftOpen = daysLeftOpen;
    }


    @Column(name="FAD_DUE_DAYS", precision=22, scale=0)
    public BigInteger getFadDueDays() {
        return this.fadDueDays;
    }

    public void setFadDueDays(BigInteger fadDueDays) {
        this.fadDueDays = fadDueDays;
    }


    @Column(name="FAD_DUE_DT", length=7)
    public LocalDate getFadDueDt() {
        return this.fadDueDt;
    }

    public void setFadDueDt(LocalDate fadDueDt) {
        this.fadDueDt = fadDueDt;
    }


    @Column(name="FAD_ISSUED", length=7)
    public LocalDate getFadIssued() {
        return this.fadIssued;
    }

    public void setFadIssued(LocalDate fadIssued) {
        this.fadIssued = fadIssued;
    }


    @Column(name="FAD_IMPLEMENTED", length=7)
    public LocalDate getFadImplemented() {
        return this.fadImplemented;
    }

    public void setFadImplemented(LocalDate fadImplemented) {
        this.fadImplemented = fadImplemented;
    }


    @Column(name="HO_FAD_DUE_DT", length=7)
    public LocalDate getHoFadDueDt() {
        return this.hoFadDueDt;
    }

    public void setHoFadDueDt(LocalDate hoFadDueDt) {
        this.hoFadDueDt = hoFadDueDt;
    }


    @Column(name="LAST_HEARD_DT", length=7)
    public LocalDate getLastHeardDt() {
        return this.lastHeardDt;
    }

    public void setLastHeardDt(LocalDate lastHeardDt) {
        this.lastHeardDt = lastHeardDt;
    }


    @Column(name="LAST_CONTINUED_DT", length=7)
    public LocalDate getLastContinuedDt() {
        return this.lastContinuedDt;
    }

    public void setLastContinuedDt(LocalDate lastContinuedDt) {
        this.lastContinuedDt = lastContinuedDt;
    }


    @Column(name="FIRST_SCHEDULED_DT", length=7)
    public LocalDate getFirstScheduledDt() {
        return this.firstScheduledDt;
    }

    public void setFirstScheduledDt(LocalDate firstScheduledDt) {
        this.firstScheduledDt = firstScheduledDt;
    }


    @Column(name="LAST_SCHEDULED_DT", length=7)
    public LocalDate getLastScheduledDt() {
        return this.lastScheduledDt;
    }

    public void setLastScheduledDt(LocalDate lastScheduledDt) {
        this.lastScheduledDt = lastScheduledDt;
    }


    @Column(name="LAST_STATUS", length=5)
    public String getLastStatus() {
        return this.lastStatus;
    }

    public void setLastStatus(String lastStatus) {
        this.lastStatus = lastStatus;
    }


    @Column(name="LAST_STATUS_EFF_DT", length=7)
    public LocalDate getLastStatusEffDt() {
        return this.lastStatusEffDt;
    }

    public void setLastStatusEffDt(LocalDate lastStatusEffDt) {
        this.lastStatusEffDt = lastStatusEffDt;
    }


    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }

    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }


    @Column(name="FIRST_STATUS_EFF_DT", length=7)
    public LocalDate getFirstStatusEffDt() {
        return this.firstStatusEffDt;
    }

    public void setFirstStatusEffDt(LocalDate firstStatusEffDt) {
        this.firstStatusEffDt = firstStatusEffDt;
    }


    @Column(name="RECORD_DAYS_NUM", precision=5, scale=0)
    public Integer getRecordDaysNum() {
        return this.recordDaysNum;
    }

    public void setRecordDaysNum(Integer recordDaysNum) {
        this.recordDaysNum = recordDaysNum;
    }


    @Column(name="RESOLVED_DT", length=7)
    public LocalDate getResolvedDt() {
        return this.resolvedDt;
    }

    public void setResolvedDt(LocalDate resolvedDt) {
        this.resolvedDt = resolvedDt;
    }
*/



}
