package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmAppealReferencesAId generated by hbm2java
 */
@Embeddable
public class AmAppealReferencesAId  implements java.io.Serializable {


     private BigInteger amAppealReferencesSeqNum;
     private BigInteger historySeq;

    public AmAppealReferencesAId() {
    }

    public AmAppealReferencesAId(BigInteger amAppealReferencesSeqNum, BigInteger historySeq) {
       this.amAppealReferencesSeqNum = amAppealReferencesSeqNum;
       this.historySeq = historySeq;
    }
   


    @Column(name="AM_APPEAL_REFERENCES_SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAmAppealReferencesSeqNum() {
        return this.amAppealReferencesSeqNum;
    }
    
    public void setAmAppealReferencesSeqNum(BigInteger amAppealReferencesSeqNum) {
        this.amAppealReferencesSeqNum = amAppealReferencesSeqNum;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmAppealReferencesAId) ) return false;
		 AmAppealReferencesAId castOther = ( AmAppealReferencesAId ) other; 
         
		 return ( (this.getAmAppealReferencesSeqNum()==castOther.getAmAppealReferencesSeqNum()) || ( this.getAmAppealReferencesSeqNum()!=null && castOther.getAmAppealReferencesSeqNum()!=null && this.getAmAppealReferencesSeqNum().equals(castOther.getAmAppealReferencesSeqNum()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAmAppealReferencesSeqNum() == null ? 0 : this.getAmAppealReferencesSeqNum().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


