package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmAppealReferences generated by hbm2java
 */
@Entity
@Table(name="AM_APPEAL_REFERENCES"
    ,schema="IE_APP_ONLINE"
)
public class AmAppealReferences  implements java.io.Serializable {


     private BigInteger amAppealReferencesSeqNum;
     private BigInteger aplNum;
     private BigInteger refAplNum;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;

    public AmAppealReferences() {
    }

    public AmAppealReferences(BigInteger amAppealReferencesSeqNum, BigInteger aplNum, BigInteger refAplNum, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
       this.amAppealReferencesSeqNum = amAppealReferencesSeqNum;
       this.aplNum = aplNum;
       this.refAplNum = refAplNum;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
    }
   
     @Id 

    
    @Column(name="AM_APPEAL_REFERENCES_SEQ_NUM", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getAmAppealReferencesSeqNum() {
        return this.amAppealReferencesSeqNum;
    }
    
    public void setAmAppealReferencesSeqNum(BigInteger amAppealReferencesSeqNum) {
        this.amAppealReferencesSeqNum = amAppealReferencesSeqNum;
    }

    
    @Column(name="APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }

    
    @Column(name="REF_APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getRefAplNum() {
        return this.refAplNum;
    }
    
    public void setRefAplNum(BigInteger refAplNum) {
        this.refAplNum = refAplNum;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }




}


