package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmAppealPenaltiesId generated by hbm2java
 */
@Embeddable
public class AmAppealPenaltiesId  implements java.io.Serializable {


     private BigInteger amAppealPenaltiesSeqNum;
     private BigInteger aplNum;

    public AmAppealPenaltiesId() {
    }

    public AmAppealPenaltiesId(BigInteger amAppealPenaltiesSeqNum, BigInteger aplNum) {
       this.amAppealPenaltiesSeqNum = amAppealPenaltiesSeqNum;
       this.aplNum = aplNum;
    }
   


    @Column(name="AM_APPEAL_PENALTIES_SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAmAppealPenaltiesSeqNum() {
        return this.amAppealPenaltiesSeqNum;
    }
    
    public void setAmAppealPenaltiesSeqNum(BigInteger amAppealPenaltiesSeqNum) {
        this.amAppealPenaltiesSeqNum = amAppealPenaltiesSeqNum;
    }


    @Column(name="APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmAppealPenaltiesId) ) return false;
		 AmAppealPenaltiesId castOther = ( AmAppealPenaltiesId ) other; 
         
		 return ( (this.getAmAppealPenaltiesSeqNum()==castOther.getAmAppealPenaltiesSeqNum()) || ( this.getAmAppealPenaltiesSeqNum()!=null && castOther.getAmAppealPenaltiesSeqNum()!=null && this.getAmAppealPenaltiesSeqNum().equals(castOther.getAmAppealPenaltiesSeqNum()) ) )
 && ( (this.getAplNum()==castOther.getAplNum()) || ( this.getAplNum()!=null && castOther.getAplNum()!=null && this.getAplNum().equals(castOther.getAplNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAmAppealPenaltiesSeqNum() == null ? 0 : this.getAmAppealPenaltiesSeqNum().hashCode() );
         result = 37 * result + ( getAplNum() == null ? 0 : this.getAplNum().hashCode() );
         return result;
   }   


}


