package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import lombok.Data;
import lombok.EqualsAndHashCode;

import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmAppealNotesAmendId generated by hbm2java
 */
@Data
@EqualsAndHashCode
public class AmAppealNotesAmendId  implements java.io.Serializable {


     private BigInteger aplNum;
     private BigInteger aplNotesSeqNum;
     private BigInteger aplNotesAmendSeqNum;

   /* public AmAppealNotesAmendId() {
    }

    public AmAppealNotesAmendId(BigInteger aplNum, BigInteger aplNotesSeqNum, BigInteger aplNotesAmendSeqNum) {
       this.aplNum = aplNum;
       this.aplNotesSeqNum = aplNotesSeqNum;
       this.aplNotesAmendSeqNum = aplNotesAmendSeqNum;
    }
   


    @Column(name="APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }


    @Column(name="APL_NOTES_SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNotesSeqNum() {
        return this.aplNotesSeqNum;
    }
    
    public void setAplNotesSeqNum(BigInteger aplNotesSeqNum) {
        this.aplNotesSeqNum = aplNotesSeqNum;
    }


    @Column(name="APL_NOTES_AMEND_SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNotesAmendSeqNum() {
        return this.aplNotesAmendSeqNum;
    }
    
    public void setAplNotesAmendSeqNum(BigInteger aplNotesAmendSeqNum) {
        this.aplNotesAmendSeqNum = aplNotesAmendSeqNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmAppealNotesAmendId) ) return false;
		 AmAppealNotesAmendId castOther = ( AmAppealNotesAmendId ) other; 
         
		 return ( (this.getAplNum()==castOther.getAplNum()) || ( this.getAplNum()!=null && castOther.getAplNum()!=null && this.getAplNum().equals(castOther.getAplNum()) ) )
 && ( (this.getAplNotesSeqNum()==castOther.getAplNotesSeqNum()) || ( this.getAplNotesSeqNum()!=null && castOther.getAplNotesSeqNum()!=null && this.getAplNotesSeqNum().equals(castOther.getAplNotesSeqNum()) ) )
 && ( (this.getAplNotesAmendSeqNum()==castOther.getAplNotesAmendSeqNum()) || ( this.getAplNotesAmendSeqNum()!=null && castOther.getAplNotesAmendSeqNum()!=null && this.getAplNotesAmendSeqNum().equals(castOther.getAplNotesAmendSeqNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAplNum() == null ? 0 : this.getAplNum().hashCode() );
         result = 37 * result + ( getAplNotesSeqNum() == null ? 0 : this.getAplNotesSeqNum().hashCode() );
         result = 37 * result + ( getAplNotesAmendSeqNum() == null ? 0 : this.getAplNotesAmendSeqNum().hashCode() );
         return result;
   }   
*/

}


