package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmCduApprRejDtlAId generated by hbm2java
 */
@Embeddable
public class AmCduApprRejDtlAId  implements java.io.Serializable {


     private BigInteger cduSeqNum;
     private BigInteger historySeq;

    public AmCduApprRejDtlAId() {
    }

    public AmCduApprRejDtlAId(BigInteger cduSeqNum, BigInteger historySeq) {
       this.cduSeqNum = cduSeqNum;
       this.historySeq = historySeq;
    }
   


    @Column(name="CDU_SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getCduSeqNum() {
        return this.cduSeqNum;
    }
    
    public void setCduSeqNum(BigInteger cduSeqNum) {
        this.cduSeqNum = cduSeqNum;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmCduApprRejDtlAId) ) return false;
		 AmCduApprRejDtlAId castOther = ( AmCduApprRejDtlAId ) other; 
         
		 return ( (this.getCduSeqNum()==castOther.getCduSeqNum()) || ( this.getCduSeqNum()!=null && castOther.getCduSeqNum()!=null && this.getCduSeqNum().equals(castOther.getCduSeqNum()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCduSeqNum() == null ? 0 : this.getCduSeqNum().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


