package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmCommPrefAId generated by hbm2java
 */
@Embeddable
public class AmCommPrefAId  implements java.io.Serializable {


     private BigInteger indvId;
     private BigInteger historySeq;

    public AmCommPrefAId() {
    }

    public AmCommPrefAId(BigInteger indvId, BigInteger historySeq) {
       this.indvId = indvId;
       this.historySeq = historySeq;
    }
   


    @Column(name="INDV_ID", nullable=false, precision=22, scale=0)
    public BigInteger getIndvId() {
        return this.indvId;
    }
    
    public void setIndvId(BigInteger indvId) {
        this.indvId = indvId;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmCommPrefAId) ) return false;
		 AmCommPrefAId castOther = ( AmCommPrefAId ) other; 
         
		 return ( (this.getIndvId()==castOther.getIndvId()) || ( this.getIndvId()!=null && castOther.getIndvId()!=null && this.getIndvId().equals(castOther.getIndvId()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIndvId() == null ? 0 : this.getIndvId().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


