package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmDigRecId generated by hbm2java
 */
@Embeddable
public class AmDigRecId  implements java.io.Serializable {


     private BigInteger aplNum;
     private String fileName;
     private BigInteger seqNum;

    public AmDigRecId() {
    }

    public AmDigRecId(BigInteger aplNum, String fileName, BigInteger seqNum) {
       this.aplNum = aplNum;
       this.fileName = fileName;
       this.seqNum = seqNum;
    }
   


    @Column(name="APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }


    @Column(name="FILE_NAME", nullable=false, length=300)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }


    @Column(name="SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getSeqNum() {
        return this.seqNum;
    }
    
    public void setSeqNum(BigInteger seqNum) {
        this.seqNum = seqNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmDigRecId) ) return false;
		 AmDigRecId castOther = ( AmDigRecId ) other; 
         
		 return ( (this.getAplNum()==castOther.getAplNum()) || ( this.getAplNum()!=null && castOther.getAplNum()!=null && this.getAplNum().equals(castOther.getAplNum()) ) )
 && ( (this.getFileName()==castOther.getFileName()) || ( this.getFileName()!=null && castOther.getFileName()!=null && this.getFileName().equals(castOther.getFileName()) ) )
 && ( (this.getSeqNum()==castOther.getSeqNum()) || ( this.getSeqNum()!=null && castOther.getSeqNum()!=null && this.getSeqNum().equals(castOther.getSeqNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAplNum() == null ? 0 : this.getAplNum().hashCode() );
         result = 37 * result + ( getFileName() == null ? 0 : this.getFileName().hashCode() );
         result = 37 * result + ( getSeqNum() == null ? 0 : this.getSeqNum().hashCode() );
         return result;
   }   


}


