package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.sql.Clob;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmDisqualificationA generated by hbm2java
 */
@Entity
@Table(name="AM_DISQUALIFICATION_A"
    ,schema="IE_APP_ONLINE"
)
public class AmDisqualificationA  implements java.io.Serializable {


     private AmDisqualificationAId id;
     private LocalDate ovrpayStartDt;
     private LocalDate ovrpayEndDt;
     private LocalDate scndOvrpayStartDt;
     private LocalDate scndOvrpayEndDt;
     private String ineligibilityCd;
     private Clob chgSummary;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String auditUserId;
     private LocalDate auditDt;

    public AmDisqualificationA() {
    }

	
    public AmDisqualificationA(AmDisqualificationAId id, String ineligibilityCd, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
        this.id = id;
        this.ineligibilityCd = ineligibilityCd;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
        this.auditUserId = auditUserId;
        this.auditDt = auditDt;
    }
    public AmDisqualificationA(AmDisqualificationAId id, LocalDate ovrpayStartDt, LocalDate ovrpayEndDt, LocalDate scndOvrpayStartDt, LocalDate scndOvrpayEndDt, String ineligibilityCd, Clob chgSummary, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
       this.id = id;
       this.ovrpayStartDt = ovrpayStartDt;
       this.ovrpayEndDt = ovrpayEndDt;
       this.scndOvrpayStartDt = scndOvrpayStartDt;
       this.scndOvrpayEndDt = scndOvrpayEndDt;
       this.ineligibilityCd = ineligibilityCd;
       this.chgSummary = chgSummary;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.auditUserId = auditUserId;
       this.auditDt = auditDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="aplNum", column=@Column(name="APL_NUM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="historySeq", column=@Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0) ) } )
    public AmDisqualificationAId getId() {
        return this.id;
    }
    
    public void setId(AmDisqualificationAId id) {
        this.id = id;
    }

    
    @Column(name="OVRPAY_START_DT", length=7)
    public LocalDate getOvrpayStartDt() {
        return this.ovrpayStartDt;
    }
    
    public void setOvrpayStartDt(LocalDate ovrpayStartDt) {
        this.ovrpayStartDt = ovrpayStartDt;
    }

    
    @Column(name="OVRPAY_END_DT", length=7)
    public LocalDate getOvrpayEndDt() {
        return this.ovrpayEndDt;
    }
    
    public void setOvrpayEndDt(LocalDate ovrpayEndDt) {
        this.ovrpayEndDt = ovrpayEndDt;
    }

    
    @Column(name="SCND_OVRPAY_START_DT", length=7)
    public LocalDate getScndOvrpayStartDt() {
        return this.scndOvrpayStartDt;
    }
    
    public void setScndOvrpayStartDt(LocalDate scndOvrpayStartDt) {
        this.scndOvrpayStartDt = scndOvrpayStartDt;
    }

    
    @Column(name="SCND_OVRPAY_END_DT", length=7)
    public LocalDate getScndOvrpayEndDt() {
        return this.scndOvrpayEndDt;
    }
    
    public void setScndOvrpayEndDt(LocalDate scndOvrpayEndDt) {
        this.scndOvrpayEndDt = scndOvrpayEndDt;
    }

    
    @Column(name="INELIGIBILITY_CD", nullable=false, length=2)
    public String getIneligibilityCd() {
        return this.ineligibilityCd;
    }
    
    public void setIneligibilityCd(String ineligibilityCd) {
        this.ineligibilityCd = ineligibilityCd;
    }

    
    @Column(name="CHG_SUMMARY")
    public Clob getChgSummary() {
        return this.chgSummary;
    }
    
    public void setChgSummary(Clob chgSummary) {
        this.chgSummary = chgSummary;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AUDIT_USER_ID", nullable=false, length=20)
    public String getAuditUserId() {
        return this.auditUserId;
    }
    
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    
    @Column(name="AUDIT_DT", nullable=false, length=7)
    public LocalDate getAuditDt() {
        return this.auditDt;
    }
    
    public void setAuditDt(LocalDate auditDt) {
        this.auditDt = auditDt;
    }




}


