package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmDocketAppealsA generated by hbm2java
 */
@Entity
@Table(name="AM_DOCKET_APPEALS_A"
    ,schema="IE_APP_ONLINE"
)
public class AmDocketAppealsA  implements java.io.Serializable {


     private AmDocketAppealsAId id;
     private BigInteger docketId;
     private BigInteger aplNum;
     private String programCd;
     private String appealOutcomeCd;
     private char deleteInd;
     private String deptRepRqstCd;
     private String requestReasonCd;
     private String additionalComments;
     private LocalDate beginTime;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String auditUserId;
     private LocalDate auditDt;
     private BigInteger hearingOrderNum;
     private BigInteger stagAplDrtnNum;
     private Character attorneyReviewSw;
     private String updateUserId;
     private LocalDate updateDt;
     private LocalDate endTime;

    public AmDocketAppealsA() {
    }

	
    public AmDocketAppealsA(AmDocketAppealsAId id, BigInteger docketId, BigInteger aplNum, String programCd, char deleteInd, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
        this.id = id;
        this.docketId = docketId;
        this.aplNum = aplNum;
        this.programCd = programCd;
        this.deleteInd = deleteInd;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
        this.auditUserId = auditUserId;
        this.auditDt = auditDt;
    }
    public AmDocketAppealsA(AmDocketAppealsAId id, BigInteger docketId, BigInteger aplNum, String programCd, String appealOutcomeCd, char deleteInd, String deptRepRqstCd, String requestReasonCd, String additionalComments, LocalDate beginTime, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt, BigInteger hearingOrderNum, BigInteger stagAplDrtnNum, Character attorneyReviewSw, String updateUserId, LocalDate updateDt, LocalDate endTime) {
       this.id = id;
       this.docketId = docketId;
       this.aplNum = aplNum;
       this.programCd = programCd;
       this.appealOutcomeCd = appealOutcomeCd;
       this.deleteInd = deleteInd;
       this.deptRepRqstCd = deptRepRqstCd;
       this.requestReasonCd = requestReasonCd;
       this.additionalComments = additionalComments;
       this.beginTime = beginTime;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.auditUserId = auditUserId;
       this.auditDt = auditDt;
       this.hearingOrderNum = hearingOrderNum;
       this.stagAplDrtnNum = stagAplDrtnNum;
       this.attorneyReviewSw = attorneyReviewSw;
       this.updateUserId = updateUserId;
       this.updateDt = updateDt;
       this.endTime = endTime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="docketSeqNum", column=@Column(name="DOCKET_SEQ_NUM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="historySeq", column=@Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0) ) } )
    public AmDocketAppealsAId getId() {
        return this.id;
    }
    
    public void setId(AmDocketAppealsAId id) {
        this.id = id;
    }

    
    @Column(name="DOCKET_ID", nullable=false, precision=22, scale=0)
    public BigInteger getDocketId() {
        return this.docketId;
    }
    
    public void setDocketId(BigInteger docketId) {
        this.docketId = docketId;
    }

    
    @Column(name="APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }

    
    @Column(name="PROGRAM_CD", nullable=false, length=5)
    public String getProgramCd() {
        return this.programCd;
    }
    
    public void setProgramCd(String programCd) {
        this.programCd = programCd;
    }

    
    @Column(name="APPEAL_OUTCOME_CD", length=5)
    public String getAppealOutcomeCd() {
        return this.appealOutcomeCd;
    }
    
    public void setAppealOutcomeCd(String appealOutcomeCd) {
        this.appealOutcomeCd = appealOutcomeCd;
    }

    
    @Column(name="DELETE_IND", nullable=false, length=1)
    public char getDeleteInd() {
        return this.deleteInd;
    }
    
    public void setDeleteInd(char deleteInd) {
        this.deleteInd = deleteInd;
    }

    
    @Column(name="DEPT_REP_RQST_CD", length=5)
    public String getDeptRepRqstCd() {
        return this.deptRepRqstCd;
    }
    
    public void setDeptRepRqstCd(String deptRepRqstCd) {
        this.deptRepRqstCd = deptRepRqstCd;
    }

    
    @Column(name="REQUEST_REASON_CD", length=5)
    public String getRequestReasonCd() {
        return this.requestReasonCd;
    }
    
    public void setRequestReasonCd(String requestReasonCd) {
        this.requestReasonCd = requestReasonCd;
    }

    
    @Column(name="ADDITIONAL_COMMENTS", length=4000)
    public String getAdditionalComments() {
        return this.additionalComments;
    }
    
    public void setAdditionalComments(String additionalComments) {
        this.additionalComments = additionalComments;
    }

    
    @Column(name="BEGIN_TIME", length=7)
    public LocalDate getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(LocalDate beginTime) {
        this.beginTime = beginTime;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AUDIT_USER_ID", nullable=false, length=20)
    public String getAuditUserId() {
        return this.auditUserId;
    }
    
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    
    @Column(name="AUDIT_DT", nullable=false, length=7)
    public LocalDate getAuditDt() {
        return this.auditDt;
    }
    
    public void setAuditDt(LocalDate auditDt) {
        this.auditDt = auditDt;
    }

    
    @Column(name="HEARING_ORDER_NUM", precision=22, scale=0)
    public BigInteger getHearingOrderNum() {
        return this.hearingOrderNum;
    }
    
    public void setHearingOrderNum(BigInteger hearingOrderNum) {
        this.hearingOrderNum = hearingOrderNum;
    }

    
    @Column(name="STAG_APL_DRTN_NUM", precision=22, scale=0)
    public BigInteger getStagAplDrtnNum() {
        return this.stagAplDrtnNum;
    }
    
    public void setStagAplDrtnNum(BigInteger stagAplDrtnNum) {
        this.stagAplDrtnNum = stagAplDrtnNum;
    }

    
    @Column(name="ATTORNEY_REVIEW_SW", length=1)
    public Character getAttorneyReviewSw() {
        return this.attorneyReviewSw;
    }
    
    public void setAttorneyReviewSw(Character attorneyReviewSw) {
        this.attorneyReviewSw = attorneyReviewSw;
    }

    
    @Column(name="UPDATE_USER_ID", length=20)
    public String getUpdateUserId() {
        return this.updateUserId;
    }
    
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    
    @Column(name="UPDATE_DT", length=7)
    public LocalDate getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(LocalDate updateDt) {
        this.updateDt = updateDt;
    }

    
    @Column(name="END_TIME", length=7)
    public LocalDate getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(LocalDate endTime) {
        this.endTime = endTime;
    }




}


