package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmDocketType generated by hbm2java
 */
@Entity
@Table(name="AM_DOCKET_TYPE"
    ,schema="IE_APP_ONLINE"
)
public class AmDocketType  implements java.io.Serializable {


     private AmDocketTypeId id;
     private LocalDate efectEndDt;
     private BigInteger officeTimeSlotId;
     private String typeCd;
     private BigInteger maxDocketsNum;
     private BigInteger maxAppealsNum;
     private BigInteger minAppealsNum;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private Character deleteInd;
     private BigInteger stagDurationNum;
     private String aplRsnCd;
     private BigInteger attorneyFactorNum;
     private BigInteger interpreterFactorNum;
     private String aplTimeFactCd;

    public AmDocketType() {
    }

	
    public AmDocketType(AmDocketTypeId id, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.id = id;
        this.historySeq = historySeq;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmDocketType(AmDocketTypeId id, LocalDate efectEndDt, BigInteger officeTimeSlotId, String typeCd, BigInteger maxDocketsNum, BigInteger maxAppealsNum, BigInteger minAppealsNum, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, Character deleteInd, BigInteger stagDurationNum, String aplRsnCd, BigInteger attorneyFactorNum, BigInteger interpreterFactorNum, String aplTimeFactCd) {
       this.id = id;
       this.efectEndDt = efectEndDt;
       this.officeTimeSlotId = officeTimeSlotId;
       this.typeCd = typeCd;
       this.maxDocketsNum = maxDocketsNum;
       this.maxAppealsNum = maxAppealsNum;
       this.minAppealsNum = minAppealsNum;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.deleteInd = deleteInd;
       this.stagDurationNum = stagDurationNum;
       this.aplRsnCd = aplRsnCd;
       this.attorneyFactorNum = attorneyFactorNum;
       this.interpreterFactorNum = interpreterFactorNum;
       this.aplTimeFactCd = aplTimeFactCd;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="docketTypeId", column=@Column(name="DOCKET_TYPE_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="efectStartDt", column=@Column(name="EFECT_START_DT", nullable=false, length=7) ) } )
    public AmDocketTypeId getId() {
        return this.id;
    }
    
    public void setId(AmDocketTypeId id) {
        this.id = id;
    }

    
    @Column(name="EFECT_END_DT", length=7)
    public LocalDate getEfectEndDt() {
        return this.efectEndDt;
    }
    
    public void setEfectEndDt(LocalDate efectEndDt) {
        this.efectEndDt = efectEndDt;
    }

    
    @Column(name="OFFICE_TIME_SLOT_ID", precision=22, scale=0)
    public BigInteger getOfficeTimeSlotId() {
        return this.officeTimeSlotId;
    }
    
    public void setOfficeTimeSlotId(BigInteger officeTimeSlotId) {
        this.officeTimeSlotId = officeTimeSlotId;
    }

    
    @Column(name="TYPE_CD", length=4)
    public String getTypeCd() {
        return this.typeCd;
    }
    
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd;
    }

    
    @Column(name="MAX_DOCKETS_NUM", precision=22, scale=0)
    public BigInteger getMaxDocketsNum() {
        return this.maxDocketsNum;
    }
    
    public void setMaxDocketsNum(BigInteger maxDocketsNum) {
        this.maxDocketsNum = maxDocketsNum;
    }

    
    @Column(name="MAX_APPEALS_NUM", precision=22, scale=0)
    public BigInteger getMaxAppealsNum() {
        return this.maxAppealsNum;
    }
    
    public void setMaxAppealsNum(BigInteger maxAppealsNum) {
        this.maxAppealsNum = maxAppealsNum;
    }

    
    @Column(name="MIN_APPEALS_NUM", precision=22, scale=0)
    public BigInteger getMinAppealsNum() {
        return this.minAppealsNum;
    }
    
    public void setMinAppealsNum(BigInteger minAppealsNum) {
        this.minAppealsNum = minAppealsNum;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="DELETE_IND", length=1)
    public Character getDeleteInd() {
        return this.deleteInd;
    }
    
    public void setDeleteInd(Character deleteInd) {
        this.deleteInd = deleteInd;
    }

    
    @Column(name="STAG_DURATION_NUM", precision=22, scale=0)
    public BigInteger getStagDurationNum() {
        return this.stagDurationNum;
    }
    
    public void setStagDurationNum(BigInteger stagDurationNum) {
        this.stagDurationNum = stagDurationNum;
    }

    
    @Column(name="APL_RSN_CD", length=3)
    public String getAplRsnCd() {
        return this.aplRsnCd;
    }
    
    public void setAplRsnCd(String aplRsnCd) {
        this.aplRsnCd = aplRsnCd;
    }

    
    @Column(name="ATTORNEY_FACTOR_NUM", precision=22, scale=0)
    public BigInteger getAttorneyFactorNum() {
        return this.attorneyFactorNum;
    }
    
    public void setAttorneyFactorNum(BigInteger attorneyFactorNum) {
        this.attorneyFactorNum = attorneyFactorNum;
    }

    
    @Column(name="INTERPRETER_FACTOR_NUM", precision=22, scale=0)
    public BigInteger getInterpreterFactorNum() {
        return this.interpreterFactorNum;
    }
    
    public void setInterpreterFactorNum(BigInteger interpreterFactorNum) {
        this.interpreterFactorNum = interpreterFactorNum;
    }

    
    @Column(name="APL_TIME_FACT_CD", length=2)
    public String getAplTimeFactCd() {
        return this.aplTimeFactCd;
    }
    
    public void setAplTimeFactCd(String aplTimeFactCd) {
        this.aplTimeFactCd = aplTimeFactCd;
    }




}


