package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmDocketOutcome generated by hbm2java
 */
@Entity
@Table(name="AM_DOCKET_OUTCOME"
    ,schema="IE_APP_ONLINE"
)
public class AmDocketOutcome  implements java.io.Serializable {


     private BigInteger outcomeSeqNum;
     private String docketStatus;
     private String docketOutcome;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;

    public AmDocketOutcome() {
    }

    public AmDocketOutcome(BigInteger outcomeSeqNum, String docketStatus, String docketOutcome, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
       this.outcomeSeqNum = outcomeSeqNum;
       this.docketStatus = docketStatus;
       this.docketOutcome = docketOutcome;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
    }
   
     @Id 

    
    @Column(name="OUTCOME_SEQ_NUM", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getOutcomeSeqNum() {
        return this.outcomeSeqNum;
    }
    
    public void setOutcomeSeqNum(BigInteger outcomeSeqNum) {
        this.outcomeSeqNum = outcomeSeqNum;
    }

    
    @Column(name="DOCKET_STATUS", nullable=false, length=20)
    public String getDocketStatus() {
        return this.docketStatus;
    }
    
    public void setDocketStatus(String docketStatus) {
        this.docketStatus = docketStatus;
    }

    
    @Column(name="DOCKET_OUTCOME", nullable=false, length=50)
    public String getDocketOutcome() {
        return this.docketOutcome;
    }
    
    public void setDocketOutcome(String docketOutcome) {
        this.docketOutcome = docketOutcome;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }




}


