package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmDrsA generated by hbm2java
 */
@Entity
@Table(name="AM_DRS_A"
    ,schema="IE_APP_ONLINE"
)
public class AmDrsA  implements java.io.Serializable {


     private AmDrsAId id;
     private LocalDate noticeDt;
     private Character informalReqInd;
     private Character grievantInd;
     private Character unclaimedInd;
     private Character notRecvdGrivInd;
     private Character mediationRequestedInd;
     private String mediationStatusCd;
     private LocalDate mediationDt;
     private BigInteger donScore;
     private LocalDate assesmentDt;
     private LocalDate serviceNoticeDt;
     private LocalDate applicationDt;
     private LocalDate denialDt;
     private LocalDate ipeDt;
     private LocalDate serviceDenialDt;
     private LocalDate serRequestedDt;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String auditUserId;
     private LocalDate auditDt;
     private String medOutcomeCd;
     private LocalDate medReqDate;

    public AmDrsA() {
    }

	
    public AmDrsA(AmDrsAId id, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
        this.id = id;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
        this.auditUserId = auditUserId;
        this.auditDt = auditDt;
    }
    public AmDrsA(AmDrsAId id, LocalDate noticeDt, Character informalReqInd, Character grievantInd, Character unclaimedInd, Character notRecvdGrivInd, Character mediationRequestedInd, String mediationStatusCd, LocalDate mediationDt, BigInteger donScore, LocalDate assesmentDt, LocalDate serviceNoticeDt, LocalDate applicationDt, LocalDate denialDt, LocalDate ipeDt, LocalDate serviceDenialDt, LocalDate serRequestedDt, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt, String medOutcomeCd, LocalDate medReqDate) {
       this.id = id;
       this.noticeDt = noticeDt;
       this.informalReqInd = informalReqInd;
       this.grievantInd = grievantInd;
       this.unclaimedInd = unclaimedInd;
       this.notRecvdGrivInd = notRecvdGrivInd;
       this.mediationRequestedInd = mediationRequestedInd;
       this.mediationStatusCd = mediationStatusCd;
       this.mediationDt = mediationDt;
       this.donScore = donScore;
       this.assesmentDt = assesmentDt;
       this.serviceNoticeDt = serviceNoticeDt;
       this.applicationDt = applicationDt;
       this.denialDt = denialDt;
       this.ipeDt = ipeDt;
       this.serviceDenialDt = serviceDenialDt;
       this.serRequestedDt = serRequestedDt;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.auditUserId = auditUserId;
       this.auditDt = auditDt;
       this.medOutcomeCd = medOutcomeCd;
       this.medReqDate = medReqDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="aplNum", column=@Column(name="APL_NUM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="historySeq", column=@Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0) ) } )
    public AmDrsAId getId() {
        return this.id;
    }
    
    public void setId(AmDrsAId id) {
        this.id = id;
    }

    
    @Column(name="NOTICE_DT", length=7)
    public LocalDate getNoticeDt() {
        return this.noticeDt;
    }
    
    public void setNoticeDt(LocalDate noticeDt) {
        this.noticeDt = noticeDt;
    }

    
    @Column(name="INFORMAL_REQ_IND", length=1)
    public Character getInformalReqInd() {
        return this.informalReqInd;
    }
    
    public void setInformalReqInd(Character informalReqInd) {
        this.informalReqInd = informalReqInd;
    }

    
    @Column(name="GRIEVANT_IND", length=1)
    public Character getGrievantInd() {
        return this.grievantInd;
    }
    
    public void setGrievantInd(Character grievantInd) {
        this.grievantInd = grievantInd;
    }

    
    @Column(name="UNCLAIMED_IND", length=1)
    public Character getUnclaimedInd() {
        return this.unclaimedInd;
    }
    
    public void setUnclaimedInd(Character unclaimedInd) {
        this.unclaimedInd = unclaimedInd;
    }

    
    @Column(name="NOT_RECVD_GRIV_IND", length=1)
    public Character getNotRecvdGrivInd() {
        return this.notRecvdGrivInd;
    }
    
    public void setNotRecvdGrivInd(Character notRecvdGrivInd) {
        this.notRecvdGrivInd = notRecvdGrivInd;
    }

    
    @Column(name="MEDIATION_REQUESTED_IND", length=1)
    public Character getMediationRequestedInd() {
        return this.mediationRequestedInd;
    }
    
    public void setMediationRequestedInd(Character mediationRequestedInd) {
        this.mediationRequestedInd = mediationRequestedInd;
    }

    
    @Column(name="MEDIATION_STATUS_CD", length=3)
    public String getMediationStatusCd() {
        return this.mediationStatusCd;
    }
    
    public void setMediationStatusCd(String mediationStatusCd) {
        this.mediationStatusCd = mediationStatusCd;
    }

    
    @Column(name="MEDIATION_DT", length=7)
    public LocalDate getMediationDt() {
        return this.mediationDt;
    }
    
    public void setMediationDt(LocalDate mediationDt) {
        this.mediationDt = mediationDt;
    }

    
    @Column(name="DON_SCORE", precision=22, scale=0)
    public BigInteger getDonScore() {
        return this.donScore;
    }
    
    public void setDonScore(BigInteger donScore) {
        this.donScore = donScore;
    }

    
    @Column(name="ASSESMENT_DT", length=7)
    public LocalDate getAssesmentDt() {
        return this.assesmentDt;
    }
    
    public void setAssesmentDt(LocalDate assesmentDt) {
        this.assesmentDt = assesmentDt;
    }

    
    @Column(name="SERVICE_NOTICE_DT", length=7)
    public LocalDate getServiceNoticeDt() {
        return this.serviceNoticeDt;
    }
    
    public void setServiceNoticeDt(LocalDate serviceNoticeDt) {
        this.serviceNoticeDt = serviceNoticeDt;
    }

    
    @Column(name="APPLICATION_DT", length=7)
    public LocalDate getApplicationDt() {
        return this.applicationDt;
    }
    
    public void setApplicationDt(LocalDate applicationDt) {
        this.applicationDt = applicationDt;
    }

    
    @Column(name="DENIAL_DT", length=7)
    public LocalDate getDenialDt() {
        return this.denialDt;
    }
    
    public void setDenialDt(LocalDate denialDt) {
        this.denialDt = denialDt;
    }

    
    @Column(name="IPE_DT", length=7)
    public LocalDate getIpeDt() {
        return this.ipeDt;
    }
    
    public void setIpeDt(LocalDate ipeDt) {
        this.ipeDt = ipeDt;
    }

    
    @Column(name="SERVICE_DENIAL_DT", length=7)
    public LocalDate getServiceDenialDt() {
        return this.serviceDenialDt;
    }
    
    public void setServiceDenialDt(LocalDate serviceDenialDt) {
        this.serviceDenialDt = serviceDenialDt;
    }

    
    @Column(name="SER_REQUESTED_DT", length=7)
    public LocalDate getSerRequestedDt() {
        return this.serRequestedDt;
    }
    
    public void setSerRequestedDt(LocalDate serRequestedDt) {
        this.serRequestedDt = serRequestedDt;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AUDIT_USER_ID", nullable=false, length=20)
    public String getAuditUserId() {
        return this.auditUserId;
    }
    
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    
    @Column(name="AUDIT_DT", nullable=false, length=7)
    public LocalDate getAuditDt() {
        return this.auditDt;
    }
    
    public void setAuditDt(LocalDate auditDt) {
        this.auditDt = auditDt;
    }

    
    @Column(name="MED_OUTCOME_CD", length=3)
    public String getMedOutcomeCd() {
        return this.medOutcomeCd;
    }
    
    public void setMedOutcomeCd(String medOutcomeCd) {
        this.medOutcomeCd = medOutcomeCd;
    }

    
    @Column(name="MED_REQ_DATE", length=7)
    public LocalDate getMedReqDate() {
        return this.medReqDate;
    }
    
    public void setMedReqDate(LocalDate medReqDate) {
        this.medReqDate = medReqDate;
    }




}


