package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.sql.Blob;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmFad generated by hbm2java
 */
@Entity
@Table(name="AM_FAD"
    ,schema="IE_APP_ONLINE"
)
public class AmFad  implements java.io.Serializable {


     private BigInteger fadSeqNum;
     private String fadTemplateName;
     private String fadDescription;
     private Blob fadUploadDoc;
     private String createUserId;
     private LocalDate createDt;
     private LocalDate updateDt;
     private String updateUserId;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String programCd;
     private String categoryCd;

    public AmFad() {
    }

	
    public AmFad(BigInteger fadSeqNum, LocalDate createDt) {
        this.fadSeqNum = fadSeqNum;
        this.createDt = createDt;
    }
    public AmFad(BigInteger fadSeqNum, String fadTemplateName, String fadDescription, Blob fadUploadDoc, String createUserId, LocalDate createDt, LocalDate updateDt, String updateUserId, BigInteger uniqueTransId, LocalDate archiveDt, String programCd, String categoryCd) {
       this.fadSeqNum = fadSeqNum;
       this.fadTemplateName = fadTemplateName;
       this.fadDescription = fadDescription;
       this.fadUploadDoc = fadUploadDoc;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.updateDt = updateDt;
       this.updateUserId = updateUserId;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.programCd = programCd;
       this.categoryCd = categoryCd;
    }
   
     @Id 

    
    @Column(name="FAD_SEQ_NUM", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getFadSeqNum() {
        return this.fadSeqNum;
    }
    
    public void setFadSeqNum(BigInteger fadSeqNum) {
        this.fadSeqNum = fadSeqNum;
    }

    
    @Column(name="FAD_TEMPLATE_NAME", length=500)
    public String getFadTemplateName() {
        return this.fadTemplateName;
    }
    
    public void setFadTemplateName(String fadTemplateName) {
        this.fadTemplateName = fadTemplateName;
    }

    
    @Column(name="FAD_DESCRIPTION", length=50)
    public String getFadDescription() {
        return this.fadDescription;
    }
    
    public void setFadDescription(String fadDescription) {
        this.fadDescription = fadDescription;
    }

    
    @Column(name="FAD_UPLOAD_DOC")
    public Blob getFadUploadDoc() {
        return this.fadUploadDoc;
    }
    
    public void setFadUploadDoc(Blob fadUploadDoc) {
        this.fadUploadDoc = fadUploadDoc;
    }

    
    @Column(name="CREATE_USER_ID", length=128)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UPDATE_DT", length=7)
    public LocalDate getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(LocalDate updateDt) {
        this.updateDt = updateDt;
    }

    
    @Column(name="UPDATE_USER_ID", length=128)
    public String getUpdateUserId() {
        return this.updateUserId;
    }
    
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    
    @Column(name="UNIQUE_TRANS_ID", precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="PROGRAM_CD", length=4)
    public String getProgramCd() {
        return this.programCd;
    }
    
    public void setProgramCd(String programCd) {
        this.programCd = programCd;
    }

    
    @Column(name="CATEGORY_CD", length=4)
    public String getCategoryCd() {
        return this.categoryCd;
    }
    
    public void setCategoryCd(String categoryCd) {
        this.categoryCd = categoryCd;
    }




}


