package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmHoLog generated by hbm2java
 */
@Entity
@Table(name="AM_HO_LOG"
    ,schema="IE_APP_ONLINE"
)
public class AmHoLog  implements java.io.Serializable {


     private AmHoLogId id;
     private BigInteger hearingOfficerId;
     private LocalDate startDt;
     private String logComments;
     private String createUserId;
     private LocalDate createDt;
     private LocalDate updateDt;
     private String updateUserId;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;

    public AmHoLog() {
    }

	
    public AmHoLog(AmHoLogId id, LocalDate createDt) {
        this.id = id;
        this.createDt = createDt;
    }
    public AmHoLog(AmHoLogId id, BigInteger hearingOfficerId, LocalDate startDt, String logComments, String createUserId, LocalDate createDt, LocalDate updateDt, String updateUserId, BigInteger uniqueTransId, LocalDate archiveDt) {
       this.id = id;
       this.hearingOfficerId = hearingOfficerId;
       this.startDt = startDt;
       this.logComments = logComments;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.updateDt = updateDt;
       this.updateUserId = updateUserId;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="aplNum", column=@Column(name="APL_NUM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="hearingSeqNum", column=@Column(name="HEARING_SEQ_NUM", nullable=false, precision=22, scale=0) ) } )
    public AmHoLogId getId() {
        return this.id;
    }
    
    public void setId(AmHoLogId id) {
        this.id = id;
    }

    
    @Column(name="HEARING_OFFICER_ID", precision=22, scale=0)
    public BigInteger getHearingOfficerId() {
        return this.hearingOfficerId;
    }
    
    public void setHearingOfficerId(BigInteger hearingOfficerId) {
        this.hearingOfficerId = hearingOfficerId;
    }

    
    @Column(name="START_DT", length=7)
    public LocalDate getStartDt() {
        return this.startDt;
    }
    
    public void setStartDt(LocalDate startDt) {
        this.startDt = startDt;
    }

    
    @Column(name="LOG_COMMENTS")
    public String getLogComments() {
        return this.logComments;
    }
    
    public void setLogComments(String logComments) {
        this.logComments = logComments;
    }

    
    @Column(name="CREATE_USER_ID", length=128)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UPDATE_DT", length=7)
    public LocalDate getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(LocalDate updateDt) {
        this.updateDt = updateDt;
    }

    
    @Column(name="UPDATE_USER_ID", length=128)
    public String getUpdateUserId() {
        return this.updateUserId;
    }
    
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    
    @Column(name="UNIQUE_TRANS_ID", precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }




}


