package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmHrngImplDtls generated by hbm2java
 */
@Entity
@Table(name="AM_HRNG_IMPL_DTLS"
    ,schema="IE_APP_ONLINE"
)
public class AmHrngImplDtls  implements java.io.Serializable {


     private BigInteger implSeqNum;
     private BigInteger aplNum;
     private String hrngImplInd;
     private Character asstServAuthInd;
     private Character asstServIncInd;
     private Character monthlyRecInd;
     private String otherInd;
     private LocalDate clientNotDat;
     private String implMethodCd;
     private LocalDate medAsstBackToDt;
     private LocalDate medAsstBackFromDt;
     private LocalDate medAsstAuthDt;
     private LocalDate ongMedAsstFromDt;
     private LocalDate ongMedAsstToDt;
     private LocalDate ongMedAuthDt;
     private String svcItmApproved;
     private String svcItemDenied;
     private LocalDate retrBenfFromDt;
     private LocalDate retrBenfToDt;
     private LocalDate ongBenfBgnDt;
     private LocalDate authorizationDt;
     private String specialIssuance;
     private String clientDelayRsn;
     private String otherPgmNotes;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String actTakenToImp;

    public AmHrngImplDtls() {
    }

	
    public AmHrngImplDtls(BigInteger implSeqNum, BigInteger aplNum, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.implSeqNum = implSeqNum;
        this.aplNum = aplNum;
        this.historySeq = historySeq;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmHrngImplDtls(BigInteger implSeqNum, BigInteger aplNum, String hrngImplInd, Character asstServAuthInd, Character asstServIncInd, Character monthlyRecInd, String otherInd, LocalDate clientNotDat, String implMethodCd, LocalDate medAsstBackToDt, LocalDate medAsstBackFromDt, LocalDate medAsstAuthDt, LocalDate ongMedAsstFromDt, LocalDate ongMedAsstToDt, LocalDate ongMedAuthDt, String svcItmApproved, String svcItemDenied, LocalDate retrBenfFromDt, LocalDate retrBenfToDt, LocalDate ongBenfBgnDt, LocalDate authorizationDt, String specialIssuance, String clientDelayRsn, String otherPgmNotes, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String actTakenToImp) {
       this.implSeqNum = implSeqNum;
       this.aplNum = aplNum;
       this.hrngImplInd = hrngImplInd;
       this.asstServAuthInd = asstServAuthInd;
       this.asstServIncInd = asstServIncInd;
       this.monthlyRecInd = monthlyRecInd;
       this.otherInd = otherInd;
       this.clientNotDat = clientNotDat;
       this.implMethodCd = implMethodCd;
       this.medAsstBackToDt = medAsstBackToDt;
       this.medAsstBackFromDt = medAsstBackFromDt;
       this.medAsstAuthDt = medAsstAuthDt;
       this.ongMedAsstFromDt = ongMedAsstFromDt;
       this.ongMedAsstToDt = ongMedAsstToDt;
       this.ongMedAuthDt = ongMedAuthDt;
       this.svcItmApproved = svcItmApproved;
       this.svcItemDenied = svcItemDenied;
       this.retrBenfFromDt = retrBenfFromDt;
       this.retrBenfToDt = retrBenfToDt;
       this.ongBenfBgnDt = ongBenfBgnDt;
       this.authorizationDt = authorizationDt;
       this.specialIssuance = specialIssuance;
       this.clientDelayRsn = clientDelayRsn;
       this.otherPgmNotes = otherPgmNotes;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.actTakenToImp = actTakenToImp;
    }
   
     @Id 

    
    @Column(name="IMPL_SEQ_NUM", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getImplSeqNum() {
        return this.implSeqNum;
    }
    
    public void setImplSeqNum(BigInteger implSeqNum) {
        this.implSeqNum = implSeqNum;
    }

    
    @Column(name="APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }

    
    @Column(name="HRNG_IMPL_IND", length=35)
    public String getHrngImplInd() {
        return this.hrngImplInd;
    }
    
    public void setHrngImplInd(String hrngImplInd) {
        this.hrngImplInd = hrngImplInd;
    }

    
    @Column(name="ASST_SERV_AUTH_IND", length=1)
    public Character getAsstServAuthInd() {
        return this.asstServAuthInd;
    }
    
    public void setAsstServAuthInd(Character asstServAuthInd) {
        this.asstServAuthInd = asstServAuthInd;
    }

    
    @Column(name="ASST_SERV_INC_IND", length=1)
    public Character getAsstServIncInd() {
        return this.asstServIncInd;
    }
    
    public void setAsstServIncInd(Character asstServIncInd) {
        this.asstServIncInd = asstServIncInd;
    }

    
    @Column(name="MONTHLY_REC_IND", length=1)
    public Character getMonthlyRecInd() {
        return this.monthlyRecInd;
    }
    
    public void setMonthlyRecInd(Character monthlyRecInd) {
        this.monthlyRecInd = monthlyRecInd;
    }

    
    @Column(name="OTHER_IND", length=25)
    public String getOtherInd() {
        return this.otherInd;
    }
    
    public void setOtherInd(String otherInd) {
        this.otherInd = otherInd;
    }

    
    @Column(name="CLIENT_NOT_DAT", length=7)
    public LocalDate getClientNotDat() {
        return this.clientNotDat;
    }
    
    public void setClientNotDat(LocalDate clientNotDat) {
        this.clientNotDat = clientNotDat;
    }

    
    @Column(name="IMPL_METHOD_CD", length=5)
    public String getImplMethodCd() {
        return this.implMethodCd;
    }
    
    public void setImplMethodCd(String implMethodCd) {
        this.implMethodCd = implMethodCd;
    }

    
    @Column(name="MED_ASST_BACK_TO_DT", length=7)
    public LocalDate getMedAsstBackToDt() {
        return this.medAsstBackToDt;
    }
    
    public void setMedAsstBackToDt(LocalDate medAsstBackToDt) {
        this.medAsstBackToDt = medAsstBackToDt;
    }

    
    @Column(name="MED_ASST_BACK_FROM_DT", length=7)
    public LocalDate getMedAsstBackFromDt() {
        return this.medAsstBackFromDt;
    }
    
    public void setMedAsstBackFromDt(LocalDate medAsstBackFromDt) {
        this.medAsstBackFromDt = medAsstBackFromDt;
    }

    
    @Column(name="MED_ASST_AUTH_DT", length=7)
    public LocalDate getMedAsstAuthDt() {
        return this.medAsstAuthDt;
    }
    
    public void setMedAsstAuthDt(LocalDate medAsstAuthDt) {
        this.medAsstAuthDt = medAsstAuthDt;
    }

    
    @Column(name="ONG_MED_ASST_FROM_DT", length=7)
    public LocalDate getOngMedAsstFromDt() {
        return this.ongMedAsstFromDt;
    }
    
    public void setOngMedAsstFromDt(LocalDate ongMedAsstFromDt) {
        this.ongMedAsstFromDt = ongMedAsstFromDt;
    }

    
    @Column(name="ONG_MED_ASST_TO_DT", length=7)
    public LocalDate getOngMedAsstToDt() {
        return this.ongMedAsstToDt;
    }
    
    public void setOngMedAsstToDt(LocalDate ongMedAsstToDt) {
        this.ongMedAsstToDt = ongMedAsstToDt;
    }

    
    @Column(name="ONG_MED_AUTH_DT", length=7)
    public LocalDate getOngMedAuthDt() {
        return this.ongMedAuthDt;
    }
    
    public void setOngMedAuthDt(LocalDate ongMedAuthDt) {
        this.ongMedAuthDt = ongMedAuthDt;
    }

    
    @Column(name="SVC_ITM_APPROVED", length=50)
    public String getSvcItmApproved() {
        return this.svcItmApproved;
    }
    
    public void setSvcItmApproved(String svcItmApproved) {
        this.svcItmApproved = svcItmApproved;
    }

    
    @Column(name="SVC_ITEM_DENIED", length=50)
    public String getSvcItemDenied() {
        return this.svcItemDenied;
    }
    
    public void setSvcItemDenied(String svcItemDenied) {
        this.svcItemDenied = svcItemDenied;
    }

    
    @Column(name="RETR_BENF_FROM_DT", length=7)
    public LocalDate getRetrBenfFromDt() {
        return this.retrBenfFromDt;
    }
    
    public void setRetrBenfFromDt(LocalDate retrBenfFromDt) {
        this.retrBenfFromDt = retrBenfFromDt;
    }

    
    @Column(name="RETR_BENF_TO_DT", length=7)
    public LocalDate getRetrBenfToDt() {
        return this.retrBenfToDt;
    }
    
    public void setRetrBenfToDt(LocalDate retrBenfToDt) {
        this.retrBenfToDt = retrBenfToDt;
    }

    
    @Column(name="ONG_BENF_BGN_DT", length=7)
    public LocalDate getOngBenfBgnDt() {
        return this.ongBenfBgnDt;
    }
    
    public void setOngBenfBgnDt(LocalDate ongBenfBgnDt) {
        this.ongBenfBgnDt = ongBenfBgnDt;
    }

    
    @Column(name="AUTHORIZATION_DT", length=7)
    public LocalDate getAuthorizationDt() {
        return this.authorizationDt;
    }
    
    public void setAuthorizationDt(LocalDate authorizationDt) {
        this.authorizationDt = authorizationDt;
    }

    
    @Column(name="SPECIAL_ISSUANCE", length=50)
    public String getSpecialIssuance() {
        return this.specialIssuance;
    }
    
    public void setSpecialIssuance(String specialIssuance) {
        this.specialIssuance = specialIssuance;
    }

    
    @Column(name="CLIENT_DELAY_RSN", length=100)
    public String getClientDelayRsn() {
        return this.clientDelayRsn;
    }
    
    public void setClientDelayRsn(String clientDelayRsn) {
        this.clientDelayRsn = clientDelayRsn;
    }

    
    @Column(name="OTHER_PGM_NOTES", length=4000)
    public String getOtherPgmNotes() {
        return this.otherPgmNotes;
    }
    
    public void setOtherPgmNotes(String otherPgmNotes) {
        this.otherPgmNotes = otherPgmNotes;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="ACT_TAKEN_TO_IMP", length=20)
    public String getActTakenToImp() {
        return this.actTakenToImp;
    }
    
    public void setActTakenToImp(String actTakenToImp) {
        this.actTakenToImp = actTakenToImp;
    }




}


