package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmHrngImplA generated by hbm2java
 */
@Entity
@Table(name="AM_HRNG_IMPL_A"
    ,schema="IE_APP_ONLINE"
)
public class AmHrngImplA  implements java.io.Serializable {


     private AmHrngImplAId id;
     private Character noActionReqInd;
     private Character benefitsAffectedInd;
     private Character noIssueRegBenefitLevelInd;
     private Character adjMedAssistInd;
     private Character adjFinAssistInd;
     private Character adjSnapBenefitsInd;
     private Character clientDelayedInd;
     private String implementComments;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String auditUserId;
     private LocalDate auditDt;
     private Character allOtherPgmInd;

    public AmHrngImplA() {
    }

	
    public AmHrngImplA(AmHrngImplAId id, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
        this.id = id;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
        this.auditUserId = auditUserId;
        this.auditDt = auditDt;
    }
    public AmHrngImplA(AmHrngImplAId id, Character noActionReqInd, Character benefitsAffectedInd, Character noIssueRegBenefitLevelInd, Character adjMedAssistInd, Character adjFinAssistInd, Character adjSnapBenefitsInd, Character clientDelayedInd, String implementComments, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt, Character allOtherPgmInd) {
       this.id = id;
       this.noActionReqInd = noActionReqInd;
       this.benefitsAffectedInd = benefitsAffectedInd;
       this.noIssueRegBenefitLevelInd = noIssueRegBenefitLevelInd;
       this.adjMedAssistInd = adjMedAssistInd;
       this.adjFinAssistInd = adjFinAssistInd;
       this.adjSnapBenefitsInd = adjSnapBenefitsInd;
       this.clientDelayedInd = clientDelayedInd;
       this.implementComments = implementComments;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.auditUserId = auditUserId;
       this.auditDt = auditDt;
       this.allOtherPgmInd = allOtherPgmInd;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="aplNum", column=@Column(name="APL_NUM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="historySeq", column=@Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0) ) } )
    public AmHrngImplAId getId() {
        return this.id;
    }
    
    public void setId(AmHrngImplAId id) {
        this.id = id;
    }

    
    @Column(name="NO_ACTION_REQ_IND", length=1)
    public Character getNoActionReqInd() {
        return this.noActionReqInd;
    }
    
    public void setNoActionReqInd(Character noActionReqInd) {
        this.noActionReqInd = noActionReqInd;
    }

    
    @Column(name="BENEFITS_AFFECTED_IND", length=1)
    public Character getBenefitsAffectedInd() {
        return this.benefitsAffectedInd;
    }
    
    public void setBenefitsAffectedInd(Character benefitsAffectedInd) {
        this.benefitsAffectedInd = benefitsAffectedInd;
    }

    
    @Column(name="NO_ISSUE_REG_BENEFIT_LEVEL_IND", length=1)
    public Character getNoIssueRegBenefitLevelInd() {
        return this.noIssueRegBenefitLevelInd;
    }
    
    public void setNoIssueRegBenefitLevelInd(Character noIssueRegBenefitLevelInd) {
        this.noIssueRegBenefitLevelInd = noIssueRegBenefitLevelInd;
    }

    
    @Column(name="ADJ_MED_ASSIST_IND", length=1)
    public Character getAdjMedAssistInd() {
        return this.adjMedAssistInd;
    }
    
    public void setAdjMedAssistInd(Character adjMedAssistInd) {
        this.adjMedAssistInd = adjMedAssistInd;
    }

    
    @Column(name="ADJ_FIN_ASSIST_IND", length=1)
    public Character getAdjFinAssistInd() {
        return this.adjFinAssistInd;
    }
    
    public void setAdjFinAssistInd(Character adjFinAssistInd) {
        this.adjFinAssistInd = adjFinAssistInd;
    }

    
    @Column(name="ADJ_SNAP_BENEFITS_IND", length=1)
    public Character getAdjSnapBenefitsInd() {
        return this.adjSnapBenefitsInd;
    }
    
    public void setAdjSnapBenefitsInd(Character adjSnapBenefitsInd) {
        this.adjSnapBenefitsInd = adjSnapBenefitsInd;
    }

    
    @Column(name="CLIENT_DELAYED_IND", length=1)
    public Character getClientDelayedInd() {
        return this.clientDelayedInd;
    }
    
    public void setClientDelayedInd(Character clientDelayedInd) {
        this.clientDelayedInd = clientDelayedInd;
    }

    
    @Column(name="IMPLEMENT_COMMENTS", length=4000)
    public String getImplementComments() {
        return this.implementComments;
    }
    
    public void setImplementComments(String implementComments) {
        this.implementComments = implementComments;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AUDIT_USER_ID", nullable=false, length=20)
    public String getAuditUserId() {
        return this.auditUserId;
    }
    
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    
    @Column(name="AUDIT_DT", nullable=false, length=7)
    public LocalDate getAuditDt() {
        return this.auditDt;
    }
    
    public void setAuditDt(LocalDate auditDt) {
        this.auditDt = auditDt;
    }

    
    @Column(name="ALL_OTHER_PGM_IND", length=1)
    public Character getAllOtherPgmInd() {
        return this.allOtherPgmInd;
    }
    
    public void setAllOtherPgmInd(Character allOtherPgmInd) {
        this.allOtherPgmInd = allOtherPgmInd;
    }




}


