package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmHrngImplDtlsAId generated by hbm2java
 */
@Embeddable
public class AmHrngImplDtlsAId  implements java.io.Serializable {


     private BigInteger implSeqNum;
     private BigInteger historySeq;

    public AmHrngImplDtlsAId() {
    }

    public AmHrngImplDtlsAId(BigInteger implSeqNum, BigInteger historySeq) {
       this.implSeqNum = implSeqNum;
       this.historySeq = historySeq;
    }
   


    @Column(name="IMPL_SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getImplSeqNum() {
        return this.implSeqNum;
    }
    
    public void setImplSeqNum(BigInteger implSeqNum) {
        this.implSeqNum = implSeqNum;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmHrngImplDtlsAId) ) return false;
		 AmHrngImplDtlsAId castOther = ( AmHrngImplDtlsAId ) other; 
         
		 return ( (this.getImplSeqNum()==castOther.getImplSeqNum()) || ( this.getImplSeqNum()!=null && castOther.getImplSeqNum()!=null && this.getImplSeqNum().equals(castOther.getImplSeqNum()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getImplSeqNum() == null ? 0 : this.getImplSeqNum().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


