package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmHrngImplPgmDtlsA generated by hbm2java
 */
@Entity
@Table(name="AM_HRNG_IMPL_PGM_DTLS_A"
    ,schema="IE_APP_ONLINE"
)
public class AmHrngImplPgmDtlsA  implements java.io.Serializable {


     private AmHrngImplPgmDtlsAId id;
     private BigInteger aplNum;
     private String programCd;
     private LocalDate implDate;
     private BigInteger clientDelayDays;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String auditUserId;
     private LocalDate auditDt;

    public AmHrngImplPgmDtlsA() {
    }

	
    public AmHrngImplPgmDtlsA(AmHrngImplPgmDtlsAId id, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
        this.id = id;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
        this.auditUserId = auditUserId;
        this.auditDt = auditDt;
    }
    public AmHrngImplPgmDtlsA(AmHrngImplPgmDtlsAId id, BigInteger aplNum, String programCd, LocalDate implDate, BigInteger clientDelayDays, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
       this.id = id;
       this.aplNum = aplNum;
       this.programCd = programCd;
       this.implDate = implDate;
       this.clientDelayDays = clientDelayDays;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.auditUserId = auditUserId;
       this.auditDt = auditDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="implPgmSeqNum", column=@Column(name="IMPL_PGM_SEQ_NUM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="historySeq", column=@Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0) ) } )
    public AmHrngImplPgmDtlsAId getId() {
        return this.id;
    }
    
    public void setId(AmHrngImplPgmDtlsAId id) {
        this.id = id;
    }

    
    @Column(name="APL_NUM", precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }

    
    @Column(name="PROGRAM_CD", length=5)
    public String getProgramCd() {
        return this.programCd;
    }
    
    public void setProgramCd(String programCd) {
        this.programCd = programCd;
    }

    
    @Column(name="IMPL_DATE", length=7)
    public LocalDate getImplDate() {
        return this.implDate;
    }
    
    public void setImplDate(LocalDate implDate) {
        this.implDate = implDate;
    }

    
    @Column(name="CLIENT_DELAY_DAYS", precision=22, scale=0)
    public BigInteger getClientDelayDays() {
        return this.clientDelayDays;
    }
    
    public void setClientDelayDays(BigInteger clientDelayDays) {
        this.clientDelayDays = clientDelayDays;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AUDIT_USER_ID", nullable=false, length=20)
    public String getAuditUserId() {
        return this.auditUserId;
    }
    
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    
    @Column(name="AUDIT_DT", nullable=false, length=7)
    public LocalDate getAuditDt() {
        return this.auditDt;
    }
    
    public void setAuditDt(LocalDate auditDt) {
        this.auditDt = auditDt;
    }




}


