package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmImplementationReviewAId generated by hbm2java
 */
@Embeddable
public class AmImplementationReviewAId  implements java.io.Serializable {


     private int aplNum;
     private BigInteger impSeqNum;
     private BigInteger historySeq;

    public AmImplementationReviewAId() {
    }

    public AmImplementationReviewAId(int aplNum, BigInteger impSeqNum, BigInteger historySeq) {
       this.aplNum = aplNum;
       this.impSeqNum = impSeqNum;
       this.historySeq = historySeq;
    }
   


    @Column(name="APL_NUM", nullable=false, precision=9, scale=0)
    public int getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(int aplNum) {
        this.aplNum = aplNum;
    }


    @Column(name="IMP_SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getImpSeqNum() {
        return this.impSeqNum;
    }
    
    public void setImpSeqNum(BigInteger impSeqNum) {
        this.impSeqNum = impSeqNum;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmImplementationReviewAId) ) return false;
		 AmImplementationReviewAId castOther = ( AmImplementationReviewAId ) other; 
         
		 return (this.getAplNum()==castOther.getAplNum())
 && ( (this.getImpSeqNum()==castOther.getImpSeqNum()) || ( this.getImpSeqNum()!=null && castOther.getImpSeqNum()!=null && this.getImpSeqNum().equals(castOther.getImpSeqNum()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAplNum();
         result = 37 * result + ( getImpSeqNum() == null ? 0 : this.getImpSeqNum().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


