package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmKidsChStagingA generated by hbm2java
 */
@Entity
@Table(name="AM_KIDS_CH_STAGING_A"
    ,schema="IE_APP_ONLINE"
)
public class AmKidsChStagingA  implements java.io.Serializable {


     private AmKidsChStagingAId id;
     private BigInteger kidsSummaryId;
     private String chLastName;
     private String chFirstName;
     private char chMiddleInitial;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String auditUserId;
     private LocalDate auditDt;
     private String kidsCaseType;
     private String chCaseId;
     private String chErrCd;

    public AmKidsChStagingA() {
    }

	
    public AmKidsChStagingA(AmKidsChStagingAId id, String chLastName, String chFirstName, char chMiddleInitial, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
        this.id = id;
        this.chLastName = chLastName;
        this.chFirstName = chFirstName;
        this.chMiddleInitial = chMiddleInitial;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
        this.auditUserId = auditUserId;
        this.auditDt = auditDt;
    }
    public AmKidsChStagingA(AmKidsChStagingAId id, BigInteger kidsSummaryId, String chLastName, String chFirstName, char chMiddleInitial, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt, String kidsCaseType, String chCaseId, String chErrCd) {
       this.id = id;
       this.kidsSummaryId = kidsSummaryId;
       this.chLastName = chLastName;
       this.chFirstName = chFirstName;
       this.chMiddleInitial = chMiddleInitial;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.auditUserId = auditUserId;
       this.auditDt = auditDt;
       this.kidsCaseType = kidsCaseType;
       this.chCaseId = chCaseId;
       this.chErrCd = chErrCd;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="chId", column=@Column(name="CH_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="historySeq", column=@Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0) ) } )
    public AmKidsChStagingAId getId() {
        return this.id;
    }
    
    public void setId(AmKidsChStagingAId id) {
        this.id = id;
    }

    
    @Column(name="KIDS_SUMMARY_ID", precision=22, scale=0)
    public BigInteger getKidsSummaryId() {
        return this.kidsSummaryId;
    }
    
    public void setKidsSummaryId(BigInteger kidsSummaryId) {
        this.kidsSummaryId = kidsSummaryId;
    }

    
    @Column(name="CH_LAST_NAME", nullable=false, length=17)
    public String getChLastName() {
        return this.chLastName;
    }
    
    public void setChLastName(String chLastName) {
        this.chLastName = chLastName;
    }

    
    @Column(name="CH_FIRST_NAME", nullable=false, length=12)
    public String getChFirstName() {
        return this.chFirstName;
    }
    
    public void setChFirstName(String chFirstName) {
        this.chFirstName = chFirstName;
    }

    
    @Column(name="CH_MIDDLE_INITIAL", nullable=false, length=1)
    public char getChMiddleInitial() {
        return this.chMiddleInitial;
    }
    
    public void setChMiddleInitial(char chMiddleInitial) {
        this.chMiddleInitial = chMiddleInitial;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AUDIT_USER_ID", nullable=false, length=20)
    public String getAuditUserId() {
        return this.auditUserId;
    }
    
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    
    @Column(name="AUDIT_DT", nullable=false, length=7)
    public LocalDate getAuditDt() {
        return this.auditDt;
    }
    
    public void setAuditDt(LocalDate auditDt) {
        this.auditDt = auditDt;
    }

    
    @Column(name="KIDS_CASE_TYPE", length=8)
    public String getKidsCaseType() {
        return this.kidsCaseType;
    }
    
    public void setKidsCaseType(String kidsCaseType) {
        this.kidsCaseType = kidsCaseType;
    }

    
    @Column(name="CH_CASE_ID", length=9)
    public String getChCaseId() {
        return this.chCaseId;
    }
    
    public void setChCaseId(String chCaseId) {
        this.chCaseId = chCaseId;
    }

    
    @Column(name="CH_ERR_CD", length=3)
    public String getChErrCd() {
        return this.chErrCd;
    }
    
    public void setChErrCd(String chErrCd) {
        this.chErrCd = chErrCd;
    }




}


