package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmKidsNcpStagingAId generated by hbm2java
 */
@Embeddable
public class AmKidsNcpStagingAId  implements java.io.Serializable {


     private BigInteger ncpId;
     private BigInteger historySeq;

    public AmKidsNcpStagingAId() {
    }

    public AmKidsNcpStagingAId(BigInteger ncpId, BigInteger historySeq) {
       this.ncpId = ncpId;
       this.historySeq = historySeq;
    }
   


    @Column(name="NCP_ID", nullable=false, precision=22, scale=0)
    public BigInteger getNcpId() {
        return this.ncpId;
    }
    
    public void setNcpId(BigInteger ncpId) {
        this.ncpId = ncpId;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmKidsNcpStagingAId) ) return false;
		 AmKidsNcpStagingAId castOther = ( AmKidsNcpStagingAId ) other; 
         
		 return ( (this.getNcpId()==castOther.getNcpId()) || ( this.getNcpId()!=null && castOther.getNcpId()!=null && this.getNcpId().equals(castOther.getNcpId()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNcpId() == null ? 0 : this.getNcpId().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


