package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmKidsSummaryA generated by hbm2java
 */
@Entity
@Table(name="AM_KIDS_SUMMARY_A"
    ,schema="IE_APP_ONLINE"
)
public class AmKidsSummaryA  implements java.io.Serializable {


     private AmKidsSummaryAId id;
     private String kidsSsn;
     private String kidsCaseNum;
     private BigInteger indvId;
     private LocalDate runDt;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String auditUserId;
     private LocalDate auditDt;

    public AmKidsSummaryA() {
    }

	
    public AmKidsSummaryA(AmKidsSummaryAId id, LocalDate runDt, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
        this.id = id;
        this.runDt = runDt;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
        this.auditUserId = auditUserId;
        this.auditDt = auditDt;
    }
    public AmKidsSummaryA(AmKidsSummaryAId id, String kidsSsn, String kidsCaseNum, BigInteger indvId, LocalDate runDt, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
       this.id = id;
       this.kidsSsn = kidsSsn;
       this.kidsCaseNum = kidsCaseNum;
       this.indvId = indvId;
       this.runDt = runDt;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.auditUserId = auditUserId;
       this.auditDt = auditDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="kidsSummaryId", column=@Column(name="KIDS_SUMMARY_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="historySeq", column=@Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0) ) } )
    public AmKidsSummaryAId getId() {
        return this.id;
    }
    
    public void setId(AmKidsSummaryAId id) {
        this.id = id;
    }

    
    @Column(name="KIDS_SSN", length=11)
    public String getKidsSsn() {
        return this.kidsSsn;
    }
    
    public void setKidsSsn(String kidsSsn) {
        this.kidsSsn = kidsSsn;
    }

    
    @Column(name="KIDS_CASE_NUM", length=20)
    public String getKidsCaseNum() {
        return this.kidsCaseNum;
    }
    
    public void setKidsCaseNum(String kidsCaseNum) {
        this.kidsCaseNum = kidsCaseNum;
    }

    
    @Column(name="INDV_ID", precision=22, scale=0)
    public BigInteger getIndvId() {
        return this.indvId;
    }
    
    public void setIndvId(BigInteger indvId) {
        this.indvId = indvId;
    }

    
    @Column(name="RUN_DT", nullable=false, length=7)
    public LocalDate getRunDt() {
        return this.runDt;
    }
    
    public void setRunDt(LocalDate runDt) {
        this.runDt = runDt;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AUDIT_USER_ID", nullable=false, length=20)
    public String getAuditUserId() {
        return this.auditUserId;
    }
    
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    
    @Column(name="AUDIT_DT", nullable=false, length=7)
    public LocalDate getAuditDt() {
        return this.auditDt;
    }
    
    public void setAuditDt(LocalDate auditDt) {
        this.auditDt = auditDt;
    }




}


