package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmKidsNcpStaging generated by hbm2java
 */
@Entity
@Table(name="AM_KIDS_NCP_STAGING"
    ,schema="IE_APP_ONLINE"
)
public class AmKidsNcpStaging  implements java.io.Serializable {


     private BigInteger ncpId;
     private BigInteger kidsSummaryId;
     private String ncpLastName;
     private String ncpFirstName;
     private Character ncpMiddleInitial;
     private String ncpSsn;
     private String ncpCaseId;
     private String ncpRegionName;
     private String ncpCaseStatusCd;
     private BigInteger ncpHomePhoneNum;
     private BigInteger ncpBusinessPhoneNum;
     private BigInteger ncpBusinessExtnNum;
     private BigInteger ncpCellPhoneNum;
     private Character ncpFamilyViolenceInd;
     private String ncpErrCd;
     private String kidsCaseType;
     private String cltMailAdrLine1;
     private String cltMailAdrLine2;
     private String cltMailAdrCity;
     private String cltMailAdrState;
     private String cltMailAdrZip;
     private String cltResdAdrLine1;
     private String cltResdAdrLine2;
     private String cltResdAdrCity;
     private String cltResdAdrState;
     private String cltResdAdrZip;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;

    public AmKidsNcpStaging() {
    }

	
    public AmKidsNcpStaging(BigInteger ncpId, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.ncpId = ncpId;
        this.historySeq = historySeq;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmKidsNcpStaging(BigInteger ncpId, BigInteger kidsSummaryId, String ncpLastName, String ncpFirstName, Character ncpMiddleInitial, String ncpSsn, String ncpCaseId, String ncpRegionName, String ncpCaseStatusCd, BigInteger ncpHomePhoneNum, BigInteger ncpBusinessPhoneNum, BigInteger ncpBusinessExtnNum, BigInteger ncpCellPhoneNum, Character ncpFamilyViolenceInd, String ncpErrCd, String kidsCaseType, String cltMailAdrLine1, String cltMailAdrLine2, String cltMailAdrCity, String cltMailAdrState, String cltMailAdrZip, String cltResdAdrLine1, String cltResdAdrLine2, String cltResdAdrCity, String cltResdAdrState, String cltResdAdrZip, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
       this.ncpId = ncpId;
       this.kidsSummaryId = kidsSummaryId;
       this.ncpLastName = ncpLastName;
       this.ncpFirstName = ncpFirstName;
       this.ncpMiddleInitial = ncpMiddleInitial;
       this.ncpSsn = ncpSsn;
       this.ncpCaseId = ncpCaseId;
       this.ncpRegionName = ncpRegionName;
       this.ncpCaseStatusCd = ncpCaseStatusCd;
       this.ncpHomePhoneNum = ncpHomePhoneNum;
       this.ncpBusinessPhoneNum = ncpBusinessPhoneNum;
       this.ncpBusinessExtnNum = ncpBusinessExtnNum;
       this.ncpCellPhoneNum = ncpCellPhoneNum;
       this.ncpFamilyViolenceInd = ncpFamilyViolenceInd;
       this.ncpErrCd = ncpErrCd;
       this.kidsCaseType = kidsCaseType;
       this.cltMailAdrLine1 = cltMailAdrLine1;
       this.cltMailAdrLine2 = cltMailAdrLine2;
       this.cltMailAdrCity = cltMailAdrCity;
       this.cltMailAdrState = cltMailAdrState;
       this.cltMailAdrZip = cltMailAdrZip;
       this.cltResdAdrLine1 = cltResdAdrLine1;
       this.cltResdAdrLine2 = cltResdAdrLine2;
       this.cltResdAdrCity = cltResdAdrCity;
       this.cltResdAdrState = cltResdAdrState;
       this.cltResdAdrZip = cltResdAdrZip;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
    }
   
     @Id 

    
    @Column(name="NCP_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getNcpId() {
        return this.ncpId;
    }
    
    public void setNcpId(BigInteger ncpId) {
        this.ncpId = ncpId;
    }

    
    @Column(name="KIDS_SUMMARY_ID", precision=22, scale=0)
    public BigInteger getKidsSummaryId() {
        return this.kidsSummaryId;
    }
    
    public void setKidsSummaryId(BigInteger kidsSummaryId) {
        this.kidsSummaryId = kidsSummaryId;
    }

    
    @Column(name="NCP_LAST_NAME", length=17)
    public String getNcpLastName() {
        return this.ncpLastName;
    }
    
    public void setNcpLastName(String ncpLastName) {
        this.ncpLastName = ncpLastName;
    }

    
    @Column(name="NCP_FIRST_NAME", length=12)
    public String getNcpFirstName() {
        return this.ncpFirstName;
    }
    
    public void setNcpFirstName(String ncpFirstName) {
        this.ncpFirstName = ncpFirstName;
    }

    
    @Column(name="NCP_MIDDLE_INITIAL", length=1)
    public Character getNcpMiddleInitial() {
        return this.ncpMiddleInitial;
    }
    
    public void setNcpMiddleInitial(Character ncpMiddleInitial) {
        this.ncpMiddleInitial = ncpMiddleInitial;
    }

    
    @Column(name="NCP_SSN", length=9)
    public String getNcpSsn() {
        return this.ncpSsn;
    }
    
    public void setNcpSsn(String ncpSsn) {
        this.ncpSsn = ncpSsn;
    }

    
    @Column(name="NCP_CASE_ID", length=9)
    public String getNcpCaseId() {
        return this.ncpCaseId;
    }
    
    public void setNcpCaseId(String ncpCaseId) {
        this.ncpCaseId = ncpCaseId;
    }

    
    @Column(name="NCP_REGION_NAME", length=11)
    public String getNcpRegionName() {
        return this.ncpRegionName;
    }
    
    public void setNcpRegionName(String ncpRegionName) {
        this.ncpRegionName = ncpRegionName;
    }

    
    @Column(name="NCP_CASE_STATUS_CD", length=4)
    public String getNcpCaseStatusCd() {
        return this.ncpCaseStatusCd;
    }
    
    public void setNcpCaseStatusCd(String ncpCaseStatusCd) {
        this.ncpCaseStatusCd = ncpCaseStatusCd;
    }

    
    @Column(name="NCP_HOME_PHONE_NUM", precision=22, scale=0)
    public BigInteger getNcpHomePhoneNum() {
        return this.ncpHomePhoneNum;
    }
    
    public void setNcpHomePhoneNum(BigInteger ncpHomePhoneNum) {
        this.ncpHomePhoneNum = ncpHomePhoneNum;
    }

    
    @Column(name="NCP_BUSINESS_PHONE_NUM", precision=22, scale=0)
    public BigInteger getNcpBusinessPhoneNum() {
        return this.ncpBusinessPhoneNum;
    }
    
    public void setNcpBusinessPhoneNum(BigInteger ncpBusinessPhoneNum) {
        this.ncpBusinessPhoneNum = ncpBusinessPhoneNum;
    }

    
    @Column(name="NCP_BUSINESS_EXTN_NUM", precision=22, scale=0)
    public BigInteger getNcpBusinessExtnNum() {
        return this.ncpBusinessExtnNum;
    }
    
    public void setNcpBusinessExtnNum(BigInteger ncpBusinessExtnNum) {
        this.ncpBusinessExtnNum = ncpBusinessExtnNum;
    }

    
    @Column(name="NCP_CELL_PHONE_NUM", precision=22, scale=0)
    public BigInteger getNcpCellPhoneNum() {
        return this.ncpCellPhoneNum;
    }
    
    public void setNcpCellPhoneNum(BigInteger ncpCellPhoneNum) {
        this.ncpCellPhoneNum = ncpCellPhoneNum;
    }

    
    @Column(name="NCP_FAMILY_VIOLENCE_IND", length=1)
    public Character getNcpFamilyViolenceInd() {
        return this.ncpFamilyViolenceInd;
    }
    
    public void setNcpFamilyViolenceInd(Character ncpFamilyViolenceInd) {
        this.ncpFamilyViolenceInd = ncpFamilyViolenceInd;
    }

    
    @Column(name="NCP_ERR_CD", length=3)
    public String getNcpErrCd() {
        return this.ncpErrCd;
    }
    
    public void setNcpErrCd(String ncpErrCd) {
        this.ncpErrCd = ncpErrCd;
    }

    
    @Column(name="KIDS_CASE_TYPE", length=8)
    public String getKidsCaseType() {
        return this.kidsCaseType;
    }
    
    public void setKidsCaseType(String kidsCaseType) {
        this.kidsCaseType = kidsCaseType;
    }

    
    @Column(name="CLT_MAIL_ADR_LINE1", length=40)
    public String getCltMailAdrLine1() {
        return this.cltMailAdrLine1;
    }
    
    public void setCltMailAdrLine1(String cltMailAdrLine1) {
        this.cltMailAdrLine1 = cltMailAdrLine1;
    }

    
    @Column(name="CLT_MAIL_ADR_LINE2", length=40)
    public String getCltMailAdrLine2() {
        return this.cltMailAdrLine2;
    }
    
    public void setCltMailAdrLine2(String cltMailAdrLine2) {
        this.cltMailAdrLine2 = cltMailAdrLine2;
    }

    
    @Column(name="CLT_MAIL_ADR_CITY", length=20)
    public String getCltMailAdrCity() {
        return this.cltMailAdrCity;
    }
    
    public void setCltMailAdrCity(String cltMailAdrCity) {
        this.cltMailAdrCity = cltMailAdrCity;
    }

    
    @Column(name="CLT_MAIL_ADR_STATE", length=2)
    public String getCltMailAdrState() {
        return this.cltMailAdrState;
    }
    
    public void setCltMailAdrState(String cltMailAdrState) {
        this.cltMailAdrState = cltMailAdrState;
    }

    
    @Column(name="CLT_MAIL_ADR_ZIP", length=11)
    public String getCltMailAdrZip() {
        return this.cltMailAdrZip;
    }
    
    public void setCltMailAdrZip(String cltMailAdrZip) {
        this.cltMailAdrZip = cltMailAdrZip;
    }

    
    @Column(name="CLT_RESD_ADR_LINE1", length=40)
    public String getCltResdAdrLine1() {
        return this.cltResdAdrLine1;
    }
    
    public void setCltResdAdrLine1(String cltResdAdrLine1) {
        this.cltResdAdrLine1 = cltResdAdrLine1;
    }

    
    @Column(name="CLT_RESD_ADR_LINE2", length=40)
    public String getCltResdAdrLine2() {
        return this.cltResdAdrLine2;
    }
    
    public void setCltResdAdrLine2(String cltResdAdrLine2) {
        this.cltResdAdrLine2 = cltResdAdrLine2;
    }

    
    @Column(name="CLT_RESD_ADR_CITY", length=20)
    public String getCltResdAdrCity() {
        return this.cltResdAdrCity;
    }
    
    public void setCltResdAdrCity(String cltResdAdrCity) {
        this.cltResdAdrCity = cltResdAdrCity;
    }

    
    @Column(name="CLT_RESD_ADR_STATE", length=2)
    public String getCltResdAdrState() {
        return this.cltResdAdrState;
    }
    
    public void setCltResdAdrState(String cltResdAdrState) {
        this.cltResdAdrState = cltResdAdrState;
    }

    
    @Column(name="CLT_RESD_ADR_ZIP", length=11)
    public String getCltResdAdrZip() {
        return this.cltResdAdrZip;
    }
    
    public void setCltResdAdrZip(String cltResdAdrZip) {
        this.cltResdAdrZip = cltResdAdrZip;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }




}


