package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmKidsCltStagingAId generated by hbm2java
 */
@Embeddable
public class AmKidsCltStagingAId  implements java.io.Serializable {


     private BigInteger cltId;
     private BigInteger historySeq;

    public AmKidsCltStagingAId() {
    }

    public AmKidsCltStagingAId(BigInteger cltId, BigInteger historySeq) {
       this.cltId = cltId;
       this.historySeq = historySeq;
    }
   


    @Column(name="CLT_ID", nullable=false, precision=22, scale=0)
    public BigInteger getCltId() {
        return this.cltId;
    }
    
    public void setCltId(BigInteger cltId) {
        this.cltId = cltId;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmKidsCltStagingAId) ) return false;
		 AmKidsCltStagingAId castOther = ( AmKidsCltStagingAId ) other; 
         
		 return ( (this.getCltId()==castOther.getCltId()) || ( this.getCltId()!=null && castOther.getCltId()!=null && this.getCltId().equals(castOther.getCltId()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCltId() == null ? 0 : this.getCltId().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


