package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmKidsSummary generated by hbm2java
 */
@Entity
@Table(name="AM_KIDS_SUMMARY"
    ,schema="IE_APP_ONLINE"
)
public class AmKidsSummary  implements java.io.Serializable {


     private BigInteger kidsSummaryId;
     private String kidsSsn;
     private String kidsCaseNum;
     private BigInteger indvId;
     private LocalDate runDt;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;

    public AmKidsSummary() {
    }

	
    public AmKidsSummary(BigInteger kidsSummaryId, LocalDate runDt, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.kidsSummaryId = kidsSummaryId;
        this.runDt = runDt;
        this.historySeq = historySeq;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmKidsSummary(BigInteger kidsSummaryId, String kidsSsn, String kidsCaseNum, BigInteger indvId, LocalDate runDt, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
       this.kidsSummaryId = kidsSummaryId;
       this.kidsSsn = kidsSsn;
       this.kidsCaseNum = kidsCaseNum;
       this.indvId = indvId;
       this.runDt = runDt;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
    }
   
     @Id 

    
    @Column(name="KIDS_SUMMARY_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getKidsSummaryId() {
        return this.kidsSummaryId;
    }
    
    public void setKidsSummaryId(BigInteger kidsSummaryId) {
        this.kidsSummaryId = kidsSummaryId;
    }

    
    @Column(name="KIDS_SSN", length=11)
    public String getKidsSsn() {
        return this.kidsSsn;
    }
    
    public void setKidsSsn(String kidsSsn) {
        this.kidsSsn = kidsSsn;
    }

    
    @Column(name="KIDS_CASE_NUM", length=20)
    public String getKidsCaseNum() {
        return this.kidsCaseNum;
    }
    
    public void setKidsCaseNum(String kidsCaseNum) {
        this.kidsCaseNum = kidsCaseNum;
    }

    
    @Column(name="INDV_ID", precision=22, scale=0)
    public BigInteger getIndvId() {
        return this.indvId;
    }
    
    public void setIndvId(BigInteger indvId) {
        this.indvId = indvId;
    }

    
    @Column(name="RUN_DT", nullable=false, length=7)
    public LocalDate getRunDt() {
        return this.runDt;
    }
    
    public void setRunDt(LocalDate runDt) {
        this.runDt = runDt;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }




}


