package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmOfficeTimeSlotA generated by hbm2java
 */
@Entity
@Table(name="AM_OFFICE_TIME_SLOT_A"
    ,schema="IE_APP_ONLINE"
)
public class AmOfficeTimeSlotA  implements java.io.Serializable {


     private AmOfficeTimeSlotAId id;
     private BigInteger timeSlotDay;
     private LocalDate beginTime;
     private BigInteger timeSlotDuration;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String auditUserId;
     private LocalDate auditDt;
     private String agencyCd;

    public AmOfficeTimeSlotA() {
    }

    public AmOfficeTimeSlotA(AmOfficeTimeSlotAId id, BigInteger timeSlotDay, LocalDate beginTime, BigInteger timeSlotDuration, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt, String agencyCd) {
       this.id = id;
       this.timeSlotDay = timeSlotDay;
       this.beginTime = beginTime;
       this.timeSlotDuration = timeSlotDuration;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.auditUserId = auditUserId;
       this.auditDt = auditDt;
       this.agencyCd = agencyCd;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="officeTimeSlotId", column=@Column(name="OFFICE_TIME_SLOT_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="historySeq", column=@Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0) ) } )
    public AmOfficeTimeSlotAId getId() {
        return this.id;
    }
    
    public void setId(AmOfficeTimeSlotAId id) {
        this.id = id;
    }

    
    @Column(name="TIME_SLOT_DAY", nullable=false, precision=22, scale=0)
    public BigInteger getTimeSlotDay() {
        return this.timeSlotDay;
    }
    
    public void setTimeSlotDay(BigInteger timeSlotDay) {
        this.timeSlotDay = timeSlotDay;
    }

    
    @Column(name="BEGIN_TIME", nullable=false, length=7)
    public LocalDate getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(LocalDate beginTime) {
        this.beginTime = beginTime;
    }

    
    @Column(name="TIME_SLOT_DURATION", nullable=false, precision=22, scale=0)
    public BigInteger getTimeSlotDuration() {
        return this.timeSlotDuration;
    }
    
    public void setTimeSlotDuration(BigInteger timeSlotDuration) {
        this.timeSlotDuration = timeSlotDuration;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AUDIT_USER_ID", nullable=false, length=20)
    public String getAuditUserId() {
        return this.auditUserId;
    }
    
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    
    @Column(name="AUDIT_DT", nullable=false, length=7)
    public LocalDate getAuditDt() {
        return this.auditDt;
    }
    
    public void setAuditDt(LocalDate auditDt) {
        this.auditDt = auditDt;
    }

    
    @Column(name="AGENCY_CD", nullable=false, length=3)
    public String getAgencyCd() {
        return this.agencyCd;
    }
    
    public void setAgencyCd(String agencyCd) {
        this.agencyCd = agencyCd;
    }




}


