package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmOfficeTimeSlotAId generated by hbm2java
 */
@Embeddable
public class AmOfficeTimeSlotAId  implements java.io.Serializable {


     private BigInteger officeTimeSlotId;
     private BigInteger historySeq;

    public AmOfficeTimeSlotAId() {
    }

    public AmOfficeTimeSlotAId(BigInteger officeTimeSlotId, BigInteger historySeq) {
       this.officeTimeSlotId = officeTimeSlotId;
       this.historySeq = historySeq;
    }
   


    @Column(name="OFFICE_TIME_SLOT_ID", nullable=false, precision=22, scale=0)
    public BigInteger getOfficeTimeSlotId() {
        return this.officeTimeSlotId;
    }
    
    public void setOfficeTimeSlotId(BigInteger officeTimeSlotId) {
        this.officeTimeSlotId = officeTimeSlotId;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmOfficeTimeSlotAId) ) return false;
		 AmOfficeTimeSlotAId castOther = ( AmOfficeTimeSlotAId ) other; 
         
		 return ( (this.getOfficeTimeSlotId()==castOther.getOfficeTimeSlotId()) || ( this.getOfficeTimeSlotId()!=null && castOther.getOfficeTimeSlotId()!=null && this.getOfficeTimeSlotId().equals(castOther.getOfficeTimeSlotId()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOfficeTimeSlotId() == null ? 0 : this.getOfficeTimeSlotId().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


