package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmOfficeTimeSlot generated by hbm2java
 */
@Entity
@Table(name="AM_OFFICE_TIME_SLOT"
    ,schema="IE_APP_ONLINE"
)
public class AmOfficeTimeSlot  implements java.io.Serializable {


     private BigInteger officeTimeSlotId;
     private BigInteger timeSlotDay;
     private LocalDate beginTime;
     private BigInteger timeSlotDuration;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String agencyCd;

    public AmOfficeTimeSlot() {
    }

    public AmOfficeTimeSlot(BigInteger officeTimeSlotId, BigInteger timeSlotDay, LocalDate beginTime, BigInteger timeSlotDuration, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String agencyCd) {
       this.officeTimeSlotId = officeTimeSlotId;
       this.timeSlotDay = timeSlotDay;
       this.beginTime = beginTime;
       this.timeSlotDuration = timeSlotDuration;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.agencyCd = agencyCd;
    }
   
     @Id 

    
    @Column(name="OFFICE_TIME_SLOT_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getOfficeTimeSlotId() {
        return this.officeTimeSlotId;
    }
    
    public void setOfficeTimeSlotId(BigInteger officeTimeSlotId) {
        this.officeTimeSlotId = officeTimeSlotId;
    }

    
    @Column(name="TIME_SLOT_DAY", nullable=false, precision=22, scale=0)
    public BigInteger getTimeSlotDay() {
        return this.timeSlotDay;
    }
    
    public void setTimeSlotDay(BigInteger timeSlotDay) {
        this.timeSlotDay = timeSlotDay;
    }

    
    @Column(name="BEGIN_TIME", nullable=false, length=7)
    public LocalDate getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(LocalDate beginTime) {
        this.beginTime = beginTime;
    }

    
    @Column(name="TIME_SLOT_DURATION", nullable=false, precision=22, scale=0)
    public BigInteger getTimeSlotDuration() {
        return this.timeSlotDuration;
    }
    
    public void setTimeSlotDuration(BigInteger timeSlotDuration) {
        this.timeSlotDuration = timeSlotDuration;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AGENCY_CD", nullable=false, length=3)
    public String getAgencyCd() {
        return this.agencyCd;
    }
    
    public void setAgencyCd(String agencyCd) {
        this.agencyCd = agencyCd;
    }




}


