package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmPgmDetailsA generated by hbm2java
 */
@Entity
@Table(name="AM_PGM_DETAILS_A"
    ,schema="IE_APP_ONLINE"
)
public class AmPgmDetailsA  implements java.io.Serializable {


     private AmPgmDetailsAId id;
     private String programCd;
     private String appealTypeCd;
     private String agencyCd;
     private Character continueBenefitsInd;
     private String deptRepFilingApl;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String auditUserId;
     private LocalDate auditDt;

    public AmPgmDetailsA() {
    }

	
    public AmPgmDetailsA(AmPgmDetailsAId id, String programCd, String appealTypeCd, String agencyCd, String deptRepFilingApl, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
        this.id = id;
        this.programCd = programCd;
        this.appealTypeCd = appealTypeCd;
        this.agencyCd = agencyCd;
        this.deptRepFilingApl = deptRepFilingApl;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
        this.auditUserId = auditUserId;
        this.auditDt = auditDt;
    }
    public AmPgmDetailsA(AmPgmDetailsAId id, String programCd, String appealTypeCd, String agencyCd, Character continueBenefitsInd, String deptRepFilingApl, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt) {
       this.id = id;
       this.programCd = programCd;
       this.appealTypeCd = appealTypeCd;
       this.agencyCd = agencyCd;
       this.continueBenefitsInd = continueBenefitsInd;
       this.deptRepFilingApl = deptRepFilingApl;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.auditUserId = auditUserId;
       this.auditDt = auditDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pgmSeqNum", column=@Column(name="PGM_SEQ_NUM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="historySeq", column=@Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0) ) } )
    public AmPgmDetailsAId getId() {
        return this.id;
    }
    
    public void setId(AmPgmDetailsAId id) {
        this.id = id;
    }

    
    @Column(name="PROGRAM_CD", nullable=false, length=2)
    public String getProgramCd() {
        return this.programCd;
    }
    
    public void setProgramCd(String programCd) {
        this.programCd = programCd;
    }

    
    @Column(name="APPEAL_TYPE_CD", nullable=false, length=2)
    public String getAppealTypeCd() {
        return this.appealTypeCd;
    }
    
    public void setAppealTypeCd(String appealTypeCd) {
        this.appealTypeCd = appealTypeCd;
    }

    
    @Column(name="AGENCY_CD", nullable=false, length=2)
    public String getAgencyCd() {
        return this.agencyCd;
    }
    
    public void setAgencyCd(String agencyCd) {
        this.agencyCd = agencyCd;
    }

    
    @Column(name="CONTINUE_BENEFITS_IND", length=1)
    public Character getContinueBenefitsInd() {
        return this.continueBenefitsInd;
    }
    
    public void setContinueBenefitsInd(Character continueBenefitsInd) {
        this.continueBenefitsInd = continueBenefitsInd;
    }

    
    @Column(name="DEPT_REP_FILING_APL", nullable=false, length=50)
    public String getDeptRepFilingApl() {
        return this.deptRepFilingApl;
    }
    
    public void setDeptRepFilingApl(String deptRepFilingApl) {
        this.deptRepFilingApl = deptRepFilingApl;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AUDIT_USER_ID", nullable=false, length=20)
    public String getAuditUserId() {
        return this.auditUserId;
    }
    
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    
    @Column(name="AUDIT_DT", nullable=false, length=7)
    public LocalDate getAuditDt() {
        return this.auditDt;
    }
    
    public void setAuditDt(LocalDate auditDt) {
        this.auditDt = auditDt;
    }




}


