package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmPgmDetailsAId generated by hbm2java
 */
@Embeddable
public class AmPgmDetailsAId  implements java.io.Serializable {


     private BigInteger pgmSeqNum;
     private BigInteger historySeq;

    public AmPgmDetailsAId() {
    }

    public AmPgmDetailsAId(BigInteger pgmSeqNum, BigInteger historySeq) {
       this.pgmSeqNum = pgmSeqNum;
       this.historySeq = historySeq;
    }
   


    @Column(name="PGM_SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getPgmSeqNum() {
        return this.pgmSeqNum;
    }
    
    public void setPgmSeqNum(BigInteger pgmSeqNum) {
        this.pgmSeqNum = pgmSeqNum;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmPgmDetailsAId) ) return false;
		 AmPgmDetailsAId castOther = ( AmPgmDetailsAId ) other; 
         
		 return ( (this.getPgmSeqNum()==castOther.getPgmSeqNum()) || ( this.getPgmSeqNum()!=null && castOther.getPgmSeqNum()!=null && this.getPgmSeqNum().equals(castOther.getPgmSeqNum()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPgmSeqNum() == null ? 0 : this.getPgmSeqNum().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


