package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmPgmDetails generated by hbm2java
 */
@Entity
@Table(name="AM_PGM_DETAILS"
    ,schema="IE_APP_ONLINE"
)
public class AmPgmDetails  implements java.io.Serializable {


     private BigInteger pgmSeqNum;
     private String programCd;
     private String appealTypeCd;
     private String agencyCd;
     private Character continueBenefitsInd;
     private String deptRepFilingApl;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;

    public AmPgmDetails() {
    }

	
    public AmPgmDetails(BigInteger pgmSeqNum, String programCd, String appealTypeCd, String agencyCd, String deptRepFilingApl, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.pgmSeqNum = pgmSeqNum;
        this.programCd = programCd;
        this.appealTypeCd = appealTypeCd;
        this.agencyCd = agencyCd;
        this.deptRepFilingApl = deptRepFilingApl;
        this.historySeq = historySeq;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmPgmDetails(BigInteger pgmSeqNum, String programCd, String appealTypeCd, String agencyCd, Character continueBenefitsInd, String deptRepFilingApl, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
       this.pgmSeqNum = pgmSeqNum;
       this.programCd = programCd;
       this.appealTypeCd = appealTypeCd;
       this.agencyCd = agencyCd;
       this.continueBenefitsInd = continueBenefitsInd;
       this.deptRepFilingApl = deptRepFilingApl;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
    }
   
     @Id 

    
    @Column(name="PGM_SEQ_NUM", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getPgmSeqNum() {
        return this.pgmSeqNum;
    }
    
    public void setPgmSeqNum(BigInteger pgmSeqNum) {
        this.pgmSeqNum = pgmSeqNum;
    }

    
    @Column(name="PROGRAM_CD", nullable=false, length=2)
    public String getProgramCd() {
        return this.programCd;
    }
    
    public void setProgramCd(String programCd) {
        this.programCd = programCd;
    }

    
    @Column(name="APPEAL_TYPE_CD", nullable=false, length=2)
    public String getAppealTypeCd() {
        return this.appealTypeCd;
    }
    
    public void setAppealTypeCd(String appealTypeCd) {
        this.appealTypeCd = appealTypeCd;
    }

    
    @Column(name="AGENCY_CD", nullable=false, length=2)
    public String getAgencyCd() {
        return this.agencyCd;
    }
    
    public void setAgencyCd(String agencyCd) {
        this.agencyCd = agencyCd;
    }

    
    @Column(name="CONTINUE_BENEFITS_IND", length=1)
    public Character getContinueBenefitsInd() {
        return this.continueBenefitsInd;
    }
    
    public void setContinueBenefitsInd(Character continueBenefitsInd) {
        this.continueBenefitsInd = continueBenefitsInd;
    }

    
    @Column(name="DEPT_REP_FILING_APL", nullable=false, length=50)
    public String getDeptRepFilingApl() {
        return this.deptRepFilingApl;
    }
    
    public void setDeptRepFilingApl(String deptRepFilingApl) {
        this.deptRepFilingApl = deptRepFilingApl;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }




}


