package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmProgramParams generated by hbm2java
 */
@Entity
@Table(name="AM_PROGRAM_PARAMS"
    ,schema="IE_APP_ONLINE"
)
public class AmProgramParams  implements java.io.Serializable {


     private String programCd;
     private BigInteger netDaysManualSched;
     private BigInteger daysFirstHearing;
     private BigInteger continuanceLimit;
     private BigInteger maxWeeksHearing;
     private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;

    public AmProgramParams() {
    }

	
    public AmProgramParams(String programCd, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.programCd = programCd;
        this.historySeq = historySeq;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmProgramParams(String programCd, BigInteger netDaysManualSched, BigInteger daysFirstHearing, BigInteger continuanceLimit, BigInteger maxWeeksHearing, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
       this.programCd = programCd;
       this.netDaysManualSched = netDaysManualSched;
       this.daysFirstHearing = daysFirstHearing;
       this.continuanceLimit = continuanceLimit;
       this.maxWeeksHearing = maxWeeksHearing;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
    }
   
     @Id 

    
    @Column(name="PROGRAM_CD", unique=true, nullable=false, length=5)
    public String getProgramCd() {
        return this.programCd;
    }
    
    public void setProgramCd(String programCd) {
        this.programCd = programCd;
    }

    
    @Column(name="NET_DAYS_MANUAL_SCHED", precision=22, scale=0)
    public BigInteger getNetDaysManualSched() {
        return this.netDaysManualSched;
    }
    
    public void setNetDaysManualSched(BigInteger netDaysManualSched) {
        this.netDaysManualSched = netDaysManualSched;
    }

    
    @Column(name="DAYS_FIRST_HEARING", precision=22, scale=0)
    public BigInteger getDaysFirstHearing() {
        return this.daysFirstHearing;
    }
    
    public void setDaysFirstHearing(BigInteger daysFirstHearing) {
        this.daysFirstHearing = daysFirstHearing;
    }

    
    @Column(name="CONTINUANCE_LIMIT", precision=22, scale=0)
    public BigInteger getContinuanceLimit() {
        return this.continuanceLimit;
    }
    
    public void setContinuanceLimit(BigInteger continuanceLimit) {
        this.continuanceLimit = continuanceLimit;
    }

    
    @Column(name="MAX_WEEKS_HEARING", precision=22, scale=0)
    public BigInteger getMaxWeeksHearing() {
        return this.maxWeeksHearing;
    }
    
    public void setMaxWeeksHearing(BigInteger maxWeeksHearing) {
        this.maxWeeksHearing = maxWeeksHearing;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }




}


