package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmPreHearingMeetingAId generated by hbm2java
 */
@Embeddable
public class AmPreHearingMeetingAId  implements java.io.Serializable {


     private BigInteger amPreHearingMeetingSeqNum;
     private BigInteger aplNum;
     private BigInteger historySeq;

    public AmPreHearingMeetingAId() {
    }

    public AmPreHearingMeetingAId(BigInteger amPreHearingMeetingSeqNum, BigInteger aplNum, BigInteger historySeq) {
       this.amPreHearingMeetingSeqNum = amPreHearingMeetingSeqNum;
       this.aplNum = aplNum;
       this.historySeq = historySeq;
    }
   


    @Column(name="AM_PRE_HEARING_MEETING_SEQ_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAmPreHearingMeetingSeqNum() {
        return this.amPreHearingMeetingSeqNum;
    }
    
    public void setAmPreHearingMeetingSeqNum(BigInteger amPreHearingMeetingSeqNum) {
        this.amPreHearingMeetingSeqNum = amPreHearingMeetingSeqNum;
    }


    @Column(name="APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmPreHearingMeetingAId) ) return false;
		 AmPreHearingMeetingAId castOther = ( AmPreHearingMeetingAId ) other; 
         
		 return ( (this.getAmPreHearingMeetingSeqNum()==castOther.getAmPreHearingMeetingSeqNum()) || ( this.getAmPreHearingMeetingSeqNum()!=null && castOther.getAmPreHearingMeetingSeqNum()!=null && this.getAmPreHearingMeetingSeqNum().equals(castOther.getAmPreHearingMeetingSeqNum()) ) )
 && ( (this.getAplNum()==castOther.getAplNum()) || ( this.getAplNum()!=null && castOther.getAplNum()!=null && this.getAplNum().equals(castOther.getAplNum()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAmPreHearingMeetingSeqNum() == null ? 0 : this.getAmPreHearingMeetingSeqNum().hashCode() );
         result = 37 * result + ( getAplNum() == null ? 0 : this.getAplNum().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


