package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmProgramParamsAId generated by hbm2java
 */
@Embeddable
public class AmProgramParamsAId  implements java.io.Serializable {


     private String programCd;
     private BigInteger historySeq;

    public AmProgramParamsAId() {
    }

    public AmProgramParamsAId(String programCd, BigInteger historySeq) {
       this.programCd = programCd;
       this.historySeq = historySeq;
    }
   


    @Column(name="PROGRAM_CD", nullable=false, length=5)
    public String getProgramCd() {
        return this.programCd;
    }
    
    public void setProgramCd(String programCd) {
        this.programCd = programCd;
    }


    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmProgramParamsAId) ) return false;
		 AmProgramParamsAId castOther = ( AmProgramParamsAId ) other; 
         
		 return ( (this.getProgramCd()==castOther.getProgramCd()) || ( this.getProgramCd()!=null && castOther.getProgramCd()!=null && this.getProgramCd().equals(castOther.getProgramCd()) ) )
 && ( (this.getHistorySeq()==castOther.getHistorySeq()) || ( this.getHistorySeq()!=null && castOther.getHistorySeq()!=null && this.getHistorySeq().equals(castOther.getHistorySeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProgramCd() == null ? 0 : this.getProgramCd().hashCode() );
         result = 37 * result + ( getHistorySeq() == null ? 0 : this.getHistorySeq().hashCode() );
         return result;
   }   


}


