package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import com.deloitte.nextgen.framework.persistence.annotations.EntityType;
import com.deloitte.nextgen.framework.persistence.entity.type.one.TypeOneBaseEntity;
import com.deloitte.nextgen.framework.persistence.enums.TypeEnum;
import lombok.*;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.*;

/**
 * AmRepresentativeDetails generated by hbm2java
 */
@Entity
@Table(name="AM_REPRESENTATIVE_DETAILS")
@EntityType(type= TypeEnum.ONE)
@EqualsAndHashCode(callSuper=false)
@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class AmRepresentativeDetails extends TypeOneBaseEntity<BigInteger> implements Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "AM_REPRESENTATIVE_DETAILS_1SQ")
     @Column(name="CLIENT_REP_ID", unique=true, nullable=false, precision=22, scale=0)
     private BigInteger clientRepId;
     @Column(name="REP_TYPE_CD", length=2)
     private String repTypeCd;
     @Column(name="PREFIX_NAME", length=4)
     private String prefixName;
     @Column(name="FIRST_NAME", length=45)
     private String firstName;
     @Column(name="MID_NAME", length=30)
     private String midName;
     @Column(name="LAST_NAME", length=45)
     private String lastName;
     @Column(name="SUFFIX_NAME", length=4)
     private String suffixName;
     @Column(name="REL_TO_APPELLANT_CD", length=2)
     private String relToAppellantCd;
     @Column(name="HOME_PH_NUM", length=10)
     private String homePhNum;
     @Column(name="WORK_PH_NUM", length=10)
     private String workPhNum;
     @Column(name="PH_EXT", length=4)
     private String phExt;
     @Column(name="OTHER_NUM", length=10)
     private String otherNum;
     @Column(name="EMAIL_ID", length=125)
     private String emailId;
     @Column(name="COMPANY_NAME", length=45)
     private String companyName;
     @Column(name="ADDRESS_ID", nullable=false, precision=22, scale=0)
     private BigInteger addressId;
    /* @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
     private BigInteger historySeq;
     @Column(name="CREATE_USER_ID", nullable=false, length=20)
     private String createUserId;
     @Column(name="CREATE_DT", nullable=false, length=7)
     private LocalDate createDt;
     @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
     private BigInteger uniqueTransId;
     @Column(name="ARCHIVE_DT", nullable=false, length=7)
     private LocalDate archiveDt;
     @Column(name="UPDATE_DT", length=7)
     private LocalDate updateDt;
     @Column(name="UPDATE_USER_ID", length=20)
     private String updateUserId;*/
     @Column(name="RECV_NOTICE_SW", length=1)
     private Character recvNoticeSw;
     @Column(name="AR_NOTICE_LANG_CD", length=3)
     private String arNoticeLangCd;

    /*public AmRepresentativeDetails() {
    }

	
    public AmRepresentativeDetails(BigInteger clientRepId, BigInteger addressId, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.clientRepId = clientRepId;
        this.addressId = addressId;
        this.historySeq = historySeq;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmRepresentativeDetails(BigInteger clientRepId, String repTypeCd, String prefixName, String firstName, String midName, String lastName, String suffixName, String relToAppellantCd, String homePhNum, String workPhNum, String phExt, String otherNum, String emailId, String companyName, BigInteger addressId, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, LocalDate updateDt, String updateUserId, Character recvNoticeSw, String arNoticeLangCd) {
       this.clientRepId = clientRepId;
       this.repTypeCd = repTypeCd;
       this.prefixName = prefixName;
       this.firstName = firstName;
       this.midName = midName;
       this.lastName = lastName;
       this.suffixName = suffixName;
       this.relToAppellantCd = relToAppellantCd;
       this.homePhNum = homePhNum;
       this.workPhNum = workPhNum;
       this.phExt = phExt;
       this.otherNum = otherNum;
       this.emailId = emailId;
       this.companyName = companyName;
       this.addressId = addressId;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.updateDt = updateDt;
       this.updateUserId = updateUserId;
       this.recvNoticeSw = recvNoticeSw;
       this.arNoticeLangCd = arNoticeLangCd;
    }
   
     @Id 

    
    @Column(name="CLIENT_REP_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getClientRepId() {
        return this.clientRepId;
    }
    
    public void setClientRepId(BigInteger clientRepId) {
        this.clientRepId = clientRepId;
    }

    
    @Column(name="REP_TYPE_CD", length=2)
    public String getRepTypeCd() {
        return this.repTypeCd;
    }
    
    public void setRepTypeCd(String repTypeCd) {
        this.repTypeCd = repTypeCd;
    }

    
    @Column(name="PREFIX_NAME", length=4)
    public String getPrefixName() {
        return this.prefixName;
    }
    
    public void setPrefixName(String prefixName) {
        this.prefixName = prefixName;
    }

    
    @Column(name="FIRST_NAME", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="MID_NAME", length=30)
    public String getMidName() {
        return this.midName;
    }
    
    public void setMidName(String midName) {
        this.midName = midName;
    }

    
    @Column(name="LAST_NAME", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="SUFFIX_NAME", length=4)
    public String getSuffixName() {
        return this.suffixName;
    }
    
    public void setSuffixName(String suffixName) {
        this.suffixName = suffixName;
    }

    
    @Column(name="REL_TO_APPELLANT_CD", length=2)
    public String getRelToAppellantCd() {
        return this.relToAppellantCd;
    }
    
    public void setRelToAppellantCd(String relToAppellantCd) {
        this.relToAppellantCd = relToAppellantCd;
    }

    
    @Column(name="HOME_PH_NUM", length=10)
    public String getHomePhNum() {
        return this.homePhNum;
    }
    
    public void setHomePhNum(String homePhNum) {
        this.homePhNum = homePhNum;
    }

    
    @Column(name="WORK_PH_NUM", length=10)
    public String getWorkPhNum() {
        return this.workPhNum;
    }
    
    public void setWorkPhNum(String workPhNum) {
        this.workPhNum = workPhNum;
    }

    
    @Column(name="PH_EXT", length=4)
    public String getPhExt() {
        return this.phExt;
    }
    
    public void setPhExt(String phExt) {
        this.phExt = phExt;
    }

    
    @Column(name="OTHER_NUM", length=10)
    public String getOtherNum() {
        return this.otherNum;
    }
    
    public void setOtherNum(String otherNum) {
        this.otherNum = otherNum;
    }

    
    @Column(name="EMAIL_ID", length=125)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="COMPANY_NAME", length=45)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    
    @Column(name="ADDRESS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(BigInteger addressId) {
        this.addressId = addressId;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="UPDATE_DT", length=7)
    public LocalDate getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(LocalDate updateDt) {
        this.updateDt = updateDt;
    }

    
    @Column(name="UPDATE_USER_ID", length=20)
    public String getUpdateUserId() {
        return this.updateUserId;
    }
    
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    
    @Column(name="RECV_NOTICE_SW", length=1)
    public Character getRecvNoticeSw() {
        return this.recvNoticeSw;
    }
    
    public void setRecvNoticeSw(Character recvNoticeSw) {
        this.recvNoticeSw = recvNoticeSw;
    }

    
    @Column(name="AR_NOTICE_LANG_CD", length=3)
    public String getArNoticeLangCd() {
        return this.arNoticeLangCd;
    }
    
    public void setArNoticeLangCd(String arNoticeLangCd) {
        this.arNoticeLangCd = arNoticeLangCd;
    }
*/



}


