package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import com.deloitte.nextgen.framework.persistence.annotations.EntityType;
import com.deloitte.nextgen.framework.persistence.entity.type.one.TypeOneBaseEntity;
import com.deloitte.nextgen.framework.persistence.enums.TypeEnum;
import lombok.*;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.*;

/**
 * AmRequestDetails generated by hbm2java
 */
@Entity
@Table(name="AM_REQUEST_DETAILS")
@EntityType(type= TypeEnum.ONE)
@EqualsAndHashCode(callSuper=false)
@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class AmRequestDetails  extends TypeOneBaseEntity<BigInteger> implements Serializable {

     @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE , generator = "AM_REQUEST_DETAILS_2SQ")
    @Column(name = "APL_NUM")
    private BigInteger aplNum;
 @Column(name="INDV_ID")
     private BigInteger indvId;
 @Column(name="NON_IES_CASE_NUM")
     private String nonIesCaseNum;
 @Column(name="NON_IES_CASE_TYPE")
     private String nonIesCaseType;
 @Column(name="PREFERRED_LANG_CD")
     private String preferredLangCd;
 @Column(name="OTHER_LANG")
     private String otherLang;
 @Column(name="APL_NOTICE_DT")
     private LocalDate aplNoticeDt;
 @Column(name="RECVD_DT")
     private LocalDate recvdDt;
 @Column(name="PERFECTED_DT")
     private LocalDate perfectedDt;
 @Column(name="POSTMARKED_DT")
     private LocalDate postmarkedDt;
 @Column(name="FILING_METHOD_CD")
     private String filingMethodCd;
 @Column(name="MCO_IND")
     private Character mcoInd;
 @Column(name="HOLD_LETTERS_IND")
     private Character holdLettersInd;
 @Column(name="INTERPRETER_IND")
     private Character interpreterInd;
 @Column(name="EXPEDITED_IND")
     private Character expeditedInd;
 @Column(name="TYPE_OF_HEARING_CD")
     private String typeOfHearingCd;
 @Column(name="URGENT_IND")
     private Character urgentInd;
 @Column(name="HEARING_LOCATION_ID")
     private BigInteger hearingLocationId;
 @Column(name="ADDRESS_ID")
     private BigInteger addressId;
 @Column(name="HOME_PH_NUM")
     private BigInteger homePhNum;
 @Column(name="WORK_PH_NUM")
     private BigInteger workPhNum;
 @Column(name="EXT_NUM")
     private BigInteger extNum;
 @Column(name="CELL_PH_NUM")
     private BigInteger cellPhNum;
 @Column(name="TDD_OTHER")
     private String tddOther;
 @Column(name="EMAIL_ID")
     private String emailId;
 @Column(name="PREFERRED_CNTCT_CD")
     private String preferredCntctCd;
 @Column(name="ALT_COMM_METHOD_CD")
     private String altCommMethodCd;
 @Column(name="OFFICE_NUM")
     private BigInteger officeNum;
 @Column(name="CONVERSION_IND")
     private String conversionInd;
    /* private BigInteger historySeq;
     private String createUserId;
     private LocalDate createDt;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;*/
 @Column(name="KIDS_CASE_ID")
     private String kidsCaseId;
 @Column(name="CC_INT_ID")
     private String ccIntId;
 @Column(name="LEGACY_HRNG_NUM")
     private String legacyHrngNum;
 @Column(name="EXHIBIT_SENT")
     private String exhibitSent;
 @Column(name="EXHIBIT_SENT_DATE")
     private LocalDate exhibitSentDate;
 @Column(name="ABE_SYNC_IND")
     private Character abeSyncInd;
 @Column(name="CONVERSION_DOC_IND")
     private Character conversionDocInd;
 @Column(name="SEGMENT_IND")
     private Character segmentInd;
 @Column(name="IS_DEPT_REP_APL")
     private Character isDeptRepApl;
 @Column(name="DUPLICATE_SW")
     private Character duplicateSw;
 @Column(name="CALL_NOTES_TXT")
     private String callNotesTxt;
 @Column(name="CALLER_RTL_CD")
     private String callerRtlCd;
 @Column(name="CALLER_FIRST_NAME")
     private String callerFirstName;
 @Column(name="CALLER_LAST_NAME")
     private String callerLastName;
 @Column(name="CALLER_PHONE_NUM")
     private Long callerPhoneNum;
 @Column(name="DATE_APPLY_CVRG_TXT")
     private String dateApplyCvrgTxt;
 @Column(name="APPL_EXT2_NUM")
     private Integer applExt2Num;
 @Column(name="CALLER_PHN_EXT_NUM")
     private Integer callerPhnExtNum;
 @Column(name="CALLER_INTR_USED_SW")
     private Character callerIntrUsedSw;
 @Column(name="APPL_IN_SYS_SW")
     private Character applInSysSw;
 @Column(name="HAS_SSN_SW")
     private Character hasSsnSw;
 @Column(name="PROVIDE_ELIG_SW")
     private Character provideEligSw;
 @Column(name="CALLER_IS_APPL_SW")
     private Character callerIsApplSw;
 @Column(name="LINKED_APPL_TXT")
     private String linkedApplTxt;
 @Column(name="CALLER_PRFRD_LANG_CD")
         private String callerPrfrdLangCd;
 /*@Column(name="UPDATE_DT")
     private LocalDate updateDt;*/
 @Column(name="UPDATE_USER_ID")
     private String updateUserId;
 @Column(name="CALLER_PRFRD_LANG_TXT")
         private String callerPrfrdLangTxt;
 @Column(name="APL_POT_ASSC_TXT")
     private String aplPotAsscTxt;
 @Column(name="FAIR_HEARING")
     private Character fairHearing;
 @Column(name="FAIR_HEARING_METHOD")
     private String fairHearingMethod;

   /* public AmRequestDetails() {
    }

	
    public AmRequestDetails(BigInteger aplNum, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.aplNum = aplNum;
        this.historySeq = historySeq;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmRequestDetails(BigInteger aplNum, BigInteger indvId, String nonIesCaseNum, String nonIesCaseType, String preferredLangCd, String otherLang, LocalDate aplNoticeDt, LocalDate recvdDt, LocalDate perfectedDt, LocalDate postmarkedDt, String filingMethodCd, Character mcoInd, Character holdLettersInd, Character interpreterInd, Character expeditedInd, String typeOfHearingCd, Character urgentInd, BigInteger hearingLocationId, BigInteger addressId, BigInteger homePhNum, BigInteger workPhNum, BigInteger extNum, BigInteger cellPhNum, String tddOther, String emailId, String preferredCntctCd, String altCommMethodCd, BigInteger officeNum, String conversionInd, BigInteger historySeq, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt, String kidsCaseId, String ccIntId, String legacyHrngNum, String exhibitSent, LocalDate exhibitSentDate, Character abeSyncInd, Character conversionDocInd, Character segmentInd, Character isDeptRepApl, Character duplicateSw, String callNotesTxt, String callerRtlCd, String callerFirstName, String callerLastName, Long callerPhoneNum, String dateApplyCvrgTxt, Integer applExt2Num, Integer callerPhnExtNum, Character callerIntrUsedSw, Character applInSysSw, Character hasSsnSw, Character provideEligSw, Character callerIsApplSw, String linkedApplTxt, String callerPrfrdLangCd, LocalDate updateDt, String updateUserId, String callerPrfrdLangTxt, String aplPotAsscTxt, Character fairHearing, String fairHearingMethod) {
       this.aplNum = aplNum;
       this.indvId = indvId;
       this.nonIesCaseNum = nonIesCaseNum;
       this.nonIesCaseType = nonIesCaseType;
       this.preferredLangCd = preferredLangCd;
       this.otherLang = otherLang;
       this.aplNoticeDt = aplNoticeDt;
       this.recvdDt = recvdDt;
       this.perfectedDt = perfectedDt;
       this.postmarkedDt = postmarkedDt;
       this.filingMethodCd = filingMethodCd;
       this.mcoInd = mcoInd;
       this.holdLettersInd = holdLettersInd;
       this.interpreterInd = interpreterInd;
       this.expeditedInd = expeditedInd;
       this.typeOfHearingCd = typeOfHearingCd;
       this.urgentInd = urgentInd;
       this.hearingLocationId = hearingLocationId;
       this.addressId = addressId;
       this.homePhNum = homePhNum;
       this.workPhNum = workPhNum;
       this.extNum = extNum;
       this.cellPhNum = cellPhNum;
       this.tddOther = tddOther;
       this.emailId = emailId;
       this.preferredCntctCd = preferredCntctCd;
       this.altCommMethodCd = altCommMethodCd;
       this.officeNum = officeNum;
       this.conversionInd = conversionInd;
       this.historySeq = historySeq;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.kidsCaseId = kidsCaseId;
       this.ccIntId = ccIntId;
       this.legacyHrngNum = legacyHrngNum;
       this.exhibitSent = exhibitSent;
       this.exhibitSentDate = exhibitSentDate;
       this.abeSyncInd = abeSyncInd;
       this.conversionDocInd = conversionDocInd;
       this.segmentInd = segmentInd;
       this.isDeptRepApl = isDeptRepApl;
       this.duplicateSw = duplicateSw;
       this.callNotesTxt = callNotesTxt;
       this.callerRtlCd = callerRtlCd;
       this.callerFirstName = callerFirstName;
       this.callerLastName = callerLastName;
       this.callerPhoneNum = callerPhoneNum;
       this.dateApplyCvrgTxt = dateApplyCvrgTxt;
       this.applExt2Num = applExt2Num;
       this.callerPhnExtNum = callerPhnExtNum;
       this.callerIntrUsedSw = callerIntrUsedSw;
       this.applInSysSw = applInSysSw;
       this.hasSsnSw = hasSsnSw;
       this.provideEligSw = provideEligSw;
       this.callerIsApplSw = callerIsApplSw;
       this.linkedApplTxt = linkedApplTxt;
       this.callerPrfrdLangCd = callerPrfrdLangCd;
       this.updateDt = updateDt;
       this.updateUserId = updateUserId;
       this.callerPrfrdLangTxt = callerPrfrdLangTxt;
       this.aplPotAsscTxt = aplPotAsscTxt;
       this.fairHearing = fairHearing;
       this.fairHearingMethod = fairHearingMethod;
    }
   
     @Id 

    
    @Column(name="APL_NUM", unique=true, nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }

    
    @Column(name="INDV_ID", precision=22, scale=0)
    public BigInteger getIndvId() {
        return this.indvId;
    }
    
    public void setIndvId(BigInteger indvId) {
        this.indvId = indvId;
    }

    
    @Column(name="NON_IES_CASE_NUM", length=20)
    public String getNonIesCaseNum() {
        return this.nonIesCaseNum;
    }
    
    public void setNonIesCaseNum(String nonIesCaseNum) {
        this.nonIesCaseNum = nonIesCaseNum;
    }

    
    @Column(name="NON_IES_CASE_TYPE", length=10)
    public String getNonIesCaseType() {
        return this.nonIesCaseType;
    }
    
    public void setNonIesCaseType(String nonIesCaseType) {
        this.nonIesCaseType = nonIesCaseType;
    }

    
    @Column(name="PREFERRED_LANG_CD", length=2)
    public String getPreferredLangCd() {
        return this.preferredLangCd;
    }
    
    public void setPreferredLangCd(String preferredLangCd) {
        this.preferredLangCd = preferredLangCd;
    }

    
    @Column(name="OTHER_LANG", length=30)
    public String getOtherLang() {
        return this.otherLang;
    }
    
    public void setOtherLang(String otherLang) {
        this.otherLang = otherLang;
    }

    
    @Column(name="APL_NOTICE_DT", length=7)
    public LocalDate getAplNoticeDt() {
        return this.aplNoticeDt;
    }
    
    public void setAplNoticeDt(LocalDate aplNoticeDt) {
        this.aplNoticeDt = aplNoticeDt;
    }

    
    @Column(name="RECVD_DT", length=7)
    public LocalDate getRecvdDt() {
        return this.recvdDt;
    }
    
    public void setRecvdDt(LocalDate recvdDt) {
        this.recvdDt = recvdDt;
    }

    
    @Column(name="PERFECTED_DT", length=7)
    public LocalDate getPerfectedDt() {
        return this.perfectedDt;
    }
    
    public void setPerfectedDt(LocalDate perfectedDt) {
        this.perfectedDt = perfectedDt;
    }

    
    @Column(name="POSTMARKED_DT", length=7)
    public LocalDate getPostmarkedDt() {
        return this.postmarkedDt;
    }
    
    public void setPostmarkedDt(LocalDate postmarkedDt) {
        this.postmarkedDt = postmarkedDt;
    }

    
    @Column(name="FILING_METHOD_CD", length=3)
    public String getFilingMethodCd() {
        return this.filingMethodCd;
    }
    
    public void setFilingMethodCd(String filingMethodCd) {
        this.filingMethodCd = filingMethodCd;
    }

    
    @Column(name="MCO_IND", length=1)
    public Character getMcoInd() {
        return this.mcoInd;
    }
    
    public void setMcoInd(Character mcoInd) {
        this.mcoInd = mcoInd;
    }

    
    @Column(name="HOLD_LETTERS_IND", length=1)
    public Character getHoldLettersInd() {
        return this.holdLettersInd;
    }
    
    public void setHoldLettersInd(Character holdLettersInd) {
        this.holdLettersInd = holdLettersInd;
    }

    
    @Column(name="INTERPRETER_IND", length=1)
    public Character getInterpreterInd() {
        return this.interpreterInd;
    }
    
    public void setInterpreterInd(Character interpreterInd) {
        this.interpreterInd = interpreterInd;
    }

    
    @Column(name="EXPEDITED_IND", length=1)
    public Character getExpeditedInd() {
        return this.expeditedInd;
    }
    
    public void setExpeditedInd(Character expeditedInd) {
        this.expeditedInd = expeditedInd;
    }

    
    @Column(name="TYPE_OF_HEARING_CD", length=5)
    public String getTypeOfHearingCd() {
        return this.typeOfHearingCd;
    }
    
    public void setTypeOfHearingCd(String typeOfHearingCd) {
        this.typeOfHearingCd = typeOfHearingCd;
    }

    
    @Column(name="URGENT_IND", length=1)
    public Character getUrgentInd() {
        return this.urgentInd;
    }
    
    public void setUrgentInd(Character urgentInd) {
        this.urgentInd = urgentInd;
    }

    
    @Column(name="HEARING_LOCATION_ID", precision=22, scale=0)
    public BigInteger getHearingLocationId() {
        return this.hearingLocationId;
    }
    
    public void setHearingLocationId(BigInteger hearingLocationId) {
        this.hearingLocationId = hearingLocationId;
    }

    
    @Column(name="ADDRESS_ID", precision=22, scale=0)
    public BigInteger getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(BigInteger addressId) {
        this.addressId = addressId;
    }

    
    @Column(name="HOME_PH_NUM", precision=22, scale=0)
    public BigInteger getHomePhNum() {
        return this.homePhNum;
    }
    
    public void setHomePhNum(BigInteger homePhNum) {
        this.homePhNum = homePhNum;
    }

    
    @Column(name="WORK_PH_NUM", precision=22, scale=0)
    public BigInteger getWorkPhNum() {
        return this.workPhNum;
    }
    
    public void setWorkPhNum(BigInteger workPhNum) {
        this.workPhNum = workPhNum;
    }

    
    @Column(name="EXT_NUM", precision=22, scale=0)
    public BigInteger getExtNum() {
        return this.extNum;
    }
    
    public void setExtNum(BigInteger extNum) {
        this.extNum = extNum;
    }

    
    @Column(name="CELL_PH_NUM", precision=22, scale=0)
    public BigInteger getCellPhNum() {
        return this.cellPhNum;
    }
    
    public void setCellPhNum(BigInteger cellPhNum) {
        this.cellPhNum = cellPhNum;
    }

    
    @Column(name="TDD_OTHER", length=10)
    public String getTddOther() {
        return this.tddOther;
    }
    
    public void setTddOther(String tddOther) {
        this.tddOther = tddOther;
    }

    
    @Column(name="EMAIL_ID", length=125)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="PREFERRED_CNTCT_CD", length=3)
    public String getPreferredCntctCd() {
        return this.preferredCntctCd;
    }
    
    public void setPreferredCntctCd(String preferredCntctCd) {
        this.preferredCntctCd = preferredCntctCd;
    }

    
    @Column(name="ALT_COMM_METHOD_CD", length=2)
    public String getAltCommMethodCd() {
        return this.altCommMethodCd;
    }
    
    public void setAltCommMethodCd(String altCommMethodCd) {
        this.altCommMethodCd = altCommMethodCd;
    }

    
    @Column(name="OFFICE_NUM", precision=22, scale=0)
    public BigInteger getOfficeNum() {
        return this.officeNum;
    }
    
    public void setOfficeNum(BigInteger officeNum) {
        this.officeNum = officeNum;
    }

    
    @Column(name="CONVERSION_IND", length=2)
    public String getConversionInd() {
        return this.conversionInd;
    }
    
    public void setConversionInd(String conversionInd) {
        this.conversionInd = conversionInd;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="KIDS_CASE_ID", length=9)
    public String getKidsCaseId() {
        return this.kidsCaseId;
    }
    
    public void setKidsCaseId(String kidsCaseId) {
        this.kidsCaseId = kidsCaseId;
    }

    
    @Column(name="CC_INT_ID", length=32)
    public String getCcIntId() {
        return this.ccIntId;
    }
    
    public void setCcIntId(String ccIntId) {
        this.ccIntId = ccIntId;
    }

    
    @Column(name="LEGACY_HRNG_NUM", length=20)
    public String getLegacyHrngNum() {
        return this.legacyHrngNum;
    }
    
    public void setLegacyHrngNum(String legacyHrngNum) {
        this.legacyHrngNum = legacyHrngNum;
    }

    
    @Column(name="EXHIBIT_SENT", length=2)
    public String getExhibitSent() {
        return this.exhibitSent;
    }
    
    public void setExhibitSent(String exhibitSent) {
        this.exhibitSent = exhibitSent;
    }

    
    @Column(name="EXHIBIT_SENT_DATE", length=7)
    public LocalDate getExhibitSentDate() {
        return this.exhibitSentDate;
    }
    
    public void setExhibitSentDate(LocalDate exhibitSentDate) {
        this.exhibitSentDate = exhibitSentDate;
    }

    
    @Column(name="ABE_SYNC_IND", length=1)
    public Character getAbeSyncInd() {
        return this.abeSyncInd;
    }
    
    public void setAbeSyncInd(Character abeSyncInd) {
        this.abeSyncInd = abeSyncInd;
    }

    
    @Column(name="CONVERSION_DOC_IND", length=1)
    public Character getConversionDocInd() {
        return this.conversionDocInd;
    }
    
    public void setConversionDocInd(Character conversionDocInd) {
        this.conversionDocInd = conversionDocInd;
    }

    
    @Column(name="SEGMENT_IND", length=1)
    public Character getSegmentInd() {
        return this.segmentInd;
    }
    
    public void setSegmentInd(Character segmentInd) {
        this.segmentInd = segmentInd;
    }

    
    @Column(name="IS_DEPT_REP_APL", length=1)
    public Character getIsDeptRepApl() {
        return this.isDeptRepApl;
    }
    
    public void setIsDeptRepApl(Character isDeptRepApl) {
        this.isDeptRepApl = isDeptRepApl;
    }

    
    @Column(name="DUPLICATE_SW", length=1)
    public Character getDuplicateSw() {
        return this.duplicateSw;
    }
    
    public void setDuplicateSw(Character duplicateSw) {
        this.duplicateSw = duplicateSw;
    }

    
    @Column(name="CALL_NOTES_TXT", length=4000)
    public String getCallNotesTxt() {
        return this.callNotesTxt;
    }
    
    public void setCallNotesTxt(String callNotesTxt) {
        this.callNotesTxt = callNotesTxt;
    }

    
    @Column(name="CALLER_RTL_CD", length=45)
    public String getCallerRtlCd() {
        return this.callerRtlCd;
    }
    
    public void setCallerRtlCd(String callerRtlCd) {
        this.callerRtlCd = callerRtlCd;
    }

    
    @Column(name="CALLER_FIRST_NAME", length=45)
    public String getCallerFirstName() {
        return this.callerFirstName;
    }
    
    public void setCallerFirstName(String callerFirstName) {
        this.callerFirstName = callerFirstName;
    }

    
    @Column(name="CALLER_LAST_NAME", length=45)
    public String getCallerLastName() {
        return this.callerLastName;
    }
    
    public void setCallerLastName(String callerLastName) {
        this.callerLastName = callerLastName;
    }

    
    @Column(name="CALLER_PHONE_NUM", precision=10, scale=0)
    public Long getCallerPhoneNum() {
        return this.callerPhoneNum;
    }
    
    public void setCallerPhoneNum(Long callerPhoneNum) {
        this.callerPhoneNum = callerPhoneNum;
    }

    
    @Column(name="DATE_APPLY_CVRG_TXT", length=25)
    public String getDateApplyCvrgTxt() {
        return this.dateApplyCvrgTxt;
    }
    
    public void setDateApplyCvrgTxt(String dateApplyCvrgTxt) {
        this.dateApplyCvrgTxt = dateApplyCvrgTxt;
    }
   */
    
    @Column(name="APPL_EXT2_NUM", precision=6, scale=0)
    public Integer getApplExt2Num() {
        return this.applExt2Num;
    }
    
    public void setApplExt2Num(Integer applExt2Num) {
        this.applExt2Num = applExt2Num;
    }
/*
    
    @Column(name="CALLER_PHN_EXT_NUM", precision=6, scale=0)
    public Integer getCallerPhnExtNum() {
        return this.callerPhnExtNum;
    }
    
    public void setCallerPhnExtNum(Integer callerPhnExtNum) {
        this.callerPhnExtNum = callerPhnExtNum;
    }

    
    @Column(name="CALLER_INTR_USED_SW", length=1)
    public Character getCallerIntrUsedSw() {
        return this.callerIntrUsedSw;
    }
    
    public void setCallerIntrUsedSw(Character callerIntrUsedSw) {
        this.callerIntrUsedSw = callerIntrUsedSw;
    }

    
    @Column(name="APPL_IN_SYS_SW", length=1)
    public Character getApplInSysSw() {
        return this.applInSysSw;
    }
    
    public void setApplInSysSw(Character applInSysSw) {
        this.applInSysSw = applInSysSw;
    }

    
    @Column(name="HAS_SSN_SW", length=1)
    public Character getHasSsnSw() {
        return this.hasSsnSw;
    }
    
    public void setHasSsnSw(Character hasSsnSw) {
        this.hasSsnSw = hasSsnSw;
    }

    
    @Column(name="PROVIDE_ELIG_SW", length=1)
    public Character getProvideEligSw() {
        return this.provideEligSw;
    }
    
    public void setProvideEligSw(Character provideEligSw) {
        this.provideEligSw = provideEligSw;
    }

    
    @Column(name="CALLER_IS_APPL_SW", length=1)
    public Character getCallerIsApplSw() {
        return this.callerIsApplSw;
    }
    
    public void setCallerIsApplSw(Character callerIsApplSw) {
        this.callerIsApplSw = callerIsApplSw;
    }

    
    @Column(name="LINKED_APPL_TXT", length=200)
    public String getLinkedApplTxt() {
        return this.linkedApplTxt;
    }
    
    public void setLinkedApplTxt(String linkedApplTxt) {
        this.linkedApplTxt = linkedApplTxt;
    }

    
    @Column(name="CALLER_PRFRD_LANG_CD", length=2)
    public String getCallerPrfrdLangCd() {
        return this.callerPrfrdLangCd;
    }
    
    public void setCallerPrfrdLangCd(String callerPrfrdLangCd) {
        this.callerPrfrdLangCd = callerPrfrdLangCd;
    }

    
    @Column(name="UPDATE_DT", length=7)
    public LocalDate getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(LocalDate updateDt) {
        this.updateDt = updateDt;
    }

    
    @Column(name="UPDATE_USER_ID", length=20)
    public String getUpdateUserId() {
        return this.updateUserId;
    }
    
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    
    @Column(name="CALLER_PRFRD_LANG_TXT", length=25)
    public String getCallerPrfrdLangTxt() {
        return this.callerPrfrdLangTxt;
    }
    
    public void setCallerPrfrdLangTxt(String callerPrfrdLangTxt) {
        this.callerPrfrdLangTxt = callerPrfrdLangTxt;
    }

    
    @Column(name="APL_POT_ASSC_TXT", length=250)
    public String getAplPotAsscTxt() {
        return this.aplPotAsscTxt;
    }
    
    public void setAplPotAsscTxt(String aplPotAsscTxt) {
        this.aplPotAsscTxt = aplPotAsscTxt;
    }

    
    @Column(name="FAIR_HEARING", length=1)
    public Character getFairHearing() {
        return this.fairHearing;
    }
    
    public void setFairHearing(Character fairHearing) {
        this.fairHearing = fairHearing;
    }

    
    @Column(name="FAIR_HEARING_METHOD", length=10)
    public String getFairHearingMethod() {
        return this.fairHearingMethod;
    }
    
    public void setFairHearingMethod(String fairHearingMethod) {
        this.fairHearingMethod = fairHearingMethod;
    }

*/


}


