package com.deloitte.nextgen.ha.entity;
// Generated May 16, 2021 11:46:32 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmRequestProgDetailsId generated by hbm2java
 */
@Embeddable
public class AmRequestProgDetailsId  implements java.io.Serializable {


     private BigInteger amPrgDtlSeq;
     private BigInteger aplNum;

    /*public AmRequestProgDetailsId() {
    }

    public AmRequestProgDetailsId(BigInteger amPrgDtlSeq, BigInteger aplNum) {
       this.amPrgDtlSeq = amPrgDtlSeq;
       this.aplNum = aplNum;
    }
   


    @Column(name="AM_PRG_DTL_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getAmPrgDtlSeq() {
        return this.amPrgDtlSeq;
    }
    
    public void setAmPrgDtlSeq(BigInteger amPrgDtlSeq) {
        this.amPrgDtlSeq = amPrgDtlSeq;
    }


    @Column(name="APL_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getAplNum() {
        return this.aplNum;
    }
    
    public void setAplNum(BigInteger aplNum) {
        this.aplNum = aplNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmRequestProgDetailsId) ) return false;
		 AmRequestProgDetailsId castOther = ( AmRequestProgDetailsId ) other; 
         
		 return ( (this.getAmPrgDtlSeq()==castOther.getAmPrgDtlSeq()) || ( this.getAmPrgDtlSeq()!=null && castOther.getAmPrgDtlSeq()!=null && this.getAmPrgDtlSeq().equals(castOther.getAmPrgDtlSeq()) ) )
 && ( (this.getAplNum()==castOther.getAplNum()) || ( this.getAplNum()!=null && castOther.getAplNum()!=null && this.getAplNum().equals(castOther.getAplNum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAmPrgDtlSeq() == null ? 0 : this.getAmPrgDtlSeq().hashCode() );
         result = 37 * result + ( getAplNum() == null ? 0 : this.getAplNum().hashCode() );
         return result;
   }   
*/

}


