package com.deloitte.nextgen.ha.entity;
// Generated Jan 20, 2021 8:19:48 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmResolutionA generated by hbm2java
 */
@Entity
@Table(name="AM_RESOLUTION_A"
    ,schema="IE_APP_ONLINE"
)
public class AmResolutionA  implements java.io.Serializable {


     private AmResolutionAId id;
     private Character aplResolvedAiSw;
     private String aplResolvedResearchCd;
     private Character phoneContactSw;
     private Character sendProofAiSw;
     private Character tedsCaseFoundSw;
     private Character proofAiReceivedSw;
     private LocalDate phoneContactDt;
     private String phoneContactTxt;
     private LocalDate proofAiReceivedDt;
     private String resNotesTxt;
     private LocalDate sendProofAiDt;
     private String createUserId;
     private LocalDate createDt;
     private LocalDate updateDt;
     private String updateUserId;
     private BigInteger uniqueTransId;
     private LocalDate archiveDt;
     private String auditUserId;
     private LocalDate auditDt;
     private String aplResolvedAiTxt;
     private String aplResolvedEdCd;
     private Character delayedAppSw;
     private Character aplRqstTimelyRnSw;
     private Character goodCauseTimelyRnSw;
     private Character win90DaySw;
     private Character pcktLocSw;
     private Character pcktRsntSw;
     private String pcktTrckgNum;
     private Character rnAplRsnCd;
     private Character rnInfoRcvdSw;
     private Character algRtnPcktSw;
     private Character prfSrvcSw;
     private String rnwlNotesTxt;
     private String goodCauseTimelyRnTxt;

    public AmResolutionA() {
    }

	
    public AmResolutionA(AmResolutionAId id, String createUserId, LocalDate createDt, BigInteger uniqueTransId, LocalDate archiveDt) {
        this.id = id;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.archiveDt = archiveDt;
    }
    public AmResolutionA(AmResolutionAId id, Character aplResolvedAiSw, String aplResolvedResearchCd, Character phoneContactSw, Character sendProofAiSw, Character tedsCaseFoundSw, Character proofAiReceivedSw, LocalDate phoneContactDt, String phoneContactTxt, LocalDate proofAiReceivedDt, String resNotesTxt, LocalDate sendProofAiDt, String createUserId, LocalDate createDt, LocalDate updateDt, String updateUserId, BigInteger uniqueTransId, LocalDate archiveDt, String auditUserId, LocalDate auditDt, String aplResolvedAiTxt, String aplResolvedEdCd, Character delayedAppSw, Character aplRqstTimelyRnSw, Character goodCauseTimelyRnSw, Character win90DaySw, Character pcktLocSw, Character pcktRsntSw, String pcktTrckgNum, Character rnAplRsnCd, Character rnInfoRcvdSw, Character algRtnPcktSw, Character prfSrvcSw, String rnwlNotesTxt, String goodCauseTimelyRnTxt) {
       this.id = id;
       this.aplResolvedAiSw = aplResolvedAiSw;
       this.aplResolvedResearchCd = aplResolvedResearchCd;
       this.phoneContactSw = phoneContactSw;
       this.sendProofAiSw = sendProofAiSw;
       this.tedsCaseFoundSw = tedsCaseFoundSw;
       this.proofAiReceivedSw = proofAiReceivedSw;
       this.phoneContactDt = phoneContactDt;
       this.phoneContactTxt = phoneContactTxt;
       this.proofAiReceivedDt = proofAiReceivedDt;
       this.resNotesTxt = resNotesTxt;
       this.sendProofAiDt = sendProofAiDt;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.updateDt = updateDt;
       this.updateUserId = updateUserId;
       this.uniqueTransId = uniqueTransId;
       this.archiveDt = archiveDt;
       this.auditUserId = auditUserId;
       this.auditDt = auditDt;
       this.aplResolvedAiTxt = aplResolvedAiTxt;
       this.aplResolvedEdCd = aplResolvedEdCd;
       this.delayedAppSw = delayedAppSw;
       this.aplRqstTimelyRnSw = aplRqstTimelyRnSw;
       this.goodCauseTimelyRnSw = goodCauseTimelyRnSw;
       this.win90DaySw = win90DaySw;
       this.pcktLocSw = pcktLocSw;
       this.pcktRsntSw = pcktRsntSw;
       this.pcktTrckgNum = pcktTrckgNum;
       this.rnAplRsnCd = rnAplRsnCd;
       this.rnInfoRcvdSw = rnInfoRcvdSw;
       this.algRtnPcktSw = algRtnPcktSw;
       this.prfSrvcSw = prfSrvcSw;
       this.rnwlNotesTxt = rnwlNotesTxt;
       this.goodCauseTimelyRnTxt = goodCauseTimelyRnTxt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="aplNum", column=@Column(name="APL_NUM", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="historySeq", column=@Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0) ) } )
    public AmResolutionAId getId() {
        return this.id;
    }
    
    public void setId(AmResolutionAId id) {
        this.id = id;
    }

    
    @Column(name="APL_RESOLVED_AI_SW", length=1)
    public Character getAplResolvedAiSw() {
        return this.aplResolvedAiSw;
    }
    
    public void setAplResolvedAiSw(Character aplResolvedAiSw) {
        this.aplResolvedAiSw = aplResolvedAiSw;
    }

    
    @Column(name="APL_RESOLVED_RESEARCH_CD", length=2)
    public String getAplResolvedResearchCd() {
        return this.aplResolvedResearchCd;
    }
    
    public void setAplResolvedResearchCd(String aplResolvedResearchCd) {
        this.aplResolvedResearchCd = aplResolvedResearchCd;
    }

    
    @Column(name="PHONE_CONTACT_SW", length=1)
    public Character getPhoneContactSw() {
        return this.phoneContactSw;
    }
    
    public void setPhoneContactSw(Character phoneContactSw) {
        this.phoneContactSw = phoneContactSw;
    }

    
    @Column(name="SEND_PROOF_AI_SW", length=1)
    public Character getSendProofAiSw() {
        return this.sendProofAiSw;
    }
    
    public void setSendProofAiSw(Character sendProofAiSw) {
        this.sendProofAiSw = sendProofAiSw;
    }

    
    @Column(name="TEDS_CASE_FOUND_SW", length=1)
    public Character getTedsCaseFoundSw() {
        return this.tedsCaseFoundSw;
    }
    
    public void setTedsCaseFoundSw(Character tedsCaseFoundSw) {
        this.tedsCaseFoundSw = tedsCaseFoundSw;
    }

    
    @Column(name="PROOF_AI_RECEIVED_SW", length=1)
    public Character getProofAiReceivedSw() {
        return this.proofAiReceivedSw;
    }
    
    public void setProofAiReceivedSw(Character proofAiReceivedSw) {
        this.proofAiReceivedSw = proofAiReceivedSw;
    }

    
    @Column(name="PHONE_CONTACT_DT", length=7)
    public LocalDate getPhoneContactDt() {
        return this.phoneContactDt;
    }
    
    public void setPhoneContactDt(LocalDate phoneContactDt) {
        this.phoneContactDt = phoneContactDt;
    }

    
    @Column(name="PHONE_CONTACT_TXT", length=4000)
    public String getPhoneContactTxt() {
        return this.phoneContactTxt;
    }
    
    public void setPhoneContactTxt(String phoneContactTxt) {
        this.phoneContactTxt = phoneContactTxt;
    }

    
    @Column(name="PROOF_AI_RECEIVED_DT", length=7)
    public LocalDate getProofAiReceivedDt() {
        return this.proofAiReceivedDt;
    }
    
    public void setProofAiReceivedDt(LocalDate proofAiReceivedDt) {
        this.proofAiReceivedDt = proofAiReceivedDt;
    }

    
    @Column(name="RES_NOTES_TXT", length=4000)
    public String getResNotesTxt() {
        return this.resNotesTxt;
    }
    
    public void setResNotesTxt(String resNotesTxt) {
        this.resNotesTxt = resNotesTxt;
    }

    
    @Column(name="SEND_PROOF_AI_DT", length=7)
    public LocalDate getSendProofAiDt() {
        return this.sendProofAiDt;
    }
    
    public void setSendProofAiDt(LocalDate sendProofAiDt) {
        this.sendProofAiDt = sendProofAiDt;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UPDATE_DT", length=7)
    public LocalDate getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(LocalDate updateDt) {
        this.updateDt = updateDt;
    }

    
    @Column(name="UPDATE_USER_ID", length=20)
    public String getUpdateUserId() {
        return this.updateUserId;
    }
    
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="AUDIT_USER_ID", length=20)
    public String getAuditUserId() {
        return this.auditUserId;
    }
    
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    
    @Column(name="AUDIT_DT", length=7)
    public LocalDate getAuditDt() {
        return this.auditDt;
    }
    
    public void setAuditDt(LocalDate auditDt) {
        this.auditDt = auditDt;
    }

    
    @Column(name="APL_RESOLVED_AI_TXT", length=1000)
    public String getAplResolvedAiTxt() {
        return this.aplResolvedAiTxt;
    }
    
    public void setAplResolvedAiTxt(String aplResolvedAiTxt) {
        this.aplResolvedAiTxt = aplResolvedAiTxt;
    }

    
    @Column(name="APL_RESOLVED_ED_CD", length=2)
    public String getAplResolvedEdCd() {
        return this.aplResolvedEdCd;
    }
    
    public void setAplResolvedEdCd(String aplResolvedEdCd) {
        this.aplResolvedEdCd = aplResolvedEdCd;
    }

    
    @Column(name="DELAYED_APP_SW", length=1)
    public Character getDelayedAppSw() {
        return this.delayedAppSw;
    }
    
    public void setDelayedAppSw(Character delayedAppSw) {
        this.delayedAppSw = delayedAppSw;
    }

    
    @Column(name="APL_RQST_TIMELY_RN_SW", length=1)
    public Character getAplRqstTimelyRnSw() {
        return this.aplRqstTimelyRnSw;
    }
    
    public void setAplRqstTimelyRnSw(Character aplRqstTimelyRnSw) {
        this.aplRqstTimelyRnSw = aplRqstTimelyRnSw;
    }

    
    @Column(name="GOOD_CAUSE_TIMELY_RN_SW", length=1)
    public Character getGoodCauseTimelyRnSw() {
        return this.goodCauseTimelyRnSw;
    }
    
    public void setGoodCauseTimelyRnSw(Character goodCauseTimelyRnSw) {
        this.goodCauseTimelyRnSw = goodCauseTimelyRnSw;
    }

    
    @Column(name="WIN_90_DAY_SW", length=1)
    public Character getWin90DaySw() {
        return this.win90DaySw;
    }
    
    public void setWin90DaySw(Character win90DaySw) {
        this.win90DaySw = win90DaySw;
    }

    
    @Column(name="PCKT_LOC_SW", length=1)
    public Character getPcktLocSw() {
        return this.pcktLocSw;
    }
    
    public void setPcktLocSw(Character pcktLocSw) {
        this.pcktLocSw = pcktLocSw;
    }

    
    @Column(name="PCKT_RSNT_SW", length=1)
    public Character getPcktRsntSw() {
        return this.pcktRsntSw;
    }
    
    public void setPcktRsntSw(Character pcktRsntSw) {
        this.pcktRsntSw = pcktRsntSw;
    }

    
    @Column(name="PCKT_TRCKG_NUM", length=25)
    public String getPcktTrckgNum() {
        return this.pcktTrckgNum;
    }
    
    public void setPcktTrckgNum(String pcktTrckgNum) {
        this.pcktTrckgNum = pcktTrckgNum;
    }

    
    @Column(name="RN_APL_RSN_CD", length=1)
    public Character getRnAplRsnCd() {
        return this.rnAplRsnCd;
    }
    
    public void setRnAplRsnCd(Character rnAplRsnCd) {
        this.rnAplRsnCd = rnAplRsnCd;
    }

    
    @Column(name="RN_INFO_RCVD_SW", length=1)
    public Character getRnInfoRcvdSw() {
        return this.rnInfoRcvdSw;
    }
    
    public void setRnInfoRcvdSw(Character rnInfoRcvdSw) {
        this.rnInfoRcvdSw = rnInfoRcvdSw;
    }

    
    @Column(name="ALG_RTN_PCKT_SW", length=1)
    public Character getAlgRtnPcktSw() {
        return this.algRtnPcktSw;
    }
    
    public void setAlgRtnPcktSw(Character algRtnPcktSw) {
        this.algRtnPcktSw = algRtnPcktSw;
    }

    
    @Column(name="PRF_SRVC_SW", length=1)
    public Character getPrfSrvcSw() {
        return this.prfSrvcSw;
    }
    
    public void setPrfSrvcSw(Character prfSrvcSw) {
        this.prfSrvcSw = prfSrvcSw;
    }

    
    @Column(name="RNWL_NOTES_TXT", length=2000)
    public String getRnwlNotesTxt() {
        return this.rnwlNotesTxt;
    }
    
    public void setRnwlNotesTxt(String rnwlNotesTxt) {
        this.rnwlNotesTxt = rnwlNotesTxt;
    }

    
    @Column(name="GOOD_CAUSE_TIMELY_RN_TXT", length=100)
    public String getGoodCauseTimelyRnTxt() {
        return this.goodCauseTimelyRnTxt;
    }
    
    public void setGoodCauseTimelyRnTxt(String goodCauseTimelyRnTxt) {
        this.goodCauseTimelyRnTxt = goodCauseTimelyRnTxt;
    }




}


