package com.deloitte.nextgen.ha.entity;
// Generated Nov 2, 2020 9:40:32 PM by Hibernate Tools 5.4.22.Final


import java.math.BigInteger;
import java.time.LocalDate;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * HeAppeal generated by hbm2java
 */
@Entity
@Table(name="HE_APPEAL"
    ,schema="IE_APP_ONLINE"
    , uniqueConstraints = @UniqueConstraint(columnNames={"APPEAL_GROUP_ID", "EFF_BEGIN_DT"}) 
)
public class HeAppeal  implements java.io.Serializable {


     private HeAppealId id;
     private BigInteger historySeq;
     private char meansOfReceiptCd;
     private BigInteger workerId;
     private String regionCd;
     private LocalDate registrationDt;
     private BigInteger hearingOfficerCd;
     private Character repCapacityCd;
     private String createUserId;
     private String updateUserId;
     private LocalDate createDt;
     private LocalDate updateDt;
     private BigInteger uniqueTransId;
     private LocalDate effEndDt;
     private char histNavInd;
     private BigInteger indvId;
     private LocalDate archiveDt;
     private BigInteger unitNum;

    public HeAppeal() {
    }

	
    public HeAppeal(HeAppealId id, BigInteger historySeq, char meansOfReceiptCd, String regionCd, BigInteger hearingOfficerCd, String createUserId, LocalDate createDt, BigInteger uniqueTransId, char histNavInd, BigInteger indvId, LocalDate archiveDt, BigInteger unitNum) {
        this.id = id;
        this.historySeq = historySeq;
        this.meansOfReceiptCd = meansOfReceiptCd;
        this.regionCd = regionCd;
        this.hearingOfficerCd = hearingOfficerCd;
        this.createUserId = createUserId;
        this.createDt = createDt;
        this.uniqueTransId = uniqueTransId;
        this.histNavInd = histNavInd;
        this.indvId = indvId;
        this.archiveDt = archiveDt;
        this.unitNum = unitNum;
    }
    public HeAppeal(HeAppealId id, BigInteger historySeq, char meansOfReceiptCd, BigInteger workerId, String regionCd, LocalDate registrationDt, BigInteger hearingOfficerCd, Character repCapacityCd, String createUserId, String updateUserId, LocalDate createDt, LocalDate updateDt, BigInteger uniqueTransId, LocalDate effEndDt, char histNavInd, BigInteger indvId, LocalDate archiveDt, BigInteger unitNum) {
       this.id = id;
       this.historySeq = historySeq;
       this.meansOfReceiptCd = meansOfReceiptCd;
       this.workerId = workerId;
       this.regionCd = regionCd;
       this.registrationDt = registrationDt;
       this.hearingOfficerCd = hearingOfficerCd;
       this.repCapacityCd = repCapacityCd;
       this.createUserId = createUserId;
       this.updateUserId = updateUserId;
       this.createDt = createDt;
       this.updateDt = updateDt;
       this.uniqueTransId = uniqueTransId;
       this.effEndDt = effEndDt;
       this.histNavInd = histNavInd;
       this.indvId = indvId;
       this.archiveDt = archiveDt;
       this.unitNum = unitNum;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="caseNum", column=@Column(name="CASE_NUM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="appealGroupId", column=@Column(name="APPEAL_GROUP_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="effBeginDt", column=@Column(name="EFF_BEGIN_DT", nullable=false, length=7) ) } )
    public HeAppealId getId() {
        return this.id;
    }
    
    public void setId(HeAppealId id) {
        this.id = id;
    }

    
    @Column(name="HISTORY_SEQ", nullable=false, precision=22, scale=0)
    public BigInteger getHistorySeq() {
        return this.historySeq;
    }
    
    public void setHistorySeq(BigInteger historySeq) {
        this.historySeq = historySeq;
    }

    
    @Column(name="MEANS_OF_RECEIPT_CD", nullable=false, length=1)
    public char getMeansOfReceiptCd() {
        return this.meansOfReceiptCd;
    }
    
    public void setMeansOfReceiptCd(char meansOfReceiptCd) {
        this.meansOfReceiptCd = meansOfReceiptCd;
    }

    
    @Column(name="WORKER_ID", precision=22, scale=0)
    public BigInteger getWorkerId() {
        return this.workerId;
    }
    
    public void setWorkerId(BigInteger workerId) {
        this.workerId = workerId;
    }

    
    @Column(name="REGION_CD", nullable=false, length=3)
    public String getRegionCd() {
        return this.regionCd;
    }
    
    public void setRegionCd(String regionCd) {
        this.regionCd = regionCd;
    }

    
    @Column(name="REGISTRATION_DT", length=7)
    public LocalDate getRegistrationDt() {
        return this.registrationDt;
    }
    
    public void setRegistrationDt(LocalDate registrationDt) {
        this.registrationDt = registrationDt;
    }

    
    @Column(name="HEARING_OFFICER_CD", nullable=false, precision=22, scale=0)
    public BigInteger getHearingOfficerCd() {
        return this.hearingOfficerCd;
    }
    
    public void setHearingOfficerCd(BigInteger hearingOfficerCd) {
        this.hearingOfficerCd = hearingOfficerCd;
    }

    
    @Column(name="REP_CAPACITY_CD", length=1)
    public Character getRepCapacityCd() {
        return this.repCapacityCd;
    }
    
    public void setRepCapacityCd(Character repCapacityCd) {
        this.repCapacityCd = repCapacityCd;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=20)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="UPDATE_USER_ID", length=20)
    public String getUpdateUserId() {
        return this.updateUserId;
    }
    
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    
    @Column(name="CREATE_DT", nullable=false, length=7)
    public LocalDate getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(LocalDate createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UPDATE_DT", length=7)
    public LocalDate getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(LocalDate updateDt) {
        this.updateDt = updateDt;
    }

    
    @Column(name="UNIQUE_TRANS_ID", nullable=false, precision=22, scale=0)
    public BigInteger getUniqueTransId() {
        return this.uniqueTransId;
    }
    
    public void setUniqueTransId(BigInteger uniqueTransId) {
        this.uniqueTransId = uniqueTransId;
    }

    
    @Column(name="EFF_END_DT", length=7)
    public LocalDate getEffEndDt() {
        return this.effEndDt;
    }
    
    public void setEffEndDt(LocalDate effEndDt) {
        this.effEndDt = effEndDt;
    }

    
    @Column(name="HIST_NAV_IND", nullable=false, length=1)
    public char getHistNavInd() {
        return this.histNavInd;
    }
    
    public void setHistNavInd(char histNavInd) {
        this.histNavInd = histNavInd;
    }

    
    @Column(name="INDV_ID", nullable=false, precision=22, scale=0)
    public BigInteger getIndvId() {
        return this.indvId;
    }
    
    public void setIndvId(BigInteger indvId) {
        this.indvId = indvId;
    }

    
    @Column(name="ARCHIVE_DT", nullable=false, length=7)
    public LocalDate getArchiveDt() {
        return this.archiveDt;
    }
    
    public void setArchiveDt(LocalDate archiveDt) {
        this.archiveDt = archiveDt;
    }

    
    @Column(name="UNIT_NUM", nullable=false, precision=22, scale=0)
    public BigInteger getUnitNum() {
        return this.unitNum;
    }
    
    public void setUnitNum(BigInteger unitNum) {
        this.unitNum = unitNum;
    }




}


