logging:
  level:
    root: INFO
    org.reflections: ERROR

spring:
  liquibase:
    enabled: false
    change-log: classpath:db/changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    database: SQL_SERVER
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://localhost:1433;databasename=sampleDB
    username: iewp_ee_dev
    password: iewp_ee_dev
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connectionTestQuery: SELECT 1

nextgen:
  time-travel:
    enabled: true