nodeLinker: node-modules
npmScopes:
  d-lift:
    npmAuthToken: dcdcdf50-1110-4267-ac3f-b98b2e9b53b6
    npmRegistryServer: https://registry.npmjs.org
packageExtensions:
  eslint-config-react-app@*:
    dependencies:
      "@typescript-eslint/eslint-plugin": ^2.0.0
      "@typescript-eslint/parser": ^2.0.0
      babel-eslint: ^10.0.0
      eslint: ^6.0.0
      eslint-plugin-flowtype: ^3.0.0
      eslint-plugin-import: ^2.0.0
      eslint-plugin-jsx-a11y: ^6.0.0
      eslint-plugin-react: ^7.0.0
      eslint-plugin-react-hooks: ^2.0.0
      fsevents: 2.1.3
  react-bootstrap-table2-paginator@*:
    dependencies:
      classnames: ^2.2.5
  react-detect-offline@*:
    dependencies:
      prop-types: ^15.7.2
      react: "*"
  sass-loader@*:
    dependencies:
      node-sass: "*"
yarnPath: .yarn/releases/yarn-2.4.0.cjs
