server:
  compression:
    enabled: true
  port: 8079
  servlet:
    contextPath: /security
spring:
  application:
    name: securityservice
  datasource:
    driver-clas    s-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1522/ORCL
    username: IE_APP_ONLINE
    password: IE_APP_ONLINE
    tom   cat:
      max-active: 50
      max-idle: 20
      max-wait: 20000
      min-idle: 15
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        use_sql_comments: true
    show-sql: true
  security:
    user:
      name: user01
      password: user01

nextgen:
  reference-table:
    preload: false